### ISSUE TITLE
How to Give the index of current tetrahedra

### ISSUE THREAD

**Issue by Jueodu** [FreeFem/FreeFem-sources#100]
Q1 ：How to give the index of current tetrahedra ? ( for 2D Th(0.1, 0.2).nuTriangle, for 3D Th(0.1, 0.1 0.1).   )
Q2 : How to use the volume [give the volume of the current tetrahedra (real value)]?  Th[1].volume exists an error. Th[1].measure ?

**Comment by prj-** [comment]
Q1: Th(x, y, z).nuTriangle
Q2: Th[Th(x, y, z).nuTriangle].measure

**Comment by frederichecht** [comment]
you can use

int nk = Th(x, y, z) or directly nuTet 
Th(x, y, z).measure  or directly  volume 



>
