### ISSUE TITLE
Matrix operations of the form A-cB give unexpected results

### ISSUE THREAD

**Issue by BrunoDegliEsposti** [FreeFem/FreeFem-sources#102]
I am using the 4.2.1 automatic release of FreeFEM for Windows 10.
After executing the following code, matrix D1 is equal to -A, as expected,
whereas matrix D2 is equal to +A, even though they should be the same.
Is this well-known and intentional behaviour? Or is this a bug?
Thank you.

```
matrix A = [[1,2],[3,4]];
real c = -2;
matrix D1 = A+c*A;
matrix D2 = A-2*A;
```

**Comment by prj-** [comment]
It is definitely a bug. Here is a temporary workaround:
```
matrix D2 = 1*A-2*A;
```

**Comment by frederichecht** [comment]
Dear Bruno,

Effectively you find a but un matrix operation

The easy way is never user subtraction just addition of multiply by negative number of apply this patch. 



index 3963e5c6..dbdda06c 100644
--- a/src/fflib/lgmat.cpp
+++ b/src/fflib/lgmat.cpp
@@ -105,7 +105,30 @@ struct Op2_ListCM: public binary_function<R,Matrice_Creuse<R> *,list<tuple<R,Mat
     r ->push_back(p);
     return r;}
 };
-
+template<class R> void PrintL(const char* cc, list<tuple<R,VirtualMatrix<int,R>*,bool> > const  * const lM)
+{
+    if(verbosity>99) return; 
+    typedef typename list<tuple<R,VirtualMatrix<int,R> *,bool> >::const_iterator lconst_iterator;
+    
+    lconst_iterator begin=lM->begin();
+    lconst_iterator end=lM->end();
+    lconst_iterator i;
+    cout << cc << " (" ;
+    for(i=begin;i!=end;i++++)
+    {
+        if(std::get<1>(*i)) // M == 0 => zero matrix
+        {
+            VirtualMatrix<int,R>& M=*std::get<1>(*i);
+            bool transpose = std::get<2>(*i) ;
+            R coef=std::get<0>(*i);
+            cout << "  + " << coef << "*" << &M <<"^" << transpose  ;
+            
+        }
+    }
+    
+    
+    cout << ") "<< endl;
+}
 template<class R>
 struct Op2_ListMC: public binary_function<Matrice_Creuse<R> *,R,list<tuple<R,MatriceCreuse<R> *,bool> > *>
  {
@@ -161,7 +184,7 @@ struct Op2_ListMtC: public binary_function<Matrice_Creuse_Transpose<R> ,R,list<t
 
 
 
-template<class R>
+template<class R,int c=-1>
 struct Op1_LCMd: public unary_function<list<tuple<R,MatriceCreuse<R> *,bool> > *,
 list<tuple<R,MatriceCreuse<R> *,bool> > *  >
 {  //  - ...
@@ -172,8 +195,9 @@ list<tuple<R,MatriceCreuse<R> *,bool> > *  >
     static   RR f(const RR & l)
     {
        typedef typename list<tuple<R,MatriceCreuse<R> *,bool> >::iterator lci;
-       for (lci i= l->begin();i !=l->end();++i)
-             get<0>(*i) *= R(-1);
+        for(lci i= l->begin();i !=l->end();++i)
+            get<0>(*i) *= R(c);
+        PrintL(" - Op1_LCMd: ",l);
        return l;
     }
 
@@ -208,9 +232,12 @@ list<tuple<R,MatriceCreuse<R> *,bool> > *  >
 
     static   RR f(const RR & a,const RR & b)
     {
-        Op1_LCMd<R>::f(b);
-        a->insert(a->end(),b->begin(),b->end());
+        Op1_LCMd<R,-1>::f(b);
+        PrintL("Op2_ListCMCMsub +",a);
+        PrintL(" -(-) ",b);
 
+        a->insert(a->end(),b->begin(),b->end());
+        PrintL(" =>  ",a);
         delete b;
         return a;
     }
@@ -229,8 +256,11 @@ struct Op2_ListMCMadd: public binary_function<Matrice_Creuse<R> *,
 
   static   RR f(const MM & a,const RR & b)
   {
+    // M  + c*L
+    Op1_LCMd<R,cc>::f(b);
+      PrintL("Op2_ListMCMadd M +",b);
 
-    b->push_front(make_tuple<R,MatriceCreuse<R> *>(R(cc),a->A,false));
+    b->push_front(make_tuple<R,MatriceCreuse<R> *,bool>(R(1.),a->A,false));
     return b;
   }
 
@@ -249,7 +279,7 @@ struct Op2_ListCMMadd: public binary_function< list<tuple<R,MatriceCreuse<R> *,b
 
   static   RR f(const RR & a,const MM & b)
   {
-
+    // L + c*M
     a->push_back(make_tuple<R,MatriceCreuse<R> *,bool>(R(cc),b->A,false));
     return a;
   }
@@ -269,6 +299,7 @@ struct Op2_ListMMadd: public binary_function< Matrice_Creuse<R> *,
 
   static   RR f(const MM & a,const MM & b)
   {
+    // M + c M
     L * l=to(a);
     l->push_back(make_tuple<R,MatriceCreuse<R> *>(R(cc),b->A,false));
     return l;
@@ -2814,15 +2845,19 @@ TheOperators->Add("+",
 
        );
     TheOperators->Add("-",
-                      new OneBinaryOperator<Op2_ListCMCMsub<R> >,
-                      new OneBinaryOperator<Op2_ListCMMadd<R,-1> >,
-                      new OneBinaryOperator<Op2_ListMCMadd<R,-1> >,
-                      new OneBinaryOperator<Op2_ListMMadd<R,-1> >
+                      new OneBinaryOperator<Op2_ListCMCMsub<R> >,   //  (L) - (L)
+                      new OneBinaryOperator<Op2_ListCMMadd<R,-1> >, // L - M
+                      new OneBinaryOperator<Op2_ListMCMadd<R,-1> >, // M - L
+                      new OneBinaryOperator<Op2_ListMMadd<R,-1> >   // M - M
 
                       );
  TheOperators->Add("-",
-        new OneUnaryOperator<Op1_LCMd<R> >
+        new OneUnaryOperator<Op1_LCMd<R,-1> >
      );
+TheOperators->Add("+",
+                      new OneUnaryOperator<Op1_LCMd<R,1> >
+                      );
+
     Add<Matrice_Creuse<R> *>("COO",".",new OneOperator1<bool,Matrice_Creuse<R> *>(set_mat_COO<R>) );
     Add<Matrice_Creuse<R> *>("CSR",".",new OneOperator1<bool,Matrice_Creuse<R> *>(set_mat_CSR<R>) );
     Add<Matrice_Creuse<R> *>("CSC",".",new OneOperator1<bool,Matrice_Creuse<R> *>(set_mat_CSC<R>) );
192:ff-git hecht$ 



Best Regards, 

Frédéric Hecht.   

-----------------------------------------------------------------------------------------------------------------------------------
Laboratoire  Jacques-Louis Lions,                UPMC Sorbonne Université
BC187,  4 Place  Jussieu,     75252  PARIS cedex 05,               France
Campus Jussieu,       Barre 15-25,           3 etage           Bureau 307 
Projet Alpines ,   Inria de Paris, 2 rue Simone Iff Voie DQ12 75012 Paris
tel:  +33 1 44274411,        mob: +33 6 62198986,     fax: +33 1 44277200
frederic.hecht@sorbonne-universite.fr https://www.ljll.math.upmc.fr/hecht
software:  FreeFem++          web site:       http://www.freefem.org/ff++

**Comment by frederichecht** [comment]
C'est corrige 
Frederic.
