### ISSUE TITLE
ubuntu 19.04 and libhdf5

### ISSUE THREAD

**Issue by Sonicthh** [FreeFem/FreeFem-sources#104]
I installed FreeFem++ on Ubuntu 19.04 as described in chapter "Ubuntu binary installation" of the documentation. FreeFem++ complains about a missing library:
FreeFem++: error while loading shared libraries: libhdf5_serial.so.100: cannot open shared object file: No such file or directory
as Ubuntu provides libhdf5_serial.so.103 in their libhdf5-dev package.

**Comment by sgarnotel** [comment]
Hi,

The package is build for Ubuntu 18.04, which use `libhdf5-dev-100`.
In Ubuntu 19.04, `libhdf5-dev-103` is used.

You can try to link `libhdf5_serial.so.103` to `libhdf5_serial.so.100` directly in `/usr/lib` (or in the appropriate directory) but I can not guarantee that it will work

**Comment by Sonicthh** [comment]
That workaround does in fact work. It is however unfortunate, that there is no indication for which release your package is supposed to work, or did I miss that?
Do you plan to build a package for the latest ubuntu release as well?

**Comment by sgarnotel** [comment]
No there is no indication on the documentation, I will append a note on it.

Ubuntu package is only build for the current LTS version for now, we do not plan to build it for other version

**Comment by Sonicthh** [comment]
Thank you.
Just in case anyone else needs it, ubuntu puts libhdf5 in /usr/lib/x86_64-linux-gnu/

**Comment by jamiemfoster** [comment]
Apologies if this is a silly request, but could someone explicitly spell out how to implement this workaround. I spent quite some time looking through the documentation for the aforementioned note but could not find it. Thanks in advance.

**Comment by leo-monsaingeon** [comment]
Hi there, sorry to bother I know this thread is closed, but I'm trying to apply the workaround. However I'm no advanced expert in linux, so I have no clue about how to link libhdf5_serial.so.103 to libhdf5_serial.so.100 directly in /usr/lib  (which seems to do the job). Can you please help me out?

**Comment by EvandroMaddes** [comment]
> I confirm that the workaround works also on ubuntu 20.40 Focal Fossa. In case anyone needs it: in order to link `llibhdf5_serial.so.103` to `libhdf5_serial.so.100` just type `sudo ln -s /usr/lib/x86_64-linux-gnu/libhdf5_serial.so.103 /usr/lib/x86_64-linux-gnu/libhdf5_serial.so.100`

I solved a similar error by installing gfortran-7; [see this.](https://askubuntu.com/questions/949308/how-do-i-install-gfortran-7)
