### ISSUE TITLE
Core dump on matrix

### ISSUE THREAD

**Issue by sgarnotel** [FreeFem/FreeFem-sources#105]
The following code end with a core dump despite the resize of the matrix:
```freefem
int n = 10;

matrix A;
A.resize(n, n);

for (int i = 0; i < n; i++)
	for (int j = 0; j < n; j++)
		A(i, j) = i + j;
```

**Comment by prj-** [comment]
The segfault is no more. However, your code doesn't make much sense. You should replace `matrix` by `real[int,int]`, and then do `matrix sparse = A;`. There is no way, as of today, to dynamically set the sparsity pattern of a sparse matrix, like you are doing. If your matrix is in practice sparse, use the constructor `matrix sparse = [I, J, C];` where you can adjust the size of the arrays dynamically.

**Comment by sgarnotel** [comment]
@prj- thanks for your reply.
The full matrix is just for the example, I thinked when matrix is resized I can dynamically add values.

**Comment by frederichecht** [comment]
correct in [develop 20cc2c12] correct [FreeFem/FreeFem-sources] Core dump on matrix
