### ISSUE TITLE
LIBLAPACK not passed down to 3rdparty/ipopt

### ISSUE THREAD

**Issue by Sonicthh** [FreeFem/FreeFem-sources#106]
I ran ./configure --enable-download --enable-optim --with-lapack=-lptlapack --with-blas=-lptf77blas
Afterwards the Makefile.inc in 3rdparty/ipopt only contains
LIBBLAS =  -lptf77blas -lm
LIBLAPACK = -lm
If I change the LIBLAPACK line to 
LIBLAPACK = -lptlapack -lm
compilation of ipopt works.

**Comment by frederichecht** [comment]
the correction in [develop e64d0d19]

brochet:ff-git hecht$ git diff
diff --git a/configure.ac b/configure.ac
index 7c3d0df7..5a6c6926 100644
--- a/configure.ac
+++ b/configure.ac
@@ -1560,10 +1560,6 @@ AC_MSG_CHECKING([for lapack in $LIBS, $ff_blas_libs and -llapack] )
        fi
     fi
 
-AC_MSG_RESULT($ff_lapack_ok)
-if test "$ff_lapack_ok" != no ; then
-AC_SUBST(LAPACKLIBS,$ff_lapack_lib)
-fi
 if test "$ff_lapack_ok" = no; then
     AC_ARG_WITH(lapack,
        AC_HELP_STRING([--with-lapack=library],[Use a specific version of Lapack]),
@@ -1571,6 +1567,10 @@ if test "$ff_lapack_ok" = no; then
        ff_lapack_lib="${withval}"
        LIBS="$ff_lapack_lib $LIBS")
 fi
+AC_MSG_RESULT($ff_lapack_ok)
+if test "$ff_lapack_ok" != no ; then
+AC_SUBST(LAPACKLIBS,$ff_lapack_lib)
+fi
 
 # Lapack configuration for Arpack
