### ISSUE TITLE
Error running Elasticity Equation on 3D Beam (fgets error, plotting issue)

### ISSUE THREAD

**Issue by GitWyd** [FreeFem/FreeFem-sources#107]
After running the code for the 3D beam analysis from the [FreeFem Documentation](https://modules.freefem.org/modules/elasticity/)
See Code below:
```C
load "gmsh"
load "msh3"

//Parameters
real Rho = 8000.;		//Density
real E = 210.e9;			//Young modulus
real Nu = 0.27;		//Poisson ratio

real Gravity = -9.81;	//Gravity

//Mesh
int Fixed = 1;			//Beam fixed label
int Free = 2;			//Beam free label
mesh3 Th = gmshload3("Elasticity3D.msh");

//Fespace
func Pk = P1;
fespace Uh(Th, [Pk, Pk, Pk]);
Uh [ux, uy, uz];
Uh [vx, vy, vz];
Uh [uxp, uyp, uzp];
Uh [uxpp, uypp, uzpp];

//Macro
real sqrt2 = sqrt(2.);
macro Epsilon(ux, uy, uz) [dx(ux), dy(uy), dz(uz),
	(dz(uy)+dy(uz))/sqrt2,
	(dz(ux)+dx(uz))/sqrt2,
	(dy(ux)+dx(uy))/sqrt2] //
macro Divergence(ux, uy, uz) (dx(ux) + dy(uy) + dz(uz)) //

//Problem
real Mu = E/(2.*(1.+Nu));
real Lambda = E*Nu/((1.+Nu)*(1.-2.*Nu));

varf vElasticity ([ux, uy, uz], [vx, vy, vz])
	= int3d(Th)(
		  Lambda * Divergence(vx, vy, vz) * Divergence(ux, uy, uz)
		+ 2. * Mu * (
			  Epsilon(vx, vy, vz)' * Epsilon(ux, uy, uz)
		)
	)
	+ int3d(Th)(
		  Rho * Gravity * vy
	)
	+ on(Fixed, ux=0, uy=0, uz=0)
	;

matrix Elasticity = vElasticity(Uh, Uh, solver=sparsesolver);
real[int] ElasticityBoundary = vElasticity(0, Uh);
ux[] = Elasticity^-1 * ElasticityBoundary;

//Movemesh
Th = movemesh(Th, [x+ux, y+uy, z+uz]);
[ux, uy, uz] = [ux, uy, uz];

//Plot
plot([ux, uy, uz], value=true, cmm="u");
```

I got the following output:

```bash
11663 tetrahedrons
5024 triangles
16687 numElements
fgets error
  -- FESpace: Nb of Nodes 3286 Nb of DoF 9858
  -- FESpace: Nb of Nodes 3286 Nb of DoF 9858
  Plot::  Sorry no ps version for this type of plot 7
times: compile 0.004005s, execution 0.761139s,  mpirank:0
 ######## We forget of deleting   1 Nb pointer,   0Bytes  ,  mpirank 0, memory leak =9760
 CodeAlloc : nb ptr  3351,  size :434024 mpirank: 0
Ok: Normal End
```

How can I fix "Plot::  Sorry no ps version for this type of plot 7" and the "fgets error"?

**Comment by prj-** [comment]
These are not errors, but rather warnings. You can safely ignore those, or use put `verbosity = 0;` at the beginning of your script.

**Comment by GitWyd** [comment]
@prj- thank you for your quick response.
Why doesn't the plot show up when I run the script? How can I make it show up?

**Comment by prj-** [comment]
You probably want to change `plot([ux, uy, uz], value=true, cmm="u");` to `plot([ux, uy, uz], value=true, cmm="u", wait=true);`.

**Comment by GitWyd** [comment]
Just tested it. Unfortunately the plot still doesn't show and the output remains unchanged. Any idea why that might be?
Also, what does "no ps version for this type of plot" mean?

**Comment by frederichecht** [comment]
Der user,

Yes to day the plot of 3d vector field is not implemented. 

Best Regards, 

Frédéric Hecht.   

-----------------------------------------------------------------------------------------------------------------------------------
Laboratoire  Jacques-Louis Lions,                UPMC Sorbonne Université
BC187,  4 Place  Jussieu,     75252  PARIS cedex 05,               France
Campus Jussieu,       Barre 15-25,           3 etage           Bureau 307 
Projet Alpines ,   Inria de Paris, 2 rue Simone Iff Voie DQ12 75012 Paris
tel:  +33 1 44274411,        mob: +33 6 62198986,     fax: +33 1 44277200
frederic.hecht@sorbonne-universite.fr https://www.ljll.math.upmc.fr/hecht
software:  FreeFem++          web site:       http://www.freefem.org/ff++
