### ISSUE TITLE
savevtk issue

### ISSUE THREAD

**Issue by paolopiers** [FreeFem/FreeFem-sources#109]
Good evening to everyone.
I am running FreeFem++ 4.2.1-1 on ArchLinux.
I downloaded the program from the AUR repository at this link

`https://aur.archlinux.org/packages/freefem`

I am posting this message to report an issue with the `savevtk()` function when it comes to saving a 3D mesh, of type `meshS`. 
The program compiles correctly but the output mesh is only two-dimensional instead of three-dimensional.
I tried the same code on my Mac and the `savevtk()` command correctly outputs a three-dimensional mesh.

Could you please check and solve this issue?

Thanks a lot in advance and best regards,

Paolo

**Comment by AFourmont** [comment]
Dear Paolo,
Thanks for this report. You find a bug ant it’s correct [develop](https://github.com/FreeFem/FreeFem-sources/commit/a61fd5f8defa3693917c64cd9605956fbe4b5ec8)

Sorry for the inconvenience 
Axel

**Comment by paolopiers** [comment]
Dear Alex,
thank you for fixing the bug.
Could you please tell me how I can update this library without having to reinstall the whole FreeFem++?

Best,

Paolo

**Comment by sgarnotel** [comment]
You can try this operation (not sure that works correctly):
- download the zip file [iovtk.zip](https://github.com/FreeFem/FreeFem-sources/files/3533378/iovtk.zip) and uncompress it, you have `iovtk.so`
- copy `iovtk.so` it to `/usr/lib/ff++/${VERSION}/lib/` (version depending on the AUR package, you need sudo to do that)
- try your script

Please, give us a feedback.

Best,
Simon

**Comment by paolopiers** [comment]
Thank you Simon. The procedure works.
Now I can visualize my three-dimensional mesh.
I think that the issue can now be regarded as solved.

Best,

Paolo

**Comment by sgarnotel** [comment]
Nice, and thanks for you feedback
