### ISSUE TITLE
Issues in parallel computing

### ISSUE THREAD

**Issue by zhaog6** [FreeFem/FreeFem-sources#111]
Dear all,

I‘m using the PETSc and HPDDM interfaces to do parallel computing, but there are three questions.
1. `dscalprod(D, u, v)` function seemingly cannot work. Could you tell me if it has been changed in the new version?

2. Having distributed data to each process and got local solution by solve in each process, sometimes I would like to get global solution or L^2/H^1 Error (rather than residual) to compute convergence order, Is there any way to get the global solution?

Thanks.

**Comment by prj-** [comment]
1. What error are you getting? What are `u` and `v`? Maybe you meant `dscalprod(D, u[], v[])`?
2. It is possible to get the global solution, but it should be avoided at all cost. What are you interested in exactly? There is one example here to compute the [global solution](https://github.com/FreeFem/FreeFem-sources/blob/develop/examples/hpddm/Newton-adaptmesh-2d-PETSc.edp#L72-L76), but maybe I can provide a better solution depending on what you want to do.

**Comment by zhaog6** [comment]
Thank you, I am gonna implement my new method by using parallel tools in FreeFEM, whereas I don't know much about parallel tools in FreeFEM and I am learning it. I just want to compute H^1 error to test if my method keeps accuracy. but before I don't know how to use these distributed data to calculate it. I once tried in the following way, and the general framework is as follow:
```
//-------------------------------------+
//   Exact solution for test accuracy  |
//-------------------------------------+
func u = sin(2*pi*x) * sin(2*pi*y);
func ux = 2*pi * cos(2*pi*x) * sin(2*pi*y);
func uy = 2*pi * sin(2*pi*x) * cos(2*pi*y);
...

//---------------+
//   My method   |
//---------------+
...
...
...

//-----------------------+
//   Compute H^1 Error   |
//-----------------------+
// here uh is FE solution gained by "My method", ux,uy are derivative of u
real dH1Error = intN(Th) ( (ux - dx(uh))^2 + (uy - dy(uh))^2 );
real H1Error;
mpiAllReduce(dH1Error, H1Error, mpiCommWorld, mpiSUM);
H1Error = sqrt(H1Error);
if (mpirank == 0) cout << "||u - uh||_1 = " << H1Error << endl;

```
but the H^1 error from single process is slightly different from that from multiple processes, so I still thought I used it wrong before. Now I understand it through the example you provide.  Thank you so much for your kind help again！

**Comment by prj-** [comment]
No problem. I need to update the tutorial to include more details about these functions, you are right. Let me give you some details here. About `changeNumbering(dA, inOut, inOutPetsc, inverse = bool, exchange = bool)`, which is the most important routine in your case:

- `dA`: FreeFEM object of type `Mat` (which is an underlying PETSc Mat), you can do operations such as `dA * x`, `dA^-1 * x`, use `dA` in PETSc nonlinear solvers or time-steppers...
- `inOut`: input/output vector in FreeFEM numbering (distributed vectors with ghost elements, overlapping information)
- `inOutPETSc`: input/output vector in PETSc numbering (distributed vectors without ghost elements, nonoverlapping information)
- `inverse`: if `true`, goes from PETSc numbering to FreeFEM numbering ; if `false` (default), goes from FreeFEM numbering to PETSc numbering
- `exchange`: if `true`, exchange ghost values so that the values are consistent among subdomains (this makes only sense when `inverse = true`)

In practice, if you just want to compute an H^1 norm, here is how you can proceed. Distribute your [global mesh](https://github.com/FreeFem/FreeFem-sources/blob/develop/examples/hpddm/minimal-surface-2d-Tao-PETSc.edp#L13-L29) and compute a nonoverlapping mesh (`ThNo` in the example). Compute your norm on `ThNo` and do a [reduction](https://github.com/FreeFem/FreeFem-sources/blob/develop/examples/hpddm/minimal-surface-2d-Tao-PETSc.edp#L36-L37), like you did in the first place. The example is in the 2D but the same applies in 3D. Feel free to create a pull request with your example (in `examples/hpddm`) if you want to contribute to FreeFEM, and if you want me to review or/and fix your code.

**Comment by zhaog6** [comment]
OK. Thank you ! There is a little doubt to computing H^1 error. The distributed FE-solution `uh` is obtained through solving on the following distributed overlapping mesh
```
macro fe P1 //
meshN Th = square(1024, 1024);
build(Th, s, intersection, fe, mpiCommWorld);
```
but if building non-overlapping mesh `ThNo` in addition by the following way
```
meshN ThNo = square(1024, 1024);
fespace Ph(ThNo, P0);
Ph part;
if (mpirank == 0) partitionerSeq(part[], ThNo, mpisize);
buildWithPartitioning(ThNo, part[], s, intersection, D, fe, mpiCommWorld);
ThNo = change(ThNo, fregion=part[][nuTriangle]);

```
computing H^1 error on `ThNo` may be wrong since `uh` is obtained on distributed overlapping mesh `Th`, How to deal with this？Thanks

**Comment by prj-** [comment]
Here is how to do it.
```
macro dimension()2//
macro fe()P1//
macro def(u)u//
macro init(u)u//
include "macro_ddm.idp"
meshN Th = square(64, 64);
fespace Ph(Th, P0);
Ph part;
if (mpirank == 0) partitionerSeq(part[], Th, mpisize);
partitionerPar(part[], Th, mpiCommWorld, mpisize);
int[int][int] intersection;
int s = 1;
real[int] D;
buildWithPartitioning(Th, part[], s, intersection, D, fe, mpiCommWorld); // data for PETSc or HPDDM
meshN ThNo = trunc(Th, abs(part - mpirank) < 0.1);
fespace Wh(Th, fe);
fespace WhNo(ThNo, fe);
Wh uh = x + sin(y);
WhNo uhNo = uh; // interpolation from overlap to no overlap
real glob, loc = int2d(ThNo)(uhNo^2 + dx(uhNo)^2);
mpiAllReduce(loc, glob, mpiCommWorld, mpiSUM);
```

**Comment by zhaog6** [comment]
I get it. Thank you so much!

**Comment by zhaog6** [comment]
Dear prj

I read `examples/hpddm/stokes-2d-block-PETSc.edp`, there is one puzzle. in my method, the form of coefficient matrix of equations is as follow:
```
// here A is a square matrix(nxn), b is a column vector(nx1), c is a scalar(1x1)
F = [[A, b],
     [b', c]]
```
this is equivalent to solution&test function "space" is a hyperplane. when it is written into distributed matrix, I have learned the matrix A can build through imitating this example, namely,
```
int s = 1;
int[int][int] intersection;
real[int] D;

varf vA(u, v) = intN(Th) (...);
matrix A = vA(Vh, Vh);
Mat dA(A, intersection, D);
```
but for building the scalar `c` in block matrix `F`, there seems to be no informations of `intersection` and `D`, then I wrote it like this
```
// for b
varf vb(unused, v) = intN(Th) (... * v);
real[int] bVector = vb(0, Vh);
matrix b = [[ bVector ]];  // transform vector form to matrix form

// for c
real cScalar = intN(Th) (...);
matrix c = [[ cScalar ]];  // transform scalar to matrix form

// build distributed block matrix
Mat dc(c);
Mat db(dA,  dc, b);
Mat dS = [[dA, db],
          [db', dc]];
```
but it is not work, I think I know little about `Mat` and related interface function, so I would like to ask how to deal with it for my question?
Thank you for taking the time to read my questions

**Comment by prj-** [comment]
Could you please provide a running example, so that I can check on my side what is not working (if you want this to be private, you may find my address [here](https://github.com/FreeFem/FreeFem-sources/blob/master/plugin/mpi/parmetis.cpp#L22))?
You shouldn't need to convert `bVector` into a `Mat`. There should also be no need to convert `cScalar` into a `Mat`, but currently, there is no support for a nonzero scalar (2,2) block. I'll fix that right now. What you are doing is quite ingenious, but slightly suboptimal.

**Comment by zhaog6** [comment]
No problem, I will send an example to your mailbox after I add some comments. Later, I will also send a document to describe the scheme.

**Comment by zhaog6** [comment]
Dear prj

I update the PETSc plugin according to your suggestion, but it always makes mistakes. Afterwards,  I run the example `laplace-lagrange-PETSc.edp` and `stokes-2d-block-PETSc.edp`, both report `PETSc ERROR`,  but running some examples of others, It works well, on Ubuntu v4.4.

**Comment by prj-** [comment]
What error are you getting?

**Comment by zhaog6** [comment]
I use `ff-mpirun -np 4 laplace-lagrange-PETSc.edp` to run this file on my server, `PETSc Errors` are reported as follow,
<img width="1677" alt="屏幕快照 2019-08-30 08 33 22" src="https://user-images.githubusercontent.com/31978442/63985165-eab9e280-cb00-11e9-97e4-48bc561dc915.png">

**Comment by prj-** [comment]
May I ask if you are you using OpenMPI or MPICH, please?

**Comment by zhaog6** [comment]
Yeah, if running the both examples on one process, it's OK, but if I use multiple processes, it will report `PETSc ERROR`. I see the first line of comment of the two examples say `run with MPI: ff-mpirun -np 4 script.edp`, but I don't know why it reports error when using multiple processes?

**Comment by prj-** [comment]
There are bugs inside OpenMPI. I'll try to see if I can find a workaround. If you have access to another MPI implementation like MPICH or Intel MPI, that's the safest option.

**Comment by zhaog6** [comment]
I won't use fieldsplit preconditioned for the time being. If it's settled, please let me know.

**Comment by zhaog6** [comment]
I would also like to ask a question. In FreeFEM, Is the command `ff-mpirun -np ...` running OpenMPI or MPICH?

**Comment by prj-** [comment]
I think you can figure this out running `ff-mpirun -help`. I do not recommend using `ff-mpirun` because you don't know how `FreeFem++-mpi` is being invoked. I prefer to go for the full command `mpirun -np X FreeFem++-mpi`. That way, you know clearly which `mpirun` is being used.

**Comment by zhaog6** [comment]
Ok, I get it now, thanks！

**Comment by sfmahenk** [comment]
Hi,

sorry to disturb this old issue, but I have a follow-up question on the L^2/H^1 norm part and couldn't find any information about it elsewhere. I would like to compute the L^2 norm of some quantities after each time step of my simulation.

The code posted by @prj- in https://github.com/FreeFem/FreeFem-sources/issues/111#issuecomment-525358579 runs as expected, but I'm struggling to incorporate it into my usual FreeFEM/PETSc-workflow.

If I run

```
load "PETSc"

macro dimension()2//
macro fe()P1//
macro def(u)u//
macro init(u)u//
include "macro_ddm.idp"
meshN Th = square(64, 64);
fespace Ph(Th, P0);
Ph part;
if (mpirank == 0) partitionerSeq(part[], Th, mpisize);
partitionerPar(part[], Th, mpiCommWorld, mpisize);
int[int][int] intersection;
int s = 1;
real[int] D;
buildWithPartitioning(Th, part[], s, intersection, D, fe, mpiCommWorld); // data for PETSc or HPDDM
part = part;
meshN ThNo = trunc(Th, abs(part - mpirank) < 0.1);
fespace Wh(Th, fe);
fespace WhNo(ThNo, fe);
Wh uh = x + sin(y);
WhNo uhNo = uh; // interpolation from overlap to no overlap
real glob, loc = int2d(ThNo)(uhNo^2 + dx(uhNo)^2);
mpiAllReduce(loc, glob, mpiCommWorld, mpiSUM);

Mat A;
createMat(Th, A, fe)
```
it stalls with  `--- global mesh of 2211 elements (prior to refinement) partitioned with metis  --metisA: 4-way Edge-Cut:       3, Balance:  1.01 Nodal=0/Dual 1`

Do I have to call `buildMatWithPartitioning`? What is the proper way to compute L^2/H^1 norms in a parallel freeFEM code using the PETSc interface?

**Comment by prj-** [comment]
You are mixing the "old" decomposition API (`buildMatWithPartitioning`) with the "new" one (`createMat`). I'd suggest you fully switch to the new one.
```
load "PETSc"

macro dimension()2//
macro fe()P1//
macro def(u)u//
macro init(u)u//
include "macro_ddm.idp"
meshN Th = square(64, 64);
fespace Ph(Th, P0);
Ph part;
if (mpirank == 0) partitionerSeq(part[], Th, mpisize); // not needed anymore in practice
partitionerPar(part[], Th, mpiCommWorld, mpisize); // not needed anymore in practice
macro ThUserPartitioning()part[]//  not needed anymore in practice
buildDmesh(Th)
part = 0;
createPartition(Th, part[], P0)
meshN ThNo = trunc(Th, abs(part) > 0.1);
fespace Wh(Th, fe);
fespace WhNo(ThNo, fe);
Wh uh = x + sin(y);
WhNo uhNo = uh; // interpolation from overlap to no overlap
real glob, loc = int2d(ThNo)(uhNo^2 + dx(uhNo)^2);
mpiAllReduce(loc, glob, mpiCommWorld, mpiSUM);

Mat A;
createMat(Th, A, fe)
```
Is that OK for you?

**Comment by sfmahenk** [comment]
Thank you very much for the prompt reply. Yes, that helped me a lot!
