### ISSUE TITLE
tetg error operator

### ISSUE THREAD

**Issue by MPenaR** [FreeFem/FreeFem-sources#113]
Yesterday I compiled FreeFem++ from the latest sources (v4.4) and every test passed (except for one xfail) and then I installed it. However now I'm trying to run and old script which was working and it fails with the following error:

```
Malla = tetg( Malla, switch = "pqaAAYYQ" ) error operator (  <PPKN5Fem2D5Mesh3E> 
 List of choices 
	 (	  <N5Fem2D5Mesh3E> :   <N5Fem2D5MeshSE> )

 Error line number 86, in file 3DArmonico.edp, before  token )
```

The same script with FreeFem++ v 3.62 (on another computer) works fine.

Im using Debian 10 (that's why I recompiled FreeFem++)

**Comment by frederichecht** [comment]
In version 4.2  now we have a  new king of mesh (meshS) surface mesh,




so you must have 3 kind of mesh  mesh3 and meshS. 

meshS MallaS ; 
...

Malla = tetg( MallaS, switch = "pqaAAYYQ" );

if you send the script 
i will correct in 5mn. 
Sorry for the incompatibility. 


Best Regards, 

Frédéric Hecht.   

-----------------------------------------------------------------------------------------------------------------------------------
Laboratoire  Jacques-Louis Lions,                UPMC Sorbonne Université
BC187,  4 Place  Jussieu,     75252  PARIS cedex 05,               France
Campus Jussieu,       Barre 15-25,           3 etage           Bureau 307 
Projet Alpines ,   Inria de Paris, 2 rue Simone Iff Voie DQ12 75012 Paris
tel:  +33 1 44274411,        mob: +33 6 62198986,     fax: +33 1 44277200
frederic.hecht@sorbonne-universite.fr https://www.ljll.math.upmc.fr/hecht
software:  FreeFem++          web site:       http://www.freefem.org/ff++

>  error operator (  
>

**Comment by MPenaR** [comment]
Thank you, I was loading the mesh from a 3d mesh generated by  gmsh:
```
mesh3 MallaReal ;
meshS MallaS ; 
MallaS = gmshload3( "test5.msh" );
MallaReal = tetg( MallaS, switch = "pqaAAYYQ");
```
( if I understood the fix...)
