### ISSUE TITLE
Matrix dot product does not work as documented

### ISSUE THREAD

**Issue by MPiotr** [FreeFem/FreeFem-sources#117]
According to the documentation dot product for two matrices is `real dProd = M'*M`, but I have compile error while trying following code:
```
ifstream in1("matrix.txt");
matrix<complex> A;
in1 >> A;

ifstream in2("matrix.txt");
matrix<complex> B;
in2 >> B; 

matrix<complex> C = B - A;
real cc  = C' * C;
cout << cc << endl;
```

The error is 
```
real cc  = C' * C; error operator <-  <Pd>, <11Matrix_ProdISt7complexIdES1_E>
 List of choices
         (        <P2KNIlE> :   <P2KNIlE>, <l> )...
```

The `matrix.txt` file was saved like follows 
```
ofstream debmat("matrix.txt");
matrix<complex> M = ... //initialization
debmat<< BrtK;
...

```

Checked for version 4.400002 (Fri, Oct 25, 2019  3:45:39 PM - git v4.4.2-3-gd564991b) 64bits, Windows10

**Comment by prj-** [comment]
`real cc  = C' * C;`
should read
`matrix<complex> cc = C' * C;`

**Comment by MPiotr** [comment]
Ok, but how I can get `real d = A' * B;` (I take this from the documentation)?

**Comment by prj-** [comment]
You can't with matrices, that doesn't make sense. Where is it in the documentation?

**Comment by MPiotr** [comment]
Page 336. Matrix operations.
```
Dot product / Outer product
The dot product of two matrices is realized using:
real d = A' * B;
```
I want to have $d = \sum_{i,j} A*_{i,j}*B_{i, j}$. I think it make sense.

**Comment by prj-** [comment]
```
matrix<complex> C = A' * B;
complex d = 0;
for[i,j,v : C] d += v;
```
would be my best bet.

**Comment by MPiotr** [comment]
OK, that's work for me
