### ISSUE TITLE
src/femlib/CheckPtr.cpp patch for FreeBSD

### ISSUE THREAD

**Issue by KouichiHirabayashi** [FreeFem/FreeFem-sources#118]
--- src/femlib/CheckPtr.cpp.orig        2019-12-01 14:23:22.793323000 +0900
+++ src/femlib/CheckPtr.cpp     2019-12-01 14:23:54.603855000 +0900
@@ -27,6 +27,8 @@
  */
 #if __APPLE__
 #include <malloc/malloc.h>
+#elif __FreeBSD__
+#include <stdlib.h>
 #else
 #include <malloc.h>
 #endif

**Comment by prj-** [comment]
Thanks for your contribution, could you please submit that as a pull request? Also, why don't you include `malloc.h` anymore?

**Comment by KouichiHirabayashi** [comment]
Yes, I want anyone to make a pull request.

/usr/include/malloc.h has been deprecated in FreeBSD. (1)

If '#include <malloc.h>' line exists, the following error occurs and
compilation fails.

  --
 /usr/include/malloc.h:3:2: error: "<malloc.h> has been replaced by <stdlib.h>"
 #error "<malloc.h> has been replaced by <stdlib.h>"
  --

At the moment there is a problem with libGLU.so on FreeBSD, ffglut
compiled with gcc crushes.

If we create libGLU.a from glu-9.0.1.tar.xz source and make ffglu
with static link with libGLU.a, FreeFem++ v4.42 will be available
on FreeBSD.


(1) The contents of FreeBSD's /usr/include/malloc.h are as follows.

/* $FreeBSD: releng/12.1/include/malloc.h 86178 2001-11-07 23:14:31Z obrien $ */
#if __STDC__
#error "<malloc.h> has been replaced by <stdlib.h>"
#else
#include <stdlib.h>
#endif

**Comment by prj-** [comment]
Could you please make the PR yourself? I'll approve then, so you'll get the credit you deserve. Thanks in advance.

**Comment by KouichiHirabayashi** [comment]
I'm new to git and don't know how to do it.

**Comment by prj-** [comment]
Does [this](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) make sense to you?

**Comment by cdoucet** [comment]
`#include <cstdib>`
would be better than
`#include <stdlib.h>`

**Comment by KouichiHirabayashi** [comment]
> `#include <cstdib>`
> would be better than
> `#include <stdlib.h>`

There is no problem with FreeBSD. If Apple and Linux are the same,
I think the following changes are good.

--- CheckPtr.cpp.orig   2019-12-03 08:38:14.946918000 +0900
+++ CheckPtr.cpp        2019-12-03 08:38:56.978157000 +0900
@@ -25,11 +25,7 @@
  void* operator new (std::size_t size, const std::nothrow_t& nothrow_value) noexcept;
  p
  */
-#if __APPLE__
-#include <malloc/malloc.h>
-#else
-#include <malloc.h>
-#endif
+#include <cstdlib>
 
 static long verbosity;

**Comment by prj-** [comment]
Cf. #119.
