### ISSUE TITLE
info: libMesh 7 is available

### ISSUE THREAD

**Issue by franckl** [FreeFem/FreeFem-sources#12]
FreeFem is using libMesh v5
See https://github.com/LoicMarechal/libMeshb

**Comment by sgarnotel** [comment]
libMesh7b seems to works: compilation OK and `make check` OK

**Comment by frederichecht** [comment]
donc on peut faire l'upgrade sans probleme.

**Comment by sgarnotel** [comment]
See #44 for approval

**Comment by frederichecht** [comment]
it works
