### ISSUE TITLE
Using array for RHS vectors?

### ISSUE THREAD

**Issue by MPiotr** [FreeFem/FreeFem-sources#121]
Hi, 
I am trying to use an array for storing right-hand-side vectors for different problems sharing the same matrix. However, the result does not look reasonable, and it differs from the case when I hardcode all the RHSs. A simplified example looks like this 
```C
mesh Th = square(10,10);
fespace Vh(Th, P2);

varf Lapl(u,v) = int2d(Th)(-dx(u)*dx(v) - dy(u)*dy(v)) + on(1,3, u = 0);

varf RHSsin1(u,v) = int1d(Th, 2, 4)(sin(pi*y)*v);
varf RHSsin2(u,v) = int1d(Th, 2, 4)(sin(2*pi*y)*v);

matrix<real> M = Lapl(Vh,Vh, solver=UMFPACK);

real [int, int] rhs(2, M.n);     //hardcoded variant (works): 
rhs(0, :) = RHSsin1(0, Vh);      //real [int] rhs1 = RHSsin1(0, Vh);
rhs(1, :) = RHSsin2(0, Vh);      //real [int] rhs2 = RHSsin1(0, Vh);

real[int] u(M.n);
Vh res1, res2;

u = M^-1*(rhs(0, :));
res1[] = u;
plot(res1, cmm = "RHS1");

u = M^-1*(rhs(1,:));
res2[] = u;
plot(res2, cmm = "RHS2");
```
I suspect that an error may be in line `rhs(0, :) = RHSsin1(0, Vh);`, but I can't figure out how to fix it. 
Thanks.

**Comment by prj-** [comment]
Bidimensional arrays are stored using a column-major order, not a row-major order. Hence, if you permute your row and column indices, you'll get the desired result.
```
real [int, int] rhs(M.n, 2);     //hardcoded variant (works):
rhs(:,0) = RHSsin1(0, Vh);       //real [int] rhs1 = RHSsin1(0, Vh);
rhs(:,1) = RHSsin2(0, Vh);       //real [int] rhs2 = RHSsin1(0, Vh);

real[int] u(M.n);
Vh res1, res2;

u = M^-1*rhs(:,0);
res1[] = u;
plot(res1, cmm = "RHS1");

u = M^-1*rhs(:,1);
res2[] = u;
plot(res2, cmm = "RHS2");
```

**Comment by prj-** [comment]
I forgot to add that it's a rather inefficient way of dealing with multiple RHS (if you have many of them).
You can instead write this, which is more efficient (only a single forward/backward solve).
```
matrix<real> M = Lapl(Vh,Vh);

real [int, int] rhs(M.n, 2);
rhs(:,0) = RHSsin1(0, Vh);
rhs(:,1) = RHSsin2(0, Vh);

real[int,int] u(M.n,2);
load "PETSc"
Mat MP(M);
set(MP, sparams = "-pc_type lu");
KSPSolve(MP, rhs, u);
```
This works in parallel as well.

**Comment by MPiotr** [comment]
Thank you very much.
