### ISSUE TITLE
config.h not found by lg.ypp

### ISSUE THREAD

**Issue by csavigny** [FreeFem/FreeFem-sources#126]
i try to install freefem 4.4.2 on SUSE Linux Enterprise Server version 12 SP4 (kernel = 4.4 / proc = x86_64).
i compile freefem with Intel v18 (environment in attachment configure_freefem-4.4.2-SuSE12.txt)

the compilation abort because the header file "config.h" is not found (log in file configure_freefem-4.4.2-SuSE12.log).

lg.ypp(32): catastrophic error: cannot open source file "config.h"

  #include <config.h>

have you an idea?

[configure_freefem-4.4.2-SuSE12.txt](https://github.com/FreeFem/FreeFem-sources/files/4070647/configure_freefem-4.4.2-SuSE12.txt)
[configure_freefem-4.4.2-SuSE12.log](https://github.com/FreeFem/FreeFem-sources/files/4070648/configure_freefem-4.4.2-SuSE12.log)

**Comment by sgarnotel** [comment]
Did you have any error in the `autoreconf -i` step ?
This file is created during this step.

**Comment by prj-** [comment]
Not when using CMake, which I believe is what @csavigny is doing, right?

**Comment by csavigny** [comment]
there is any error when i launch "autoreconf -i"
but the config.h is not created.

# autoreconf -i
configure.ac:447: installing './compile'
configure.ac:293: installing './config.guess'
configure.ac:293: installing './config.sub'
configure.ac:34: installing './install-sh'
configure.ac:34: installing './missing'
parallel-tests: installing './test-driver'
plugin/seq/Makefile.am: installing './depcomp'
# pwd
/tmp/sherpa/freefem/FreeFem-sources-4.4.2
# find . -type f -iname "config.h"

**Comment by csavigny** [comment]
there is any error when i launch "autoreconf -i"
but the config.h is not created.

// # autoreconf -i
configure.ac:447: installing './compile'
configure.ac:293: installing './config.guess'
configure.ac:293: installing './config.sub'
configure.ac:34: installing './install-sh'
configure.ac:34: installing './missing'
parallel-tests: installing './test-driver'
plugin/seq/Makefile.am: installing './depcomp'

// # pwd
/tmp/sherpa/freefem/FreeFem-sources-4.4.2

// # find . -type f -iname "config.h"

**Comment by frederichecht** [comment]
Yes,

TOday the installer is with autoconf, and autoconf build the config.h 
Best Regards, 

Frédéric Hecht.   

-----------------------------------------------------------------------------------------------------------------------------------
Laboratoire  Jacques-Louis Lions,                UPMC Sorbonne Université
BC187,  4 Place  Jussieu,     75252  PARIS cedex 05,               France
Campus Jussieu,       Barre 15-25,           3 etage           Bureau 307 
Projet Alpines ,   Inria de Paris, 2 rue Simone Iff Voie DQ12 75012 Paris
tel:  +33 1 44274411,        mob: +33 6 62198986,     fax: +33 1 44277200
frederic.hecht@sorbonne-universite.fr https://www.ljll.math.upmc.fr/hecht
software:  FreeFem++          web site:       http://www.freefem.org/ff++

**Comment by csavigny** [comment]
thanks, the installation is success with autoconf, configure and make.
Freefem examples without graphics (option "-nw").
but the Freefem gui doesn't work (option "-gw"). there is any error. 
idem with the variable LIBGL_DEBUG=verbose

Have you any ideas how to diag my problem with graphics?
you will find below my shell variables for launching Freefem++

setenv LD_LIBRARY_PATH /appli/gnutool/freefem/4.2.1/requirements/4.4/openblas-0.3.7/lib:/appli/gnutool/freefem/4.2.1/requirements/4.4/CAMD/lib:/appli/gnutool/freefem/4.2.1/requirements/4.4/CHOLMOD/lib:/appli/gnutool/freefem/4.2.1/requirements/4.4/suitesparse-5.6.0/lib:${LD_LIBRARY_PATH}
setenv LD_LIBRARY_PATH /appli/gnutool/freeglut/3.2.1/linuxo/4.4/lib64:${LD_LIBRARY_PATH}
setenv PATH /appli/gnutool/freefem/4.4.2/linuxo/4.4/bin:${PATH}
setenv FF_VERBOSITY 50
setenv FF_INCLUDEPATH /appli/gnutool/freefem/4.4.2/linuxo/4.4/lib/ff++/4.4-2/include
setenv FF_LOADPATH /appli/gnutool/freefem/4.4.2/linuxo/4.4/lib/ff++/4.4-2/lib

**Comment by prj-** [comment]
The option is `-wg`, not `-gw`.

**Comment by csavigny** [comment]
sorry, i use -wg.

**Comment by frederichecht** [comment]
I think the programme ffglut is not compile 

Best Regards, 

Frédéric Hecht.   

-----------------------------------------------------------------------------------------------------------------------------------
Laboratoire  Jacques-Louis Lions,                UPMC Sorbonne Université
BC187,  4 Place  Jussieu,     75252  PARIS cedex 05,               France
Campus Jussieu,       Barre 15-25,           3 etage           Bureau 307 
Projet Alpines ,   Inria de Paris, 2 rue Simone Iff Voie DQ12 75012 Paris
tel:  +33 1 44274411,        mob: +33 6 62198986,     fax: +33 1 44277200
frederic.hecht@sorbonne-universite.fr https://www.ljll.math.upmc.fr/hecht
software:  FreeFem++          web site:       http://www.freefem.org/ff++

**Comment by csavigny** [comment]
the content of the bin directory after the build of freeglut

tree /appli/gnutool/freefem/4.4.2/linuxo/4.4/bin/
|-- FreeFem++
|-- FreeFem++-mpi
|-- FreeFem++-nw
|-- bamg
|-- cvmsh2
|-- ff-mpirun
`-- ffglut

**Comment by frederichecht** [comment]
So 

FreeFem++ LaplaceP1.edp 

must  plot a result  if ffglut is in the search PATH in the shell

**Comment by csavigny** [comment]
yes ffglut works when i process FreeFem++ LaplaceP1.edp
how can i diagnostic my problem about launching FreeFem++ -wg  ? 
FreeFem++ -wg can launch whitout filename?
the launch of FreeFem++ -wg give me this help message!!!

load path :
/appli/gnutool/freefem/4.4.2/linuxo/4.4/lib/ff++/4.4-2/lib/
(.)
include path :
/appli/gnutool/freefem/4.4.2/linuxo/4.4/lib/ff++/4.4-2/include/
(.)
 --  GetEnvironment: verbosity is set to 50
 ARGV 1 -wg
/appli/gnutool/freefem/4.4.2/linuxo/4.4/bin/FreeFem++ - version 4.400002 (Tue Jan 21 16:55:43 CET 2020 - git no git) 64bits
License: LGPL 3+ (https://www.gnu.org/licenses/lgpl-3.0.en.html)
Usage: /appli/gnutool/freefem/4.4.2/linuxo/4.4/bin/FreeFem++ [FreeFEM arguments] filename [script arguments]
FreeFEM arguments:
        -f:     [filename]  script file name
        -v:     [verbosity] level of FreeFEM output (0 - 1000000)
        -nw:                no graphics
        -wg:                with graphics
        -ne:                no edp script output
        -cd:                change directory to script directory
        -cdtmp:             change directory to /tmp
        -jc:                just compile
        -ns:                same as -ne
        -nowait:            do not wait graphics at the end
        -nc:                without console (MS Windows only)
        -log:               with console (MS Windows only)
        -wait:              wait graphics at the end
        -fglut: [filename]  redirect graphics in file
        -glut:  [command]   use custom glut
        -gff:   [command]   use custom glut (with space quoting)
        -check_plugin [filename]        just try if the plugin is correct
        -?:                 show help
with default ffglut: ffglut

**Comment by prj-** [comment]
I will close this as the user reports that `FreeFem++ LaplaceP1.edp` works. `FreeFem++ -nw` gives the error message it is supposed to: you have to give a script name in the command line.
