### ISSUE TITLE
Interpolation works very slow on a PETSc solution

### ISSUE THREAD

**Issue by mbarzegary** [FreeFem/FreeFem-sources#127]
Dear @prj- 

I learned how to work with the new PETSc interface through the tutorials you provided, and although there are still some mysteries behind the scene (which require reading the source codes of FreeFEM and related inp files to find out the secrets), it's great and works pretty well.

I have an issue now that I think should be related to interpolation. The interpolation of the solution variables is slow on the output of a PETSc computation. I provided an example [Here](https://gist.github.com/mbarzegary/41ec9c58234f82d2ded9ff274900ae2e). 
[The first file ](https://gist.github.com/mbarzegary/41ec9c58234f82d2ded9ff274900ae2e#file-parallel_new_interpolation-edp) is a PETSc-compatible implementation of [the second file](https://gist.github.com/mbarzegary/41ec9c58234f82d2ded9ff274900ae2e#file-parallel_old_interpolation), a distributed-memory parallelization of the Poisson equation. The problem is the difference in the execution speed of lines [34](https://gist.github.com/mbarzegary/41ec9c58234f82d2ded9ff274900ae2e#file-parallel_new_interpolation-edp-L34) (in the PETSc example) and [40](https://gist.github.com/mbarzegary/41ec9c58234f82d2ded9ff274900ae2e#file-parallel_old_interpolation-L40) (in the classic example).
I am using the stable release of FreeFEM v4.4.3 in Ubuntu.

**Comment by prj-** [comment]
If you surround the interpolation steps by `searchMethod = 0` before and `searchMethod = 1` after, you should get decent results (in terms of execution speed). The major difference between the two scripts being that in the second one, you have the full mesh duplicated everywhere, so the operation `x - 0.02, y + 0.02` is "well defined", whereas in the first script, your mesh is fully distributed, thus `x - 0.02, y + 0.02` may be "ill defined", and FreeFEM interpolator is struggling quite a bit (unless you set the appropriate `searchMethod` value).

**Comment by mbarzegary** [comment]
Yes, the issue can be resolved by changing the interpolation method, and it does not affect the results too much. This has been already covered in FreeFEM documentation. I thought it can be addressed in the PETSc interface, in either the documentation or [PETSc-code.hpp](https://github.com/FreeFem/FreeFem-sources/blob/master/plugin/mpi/PETSc-code.hpp) file, and that's why I put it here as an issue. Anyway, my problem is now resolved. Thanks Pierre.

**Comment by prj-** [comment]
This issue is not really related to PETSc, it's just how the FreeFEM interpolator works. You could reproduce the same behavior in a sequential script by just trying to interpolate one solution on a mesh onto another one with some bad elements: without a switch in `searchMethod`, it very well could take ages. Anyway, feel free to close this issue, or post some other questions in here. Just a small tip, you can also greatly improve the performance of your script by adding in the `set(sparams)` the following option: `-pc_type hypre`.

**Comment by mbarzegary** [comment]
Thanks Pierre. You are totally right.
