### ISSUE TITLE
using prebuilt PETSc when building from source?

### ISSUE THREAD

**Issue by boegel** [FreeFem/FreeFem-sources#128]
I'm looking into adding support to [EasyBuild](https://easybuilders.github.io/easybuild/) to install FreeFEM from source.

In EasyBuild, we try to avoid auto-downloading of dependencies during installations, since it leads to reproducibility issues...

We know how to build PETSc from source, so I was wondering if I'm going to run into surprises/problems when I try to get FreeFEM built with a readily built PETSc (using the `--with-petsc` configure option), rather than using the recommended approach using "`cd 3rdparty/ff-petsc; make petsc-slepc`".

Same question goes to other dependencies required by FreeFEM: can I avoid that they get auto-downloaded during the installation process, as long as I provide (compatible versions of) existing installations?

Do any of the FreeFEM dependencies used by FreeFEM need to be patched in order to be compatible with what FreeFEM expects?

**Comment by prj-** [comment]
Yes, of course it is possible. In fact, this is the preferred way of doing things. Please have a look at [this post](https://community.freefem.org/t/compiling-with-your-own-petsc-and-slepc-builds/225), and let me know if you need some more help.

**Comment by boegel** [comment]
@prj- I tried this by passing the location of `petscvariables` to `--with-petsc`, but I'm still getting `with PETSC: no / PETSC complex: no` in the output of `configure`... What am I overlooking?

**Comment by prj-** [comment]
Could you please share your `config.log`?

**Comment by boegel** [comment]
@prj- I think I figured it out... I noticed this in the `configure` output:

```
configure: " Warning PETSC MPI and FF++ MPI not the same: mpiexec != /software/impi/2018.5.288-iccifort-2019.5.281/bin64/mpirun or real != real
```

If I run `configure` after running `export MPIRUN=mpiexec`, then I get `with PETSC: yes`

**Comment by prj-** [comment]
Yes, this is indeed a common issue, and it's what I meant by `if PETSc is not detected, overwrite MPIRUN` in my [tutorial](http://jolivet.perso.enseeiht.fr/FreeFem-tutorial/main.pdf#page=195). You'll also need the HPDDM headers. These can be downloaded either from PETSc (`--download-hpddm`), FreeFEM (`--enable-download`), or directly via a Git clone + `--enable-hpddm --with-hpddm-include="-I/path/to/hpddm/include"` (this is header only so you don't need to compile anything). Let me know if I can be of further assistance.

**Comment by prj-** [comment]
I've updated the develop branch so that you can just download a single package. In this case, if you don't have HPDDM installed with your PETSc package, you can now do `./configure --with-petsc=${PETSC_DIR}/${PETSC_ARCH}/lib/petsc/conf/petscvariables --enable-download_hpddm`. The following packages are used directly in FreeFEM if they are available in the `petscvariables` file:
* ParMETIS
* METIS
* SCOTCH
* MUMPS
* TetGen
* SuperLU
* ScaLAPACK
* SuiteSparse
* SLEPc
* HPDDM
* hypre

By the way, `--enable-download_hpddm` will just clone HPDDM Git repository, it will not build an additional third-party library, so you don't have to worry about incompatibility or reproducibility issues.

**Comment by prj-** [comment]
Last but not least, I’ve also added the new flags `--with-[slepc|slepccomplex]-include` and `--with-[slepc|slepccomplex]-ldflags` in case you build SLEPc outside of PETSc, which I think is the case in EasyBuild. You can now configure with the following `config.param`:
```
'--enable-download_hpddm’
'--with-petsc=${PETSC_DIR}/${PETSC_ARCH}/lib/petsc/conf/petscvariables'
'--with-slepc-include=-I/${SLEPC_DIR}/${PETSC_ARCH}/include -I/${SLEPC_DIR}/include'
'--with-slepc-ldflags=-L/${SLEPC_DIR}/${SLEPC_ARCH}/lib -lslepc'
'--with-petsccomplex=${PETSC_DIR}/${PETSC_ARCH_COMPLEX}/lib/petsc/conf/petscvariables'
'--with-slepccomplex-include=-I/${SLEPC_DIR}/${PETSC_ARCH_COMPLEX}/include -I/${SLEPC_DIR}/include'
'--with-slepccomplex-ldflags=-L/${SLEPC_DIR}/${PETSC_ARCH_COMPLEX}/lib -lslepc'
```
Of course, you can add some more packages. Let me know if you need something else.

**Comment by prj-** [comment]
Are you still looking into that issue or can we close this @boegel?

**Comment by boegel** [comment]
I still need to get back to this, I hope to have time for it soon...

The additional configuration options will be helpful, thanks a lot for those!

Rather than the `--enable-download_hpddm`, I would like to just provide a pointer to a pre-downloaded HPDDM though. That's more useful since it allow building FreeFem on a system where there's no internet access... Would it make sense to add an option for this?

I assume the additional configuration options are already supported in the latest FreeFem 4.6? We strongly prefer to sticking to released versions...

**Comment by prj-** [comment]
Sure, the following should work.
```
'--with-hpddm-include=-I/predownloaded_hpddm_repository/include'
'--enable-hpddm'
```
Indeed, everything is supported in 4.6. If something doesn't work, just let us know.
