### ISSUE TITLE
 Error opening file poisson.edp

### ISSUE THREAD

**Issue by comand2** [FreeFem/FreeFem-sources#131]
I downloaded a code(poisson.edp) and saved it in a foulder(/usr/include/freefem++/idp).
And then I run a command 「FreeFem++ poisson.edp」 on a turminal(Ubuntu18.04).
But it didn't work.
I do not understand why poisson.edp fails.
Could you tell me what I should do to make it work?

**---------------------------------------------------------------------------
XXXX@XXXX:/usr/include/freefem++/idp$FreeFem++ poisson.edp

-- FreeFem++ v4.6 (Thu Apr  2 15:47:38 CEST 2020 - git v4.6)
 Load: lg_fem lg_mesh lg_mesh3 eigenvalue
 Error opening file poisson.edp in:
  -- try  :"poisson.edp"
  -- try  :"/usr/include/freefem++/idp/poisson.edp"
  -- try  :"/usr/local/lib/ff++/4.6/idp/poisson.edp"

 Error line number 1, in file -- unkown --, before  token
lex: Error input opening file
  current line = -1
Compile error : lex: Error input opening file
        line number :1,
terminate called after throwing an instance of 'ErrorCompile'
  what():  Compile error : lex: Error input opening file
        line number :1,
Aborted (core dumped)
---------------------------------------------------------------------------**

**Comment by frederichecht** [comment]
Dear user,

simple the fille 
position.edp is not in your working directory

pwd
ls poisson.edp
when you get file not found.. 

so before do 

cd ThedirectoryPath
ls poisson.edp
poisson.edp

where ThedirectoryPath is the directory path of directory contenting the file poisson.edp
FH.

**Comment by comand2** [comment]
Dear hecht

Thank you for your prompt reply.

I haven't still made it work..

Firest, I saved 「poisson.edp」in a foulder「usr/include/freefem++/idp」 .
Second, I do a command「cd usr/include/freefem++/idp 」 on a terminal.
             (↑I thought that I moved to a correct working directory.)
Finally, I do a command「FreeFem++ poisson.edp」.
But same error was displayed.
-------------------------------------------------------------------------------
*/$ pwd*
/
*/$ cd /usr/include/freefem++/idp*
* /usr/include/freefem++/idp$ pwd*
/usr/include/freefem++/idp
*/usr/include/freefem++/idp$  FreeFem++ poisson.edp*
-- FreeFem++ v4.6 (Thu Apr  2 15:47:38 CEST 2020 - git v4.6)
 Load: lg_fem lg_mesh lg_mesh3 eigenvalue
 Error opening file poisson.edp in:
  -- try  :"poisson.edp"
  -- try  :"/usr/include/freefem++/idp/poisson.edp"
  -- try  :"/usr/local/lib/ff++/4.6/idp/poisson.edp"

 Error line number 1, in file -- unkown --, before  token
lex: Error input opening file
  current line = -1
Compile error : lex: Error input opening file
        line number :1,
terminate called after throwing an instance of 'ErrorCompile'
  what():  Compile error : lex: Error input opening file
        line number :1,
Aborted (core dumped)

-------------------------------------------------------------------------------

Sincerely
command2

2020年4月20日(月) 15:40 hecht <notifications@github.com>:

> Dear user,
>
> simple the fille
> position.edp is not in your working directory
>
> pwd
> ls poisson.edp
> when you get file not found..
>
> so before do
>
> cd ThedirectoryPath
> ls poisson.edp
> poisson.edp
>
> where ThedirectoryPath is the directory path of directory contenting the
> file poisson.edp
> FH.
>

**Comment by frederichecht** [comment]
You do not do the ls command
clearly when you launch FreeFem++ you not un the correct directory

Remark, 

in you mail the RED part is strange; 

1) copie the file in /tmp 
cp poisson.edp  /tmp
cd /tmp
FreeFem++ poisson.edp

Firest, I saved 「poisson.edp」in a foulder「usr/include/freefem++/idp」 .
Second, I do a command「cd usr/include/freefem++/idp 」 on a terminal.
(↑I thought that I moved to a correct working directory.)
Finally, I do a command「FreeFem++ poisson.edp」.
But same error was displayed.
-------------------------------------------------------------------------------
*/$ pwd*
/
*/$ cd /usr/include/freefem++/idp*
* /usr/include/freefem++/idp$ pwd*
/usr/include/freefem++/idp
*/usr/include/freefem++/idp$ FreeFem++ poisson.edp*
-- FreeFem++ v4.6 (Thu Apr 2 15:47:38 CEST 2020 - git v4.6)
Load: lg_fem lg_mesh lg_mesh3 eigenvalue
Error opening file poisson.edp in:
-- try :"poisson.edp"
-- try :"/usr/include/freefem++/idp/poisson.edp"
-- try :"/usr/local/lib/ff++/4.6/idp/poisson.edp"

Error

**Comment by comand2** [comment]
Dear hecht,

Thank you again.

I could make it work.
Thank you very much.

*/usr/include/freefem++/idp$ cp poisson.edp tmp*
cp: cannot open 'poisson.edp' for reading: Permission denied
*/usr/include/freefem++/idp$ ls -al*
drwxrwxrwx 1 root root 512 Apr 17 10:44 .
drwxrwxrwx 1 root root 512 Apr 17 10:42 ..
---------- 1 root root 956 Apr 17 10:44 poisson.edp
*/usr/include/freefem++/idp$ sudo chmod 777 poisson.edp*
*/usr/include/freefem++/idp$ ls -al*
drwxrwxrwx 1 root root 512 Apr 17 10:44 .
drwxrwxrwx 1 root root 512 Apr 17 10:42 ..
-rwxrwxrwx 1 root root 956 Apr 17 10:44 poisson.edp
*/usr/include/freefem++/idp$ cp poisson.edp tmp *

And then, I could make it work!

Yours Sincerely,
command2

2020年4月20日(月) 17:04 hecht <notifications@github.com>:

> You do not do the ls command
> clearly when you launch FreeFem++ you not un the correct directory
>
> Remark,
>
> in you mail the RED part is strange;
>
> 1) copie the file in /tmp
> cp poisson.edp /tmp
> cd /tmp
> FreeFem++ poisson.edp
>
> Firest, I saved 「poisson.edp」in a foulder「usr/include/freefem++/idp」 .
> Second, I do a command「cd usr/include/freefem++/idp 」 on a terminal.
> (↑I thought that I moved to a correct working directory.)
> Finally, I do a command「FreeFem++ poisson.edp」.
> But same error was displayed.
>
> -------------------------------------------------------------------------------
> */$ pwd*
> /
> */$ cd /usr/include/freefem++/idp*
> * /usr/include/freefem++/idp$ pwd*
> /usr/include/freefem++/idp
> */usr/include/freefem++/idp$ FreeFem++ poisson.edp*
> -- FreeFem++ v4.6 (Thu Apr 2 15:47:38 CEST 2020 - git v4.6)
> Load: lg_fem lg_mesh lg_mesh3 eigenvalue
> Error opening file poisson.edp in:
> -- try :"poisson.edp"
> -- try :"/usr/include/freefem++/idp/poisson.edp"
> -- try :"/usr/local/lib/ff++/4.6/idp/poisson.edp"
>
> Error
>
>

**Comment by frederichecht** [comment]
This not de Problem of freefem++ but a Unix problem.
