### ISSUE TITLE
 How to link a parallelization customized code written by PETSc to FreeFem++?

### ISSUE THREAD

**Issue by zcwang6** [FreeFem/FreeFem-sources#137]
Dear FreeFem++ developers,
Thank you for developing such an impressive program. I have been using it for about a year and I am impressed by the powerful plugins of FreeFem.
I am trying to link a parallelization cpp code written by PETSc into FreeFem but I have two issues: 
 The first issue — 
 for sequential cpp code, the steps are 

-  (a) making cpp function 
-  (b) finding a suitable operator for this function 
-  (c) adding this function into FreeFem table by loading the initialize function. 

 I assumed the parallel case should follow the same procedures. However, PETSc needs to call PetscInitialize(&argc, &argv, PETSC_NULL, help) function at the beginning. My understanding is that you did the initialization by creating a different init function in the PETSc_code.hpp(\plugin\mpi). However, I do not know where the pointer “pkarg” comes from.
<img width="768" alt="Screen Shot 2020-05-14 at 9 14 58 AM" src="https://user-images.githubusercontent.com/30075449/81946241-203e2780-95cd-11ea-8d0f-3378484bead4.png">
<img width="948" alt="Screen Shot 2020-05-14 at 9 21 46 AM" src="https://user-images.githubusercontent.com/30075449/81946266-28966280-95cd-11ea-83d0-f2324e99e774.png">
<img width="1186" alt="Screen Shot 2020-05-14 at 9 31 26 AM" src="https://user-images.githubusercontent.com/30075449/81946293-30ee9d80-95cd-11ea-818b-9a5e93cf3e84.png">

The second issue ——
 I assumed the steps of generating the .dylib for FreeFem++ are the general way for other cpp functions. So the steps I used are : 
 

- (a)¯mpicxx -c -g -DNDEBUG -O3 -O3 -O3 -std=c++11 -DBAMG_LONG_LONG -DNCHECKPTR -fPIC -I/usr/local/ff-petsc/real/include ‘-I/usr/local/lib/ff++/4.5/include’ ‘petsc_free_port_1.cpp’ -lpetsc
-  (b)¯mpicxx -bundle -undefined dynamic_lookup -g -DNDEBUG -O3 -O3 -O3 -std=c++11 -DBAMG_LONG_LONG -DNCHECKPTR -fPIC -I/usr/local/ff-petsc/real/include ‘petsc_free_port_1.o’ -o petsc_test_port1.dylib ‘-lpetsc’. 

I was wondering whether the above steps are correct.
Thank you in advance for helping me with these questions.

**Comment by prj-** [comment]
I'll start with the second issue. If at the beginning of your `.cpp` you put the following line:
```
//ff-c++-LIBRARY-dep: cxx11 petsc mpi
```
You'll be able to simply do the following: `ff-c++ -auto petsc_free_port_1.cpp` to properly compile and link your plugin, cf. [this](https://github.com/FreeFem/FreeFem-sources/blob/develop/plugin/mpi/PETSc.cpp#L1) example.

For the first issue, I would not bother with `PetscInitialize` and stuff. In your `.edp`, just do `load "PETSc"`, and it will be taken care of, so you don't have to worry about this in your `.cpp`. You are more than welcome to contribute to [PETSc-code.hpp](https://github.com/FreeFem/FreeFem-sources/blob/develop/plugin/mpi/PETSc-code.hpp) where everything PETSc-related resides. In which case you can just make a pull request and I'll get your stuff merged into FreeFEM.

Let me know if something is not clear to you.

**Comment by prj-** [comment]
You can check the new example I've just pushed on the develop branch: [function-PETSc.edp](https://github.com/FreeFem/FreeFem-sources/commit/fe943e0700f7c78302bb9b3483762a3b4c8157e3#diff-0d6208859a921eb75994bafb8668d6ee), a FreeFEM script loading a user-written plugin, and [function-PETSc.cpp](https://github.com/FreeFem/FreeFem-sources/commit/fe943e0700f7c78302bb9b3483762a3b4c8157e3#diff-a6fe64986db5f073e0f46cb97d588175), a plugin with user-written PETSc code.

**Comment by zcwang6** [comment]
> I'll start with the second issue. If at the beginning of your `.cpp` you put the following line:
> 
> ```
> //ff-c++-LIBRARY-dep: cxx11 petsc mpi
> ```
> 
> You'll be able to simply do the following: `ff-c++ -auto petsc_free_port_1.cpp` to properly compile and link your plugin, cf. [this](https://github.com/FreeFem/FreeFem-sources/blob/develop/plugin/mpi/PETSc.cpp#L1) example.
> 
> For the first issue, I would not bother with `PetscInitialize` and stuff. In your `.edp`, just do `load "PETSc"`, and it will be taken care of, so you don't have to worry about this in your `.cpp`. You are more than welcome to contribute to [PETSc-code.hpp](https://github.com/FreeFem/FreeFem-sources/blob/develop/plugin/mpi/PETSc-code.hpp) where everything PETSc-related resides. In which case you can just make a pull request and I'll get your stuff merged into FreeFEM.
> 
> Let me know if something is not clear to you.

Thanks for your quick reply, I will try your suggestions right now.  Thanks

**Comment by zcwang6** [comment]
> You can check the new example I've just pushed on the develop branch: [function-PETSc.edp](https://github.com/FreeFem/FreeFem-sources/commit/fe943e0700f7c78302bb9b3483762a3b4c8157e3#diff-0d6208859a921eb75994bafb8668d6ee), a FreeFEM script loading a user-written plugin, and [function-PETSc.cpp](https://github.com/FreeFem/FreeFem-sources/commit/fe943e0700f7c78302bb9b3483762a3b4c8157e3#diff-a6fe64986db5f073e0f46cb97d588175), a plugin with user-written PETSc code.

<img width="859" alt="Screen Shot 2020-05-14 at 11 13 45 AM" src="https://user-images.githubusercontent.com/30075449/81952096-0a803080-95d4-11ea-8d20-272c248f4666.png">
The issue I got from ff-c++ -auto petsc_function.cpp is like this. I have GCC 9.3.0_1 instead of 9.3.0, and lgfortran is unavailable on my computer. I usually manually go and change this command. I don't know if there any way to set it appropriately. Thank you

**Comment by prj-** [comment]
Do you compile FreeFEM yourself or use a packaged version? You should be able to fix this by finding and editing one of these files (I can't tell you where they are since it will depend on your installation, my best bet is to look where the `ff-c++` file is): `WHERE_LIBRARY-config` or `WHERE_LIBRARY-download` and remove `-lgfortran`.

**Comment by zcwang6** [comment]
> Do you compile FreeFEM yourself or use a packaged version? You should be able to fix this by finding and editing one of these files (I can't tell you where they are since it will depend on your installation, my best bet is to look where the `ff-c++` file is): `WHERE_LIBRARY-config` or `WHERE_LIBRARY-download` and remove `-lgfortran`.

Thanks

**Comment by zcwang6** [comment]
> Do you compile FreeFEM yourself or use a packaged version? You should be able to fix this by finding and editing one of these files (I can't tell you where they are since it will depend on your installation, my best bet is to look where the `ff-c++` file is): `WHERE_LIBRARY-config` or `WHERE_LIBRARY-download` and remove `-lgfortran`.

I found it out, one more question, why in here, the compiler is cxx, not mpicxx?

**Comment by prj-** [comment]
`mpicxx` is nothing else than a wrapper on top of `cxx`, that includes the MPI headers and links the MPI libraries.
```
$ mpicxx -show
clang++ -Wl,-flat_namespace -Wl,-commons,use_dylibs -I/usr/local/Cellar/mpich/3.3.2/include -L/usr/local/Cellar/mpich/3.3.2/lib -lmpicxx -lmpi -lpmpi
```
So even when you use `mpicxx`, your compiler is in fact `cxx`, with the proper includes and libraries. That's what FreeFEM does. It always uses `cxx`, and if you have a `mpi` dependence in `ff-c++-LIBRARY-dep`, it will add the includes and libraries. See for example the [OpenMPI FAQ](https://www.open-mpi.org/faq/?category=mpi-apps#override-wrappers-after-v1.0) for more details about wrappers, the same applies to MPICH and _all_ other MPI implementations.

**Comment by zcwang6** [comment]
> `mpicxx` is nothing else than a wrapper on top of `cxx`, that includes the MPI headers and links the MPI libraries.
> 
> ```
> $ mpicxx -show
> clang++ -Wl,-flat_namespace -Wl,-commons,use_dylibs -I/usr/local/Cellar/mpich/3.3.2/include -L/usr/local/Cellar/mpich/3.3.2/lib -lmpicxx -lmpi -lpmpi
> ```
> 
> So even when you use `mpicxx`, your compiler is in fact `cxx`, with the proper includes and libraries. That's what FreeFEM does. It always uses `cxx`, and if you have a `mpi` dependence in `ff-c++-LIBRARY-dep`, it will add the includes and libraries. See for example the [OpenMPI FAQ](https://www.open-mpi.org/faq/?category=mpi-apps#override-wrappers-after-v1.0) for more details about wrappers, the same applies to MPICH and _all_ other MPI implementations.

Thanks for this knowledge, I am not really good at the shell script file 
<img width="1287" alt="Screen Shot 2020-05-14 at 11 48 42 AM" src="https://user-images.githubusercontent.com/30075449/81956222-0dc9eb00-95d9-11ea-8b2f-f3c195802ec4.png">
I went into ff-c++ and changed the FFFLIBS from gcc 9.3.0 into 9.3.0_1 and removed the -lgfortran at the end. it seems like it still gives the same error. Thanks

**Comment by prj-** [comment]
I never told you to edit this file. I mentioned `WHERE_LIBRARY-config` and `WHERE_LIBRARY-download`.

**Comment by zcwang6** [comment]
> I never told you to edit this file. I mentioned `WHERE_LIBRARY-config` and `WHERE_LIBRARY-download`.

sorry for that, is that a script as well. sorry for this boring question

**Comment by prj-** [comment]
Please read again my previous [answer](https://github.com/FreeFem/FreeFem-sources/issues/137#issuecomment-628708013).

**Comment by zcwang6** [comment]
> Please read again my previous [answer](https://github.com/FreeFem/FreeFem-sources/issues/137#issuecomment-628708013).
Thank you

**Comment by zcwang6** [comment]
> Please read again my previous [answer](https://github.com/FreeFem/FreeFem-sources/issues/137#issuecomment-628708013).

It solved, thanks for your time, I can run your example now. I will try to read KN<> type data in my petsc cpp code and run it. I will let you know if that works.  I apologized for missing the point of your former message.  Also thanks for the excellent job you did for freefem.   I will close this issue after its working.

**Comment by prj-** [comment]
No problem, I'm glad it's working. Feel free to ask for more help if your code doesn't run appropriately. Otherwise, if you think your code could benefit to others, feel free to create a pull request.

**Comment by zcwang6** [comment]
> No problem, I'm glad it's working. Feel free to ask for more help if your code doesn't run appropriately. Otherwise, if you think your code could benefit to others, feel free to create a pull request.

sure, thanks

**Comment by frederichecht** [comment]
please install gfortran with brew ..

**Comment by prj-** [comment]
No, do not install gfortran if you don't need Fortran...

**Comment by zcwang6** [comment]
> No, do not install gfortran if you don't need Fortran...

Sure

**Comment by zcwang6** [comment]
> No, do not install gfortran if you don't need Fortran...

Hey, could you please tell me what is "in->operator PetscScalar*()" doing here. I think you are passing the address of KN<> into PETSc:: Vec. I also trying to pass an address of Aarm:: vec into PETSc:: Vec in my cpp code. (I pass the address of arma:: vec directly) But I got "candidate function not viable: no known conversion from 'arma::vec' (aka 'Col<double>') to 'const PetscScalar *' (aka 'const double *') for 5th
      argument
PETSC_EXTERN PetscErrorCode VecCreateMPIWithArray(MPI_Comm,PetscInt,PetscInt,PetscInt,const PetscScalar[],Vec*);"
I think you are doing the right thing, but I can not understand here.

<img width="624" alt="picture" src="https://user-images.githubusercontent.com/30075449/82244740-af21ab80-990f-11ea-85d8-bec47a7b319e.png">

**Comment by zcwang6** [comment]
> > No, do not install gfortran if you don't need Fortran...
> 
> Hey, could you please tell me what is "in->operator PetscScalar*()" doing here. I think you are passing the address of KN<> into PETSc:: Vec. I also trying to pass an address of Aarm:: vec into PETSc:: Vec in my cpp code. (I pass the address of arma:: vec directly) But I got "candidate function not viable: no known conversion from 'arma::vec' (aka 'Col') to 'const PetscScalar *' (aka 'const double _') for 5th argument PETSC_EXTERN PetscErrorCode VecCreateMPIWithArray(MPI_Comm,PetscInt,PetscInt,PetscInt,const PetscScalar[],Vec_);"
> I think you are doing the right thing, but I can not understand here.
> 
> <img alt="picture" width="624" src="https://user-images.githubusercontent.com/30075449/82244740-af21ab80-990f-11ea-85d8-bec47a7b319e.png">

I guess you just passed the address of the first element of KN<> into PETSc:: Vec, right? Thank you.

**Comment by prj-** [comment]
You are right. This is not a FreeFEM question, but either a PETSc or Armadillo one. Here is what I get with a quick Google [search](https://stackoverflow.com/a/24023177/1566908).

**Comment by zcwang6** [comment]
> You are right. This is not a FreeFEM question, but either a PETSc or Armadillo one. Here is what I get with a quick Google [search](https://stackoverflow.com/a/24023177/1566908).

Thanks, I can transfer the data between Armadillo and PETSc now. thank you.

**Comment by zcwang6** [comment]
> You are right. This is not a FreeFEM question, but either a PETSc or Armadillo one. Here is what I get with a quick Google [search](https://stackoverflow.com/a/24023177/1566908).

Another question here, when I use ffddm method in FreeFem++, I am wondering that how can I get the correct gradient of my variables by dx(),dy(),dz() functions, for example, calculating the stress tensor from the displacement field (u,v,w). I noticed that if I calculate it on the sub-domain directly, it yields the wrong results. So, I calculated it globally and then bring it back into the local sub-domain by Rih[mpirank] matrix, but this way lost its benefit of parallel computing. Is there any way to calculate the derivative locally in FreeFem++? 

Thank you.

**Comment by prj-** [comment]
This is clearly suboptimal. You can do that using the PETSc interface.
```
Mat A;
createMat(Th, A, Pk)
fespace Vh(Th, Pk);
Vh yourGradient;
exchange(A, yourGradient[], scaled = true);
```
See [this](https://github.com/FreeFem/FreeFem-sources/blob/master/examples/hpddm/diffusion-2d-PETSc.edp#L27) example. There is probably a similar approach with ffddm, but this has nothing to do with the issue at hand, so it would be best to close this and post another issue if you want to use ffddm instead of PETSc.

**Comment by zcwang6** [comment]
> suboptimal

Thanks. I will open another issue about it.
