### ISSUE TITLE
Inconsistency with mesh labels being recognized

### ISSUE THREAD

**Issue by jgonzalez49** [FreeFem/FreeFem-sources#147]
I'm having an issue with the way a cube's labels are being recognized in an example piece of code. In this example code, I group together the boundary conditions 1-6 and it works fine (though it doesn't serve my need to apply a given value to each boundary separately):

[testcubeworking.zip](https://github.com/FreeFem/FreeFem-sources/files/4974841/testcubeworking.zip)

But when I break out the boundary conditions into different lines, one for each face of the cube (this does fit my need), with this code

[testcubenotworking.zip](https://github.com/FreeFem/FreeFem-sources/files/4974843/testcubenotworking.zip)

 it complains with this error:

 Warning: -- Your set of boundary condition is incompatible with the mesh label.
 lab 0  nb 400
 lab 1  nb 200
 lab 2  nb 200
 lab 3  nb 200
 lab 4  nb 200

Can anyone point me to the correct way to break apart the boundary conditions?

**Comment by prj-** [comment]
There is no label 5 and 6, so you get a warning when you do `on(5, ...)`, but not when you do `on(1, 5, ...)` because the label 1 is indeed there.
You can see from the warning, that the labels are only 0, 1, 2, 3, and 4.
```
lab 0 nb 400
lab 1 nb 200
lab 2 nb 200
lab 3 nb 200
lab 4 nb 200
```
If you want to mesh the unit cube with labels 1, 2, 3, 4, 5, and 6, just use `mesh3 Th = cube(nn, nn, nn);`.

**Comment by jgonzalez49** [comment]
That makes sense, I now see from the documentation the default labeling of the cube command. But why does the grouped version of the boundary conditions not throw the same error when it references the nonexistent 5 and 6 labels, even if label 1 is the first mentioned in the sequence?

**Comment by prj-** [comment]
First, this is not an error, but a warning. Second, what warning would you want to get?

**Comment by jgonzalez49** [comment]
I think the same warning I received as when the right and wrong labels are split up would be useful to have when the right and wrong labels are grouped together. It would let me know that the boundary conditions aren't being applied the way I'm thinking they are and prompt me to recheck the actual label situation.

**Comment by prj-** [comment]
If you want to get a warning, then just don't group the labels together?
