### ISSUE TITLE
Possible regression with VTK file output

### ISSUE THREAD

**Issue by jgonzalez49** [FreeFem/FreeFem-sources#148]
I seem to have found a regression in the VTK file output after completing a simulation. Here is a sample script that will output a VTK file:

[cubeflowtest.zip](https://github.com/FreeFem/FreeFem-sources/files/4974876/cubeflowtest.zip)

I have traced the last version that worked for me back to version 4.4.2: [https://github.com/FreeFem/FreeFem-sources/releases/tag/v4.4.2](url)

When using older versions, I am able to open the VTK in Paraview and see the geometry and data correctly rendered. However, when using versions newer than 4.4.2, Paraview cannot recognize the geometry, and in at least one intermediate version it will not even recognize there is data (the most recent version, 4.6, seems to only produce a VTK where the geometry is not understood). Here is a zip file of resulting VTKs for different versions, and are labeled with the FreeFEM version used to make them as well as whether it was working for me in Paraview:

[vtkfiles.zip](https://github.com/FreeFem/FreeFem-sources/files/4974884/vtkfiles.zip)

**Comment by prj-** [comment]
Use the `.vtu` format, not `.vtk`. Does this fix your issue?

**Comment by jgonzalez49** [comment]
I am able to confirm that using my script with the `.vtu` format does produce a file that works with Paraview, thank you for the information.
