### ISSUE TITLE
Suspicion de dysfonctionnement de IOVTK en 3D

### ISSUE THREAD

**Issue by maesg62** [FreeFem/FreeFem-sources#150]
Chers développeurs FreeFem,

J'utilise actuellement la version 4.6 de FreeFem++.
En post traitant les résultats au format VTK avec le logiciel VisIt 3.1.2 (une alternative à Paraview), je n'arrive pas à visualiser correctement un maillage volumique en 3D, alors que cela fonctionnait bien par le passé avec des versions plus anciennes de FreeFem++.
J'ai mis dans le .zip ci-dessous le morceau de code qui me sert de test, ainsi que le résultat d'affichage produit dans VisIt.

[testIOvtk3D.zip](https://github.com/FreeFem/FreeFem-sources/files/5040236/testIOvtk3D.zip)

Pouvez-vous vérifier qu'il s'agit bien d'un dysfonctionnement de la part de IOVTK, et éventuellement apporter une solution ?

En vous remerciant par avance, bien cordialement,
maesg62

**Comment by prj-** [comment]
This has been discussed many times already, e.g., https://github.com/FreeFem/FreeFem-sources/issues/148. The fix is always to use the `.vtu` format, not `.vtk`.

**Comment by maesg62** [comment]
Many thanks for your prompt response.
I confirm, effectively VTU format works very fine with VisIt too.
Have a good week-end, best regards,
maesg62
