### ISSUE TITLE
Making PETSc fails on linux on SUPERLU step

### ISSUE THREAD

**Issue by Jdogzz** [FreeFem/FreeFem-sources#151]
Hi, I've been attempting to compile the current git copy of the FreeFEM develop branch on my linux system. Following every step from the build instructions, including the prefix option to work in my home directory, I am able to complete everything successfully before the `make petsc-slepc` step. During that step, it will fail with the message:

```
         UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
-------------------------------------------------------------------------------
Error configuring SUPERLU with cmake
*******************************************************************************

make: *** [petsc-3.13.4/tag-conf-real] Error 1
```

Here is the configure log from the FreeFem-sources-develop/3rdparty/ff-petsc/petsc-3.13.4 directory: 
[configure.log](https://github.com/FreeFem/FreeFem-sources/files/5044507/configure.log)

While I do see some other lines toward the end where it shows the command it could not execute, the two particularly suspect problems appear to be these sections:

```
CMake Error at /usr/share/cmake/Modules/WriteBasicConfigVersionFile.cmake:39 (message):
  No VERSION specified for WRITE_BASIC_CONFIG_VERSION_FILE()
```

```
File "/home/jgonzalez49/freefem/FreeFem-sources-develop/3rdparty/ff-petsc/petsc-3.13.4/config/BuildSystem/config/package.py", line 1739, in Install
    raise RuntimeError('Error configuring '+self.PACKAGE+' with cmake')
```

That log further points to this log in the FreeFem-sources-develop/3rdparty/ff-petsc/petsc-3.13.4/fr/externalpackages/git.superlu/petsc-build/CMakeFiles directory:
[CMakeOutput.log](https://github.com/FreeFem/FreeFem-sources/files/5044512/CMakeOutput.log)

Within that log I do not seem to see anything that stands out as an explicit error.

Does anyone have a suggestion as to how I might correct this build failure?

**Comment by prj-** [comment]
It looks like you are using a very old Linux system. Most likely, your CMake version is not supported by SuperLU.
I'd just remove all the `--download-superlu` stuff from [ff-petsc/Makefile](https://github.com/FreeFem/FreeFem-sources/blob/develop/3rdparty/ff-petsc/Makefile) and relaunch `make petsc-slepc`.

**Comment by Jdogzz** [comment]
That seems to have worked, thank you. I noticed a couple of other errors when completing the process. Here is the portion of the output from the errors to the end:

```
PASS: Lap3dEigenValue.edp
../../bin/test-driver-ff: line 126: 51953 Segmentation fault      (core dumped)                                                                              ${TEST_FFPP} ${FLAGS_FFPP_B} "$@" ${FLAGS_FFPP_A} > $log_file 2>&1
FAIL: LapComplexEigenValue.edp
PASS: LapEigenValue.edp
PASS: LapEigenValueFunc.edp
PASS: LapEigenValueFuncV2.edp
../../bin/test-driver-ff: line 126: 52009 Killed                  ${TEST_FFPP} $                                                                             {FLAGS_FFPP_B} "$@" ${FLAGS_FFPP_A} > $log_file 2>&1
FAIL: LapnosymComplexEigenValue.edp
PASS: LapnosymEigenValue.edp
PASS: neuman.edp
PASS: Stokes-eigen.edp
PASS: VP-Steklov-Poincare.edp
PASS: WGM-sphere.edp
PASS: LapEigenBeltrami.edp
make[5]: Entering directory `/home/jgonzalez49/freefem/FreeFem-sources-develop/e                                                                             xamples/eigen'
make[5]: Nothing to be done for `all'.
make[5]: Leaving directory `/home/jgonzalez49/freefem/FreeFem-sources-develop/ex                                                                             amples/eigen'
============================================================================
Testsuite summary for FreeFEM 4.6
============================================================================
# TOTAL: 16
# PASS:  14
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0
============================================================================
See examples/eigen/test-suite.log
Please report to frederic.hecht@sorbonne-universite.fr
============================================================================
make[4]: *** [test-suite.log] Error 1
make[4]: Leaving directory `/home/jgonzalez49/freefem/FreeFem-sources-develop/ex                                                                             amples/eigen'
make[3]: *** [check-TESTS] Error 2
make[3]: Leaving directory `/home/jgonzalez49/freefem/FreeFem-sources-develop/ex                                                                             amples/eigen'
make[2]: *** [check-am] Error 2
make[2]: Leaving directory `/home/jgonzalez49/freefem/FreeFem-sources-develop/ex                                                                             amples/eigen'
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory `/home/jgonzalez49/freefem/FreeFem-sources-develop/ex                                                                             amples'
make: *** [check-recursive] Error 1
```

Here is the log mentioned in the output:
[test-suite.log](https://github.com/FreeFem/FreeFem-sources/files/5059494/test-suite.log)

I'm not sure if this is related to the missing SuperLU compilation, the dependencies in those two failed tests don't seem to mention it.

**Comment by prj-** [comment]
Those are errors related to ARPACK. I'd advise you not to use ARPACK, and instead SLEPc (which can call ARPACK internally).
Feel free to close this issue, unless you need to figure out something else.
