### ISSUE TITLE
Sphere function fails when origin is specified.

### ISSUE THREAD

**Issue by MPenaR** [FreeFem/FreeFem-sources#159]
I tried the example of the cubic mesh with the spherical one inside and worked fine:

```
load "msh3"
load "TetGen"
load "medit"
include "MeshSurface.idp"

// Parameters
real hs = 0.1; //mesh size on sphere
int[int] N = [20, 20, 20];
real [int,int] B = [[-1, 1], [-1, 1], [-1, 1]];
int [int,int] L = [[1, 2], [3, 4], [5, 6]];

// Meshes
meshS ThH = SurfaceHex(N, B, L, 1);
meshS ThS = Sphere(0.5, hs, 7, 1);

meshS ThHS = ThH + ThS;
medit("Hex-Sphere", ThHS);

real voltet = (hs^3)/6.;
cout << "voltet = " << voltet << endl;
real[int] domain = [0, 0, 0, 1, voltet, 0, 0, 0.7, 2, voltet];
mesh3 Th = tetg(ThHS, switch="pqaAAYYQ", nbofregions=2, regionlist=domain);
medit("Cube with ball", Th);
```

however if I specify the origin of the spherical mesh changing the line:
`meshS ThS = Sphere(0.5, hs, 7, 1);`
for 
`meshS ThS = Sphere(0.5, 0., 0., 0., hs, 7, 1);`
I get the next error message:

```
   15 : meshS ThS = Sphere(0.5, 0., 0., 0.,  hs, 7, 1) error operator (  <d>, <d>, <d>, <d>, <Pd>, <l>, <l> 
 List of choices 
	 (	  <N5Fem2D5MeshSE> :   <d>, <d>, <l>, <l> )

 Error line number 15, in file cube_sphere.edp, before  token )
```

I tried by passing them as an array, that is, passing
`meshS ThS = Sphere(0.5, [0., 0., 0.], hs, 7, 1);`
 but I also get an error with message:
```
 15 : meshS ThS = Sphere(0.5,[ 0., 0., 0.],  hs, 7, 1) error operator (  <d>, <7E_Array>, <Pd>, <l>, <l> 
 List of choices 
	 (	  <N5Fem2D5MeshSE> :   <d>, <d>, <l>, <l> )

 Error line number 15, in file cube_sphere.edp, before  token )

  current line = 15
```

Is it possible to change the origin of the sphere, right? I'm using version 4.4.2

EDIT: I've tryed cheating by using the `Ellipsoide` function and got similar results, everything works fine until I specify the origin.

**Comment by prj-** [comment]
You should probably try to update your FreeFEM version.
You can also try:
```
ThS = movemeshS(ThS,transfo=[x+Ox,y+Oy,z+Oz]);
```

**Comment by AFourmont** [comment]
To complete Pierre, [this commit](https://github.com/FreeFem/FreeFem-sources/commit/eaa3f0da74609b4c4e207225396218315dbc2467) fixes a bug in argument declaration

The function is Sphere(real R,real h,int L,real Ox,real Oy,real Oz,int orientation) with (Ox,Oy,Oz) the sphere center

**Comment by MPenaR** [comment]
Sorry I don't understand. 
Should I update my FreeFem++ and change the order of the arguments like in your answer or you are telling me that either I update Freefem++ or a change the ordenr of my argments?

**Comment by AFourmont** [comment]
2 solutions:

- you should update your FreeFEM with the develop current branch and use this declaration
 `Sphere(real R,real h,int L,real Ox,real Oy,real Oz,int orientation)`

-  or with your current installation and
`meshS ThS=Sphere(real R,real h,int L,int orientation);
ThS=movemesh(ThS,[x+Ox,y+Oy,z+Oz]);`
