### ISSUE TITLE
error during compiling WIN10 + SYS2 +MINGW64

### ISSUE THREAD

**Issue by spara7C5** [FreeFem/FreeFem-sources#163]
cloning the branch "develop", running makefile -j2 i get:

ranlib ../../../libopenblasp-r0.3.6.a
make[8]: Leaving directory '/home/Brain ADM/Devel/FreeFem-sources/3rdparty/blas/OpenBLAS/lapack-netlib/LAPACKE/utils'
make[7]: Leaving directory '/home/Brain ADM/Devel/FreeFem-sources/3rdparty/blas/OpenBLAS/lapack-netlib/LAPACKE'
make[6]: Leaving directory '/home/Brain ADM/Devel/FreeFem-sources/3rdparty/blas/OpenBLAS/lapack-netlib'
make[5]: Leaving directory '/home/Brain ADM/Devel/FreeFem-sources/3rdparty/blas/OpenBLAS'
touch openblas.done
cd OpenBLAS && ../../../build/links2files
/bin/sh: line 1: ../../../build/links2files: No such file or directory
make[4]: *** [Makefile:859: links.done] Error 127
make[4]: Leaving directory '/home/Brain ADM/Devel/FreeFem-sources/3rdparty/blas'
make[3]: *** [Makefile:573: all] Error 2
make[3]: Leaving directory '/home/Brain ADM/Devel/FreeFem-sources/3rdparty/blas'
make[2]: *** [Makefile:593: all-recursive] Error 1
make[2]: Leaving directory '/home/Brain ADM/Devel/FreeFem-sources/3rdparty'
make[1]: *** [Makefile:797: all-recursive] Error 1
make[1]: Leaving directory '/home/Brain ADM/Devel/FreeFem-sources'
make: *** [Makefile:747: all] Error 2

**Comment by prj-** [comment]
I'd suggest you compile PETSc which will provide a BLAS implementation so that OpenBLAS won't be compiled. You can type `make petsc-slepc` in the `3rdparty/ff-petsc` folder.

**Comment by spara7C5** [comment]
the make petsc-slepc fails:

===============================================================================
             Configuring PETSc to compile on your system
===============================================================================
TESTING: check from config.libraries(config/BuildSystem/config/libraries.py:157)                                                                                                   *******************************************************************************
         UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
-------------------------------------------------------------------------------
--with-mpi-lib=[''] and
--with-mpi-include=[] did not work
*******************************************************************************

make: *** [Makefile:220: petsc-3.14.2/tag-conf-real] Error 1

**Comment by spara7C5** [comment]
the config. log file:

## ---------------------- ##
## Running config.status. ##
## ---------------------- ##

This file was extended by FreeFEM config.status 4.7-1, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  CONFIG_FILES    = 
  CONFIG_HEADERS  = 
  CONFIG_LINKS    = 
  CONFIG_COMMANDS = 
  $ ../../config.status --file=Makefile.inc:Makefile-PETSc.inc

on DESKTOP-QJQ3LRV

config.status:1209: creating Makefile.inc

**Comment by prj-** [comment]
Do you have [MS-MPI](https://docs.microsoft.com/en-us/message-passing-interface/microsoft-mpi) installed?

**Comment by spara7C5** [comment]
Yes, i installed it via the installar msmpisetup.exe, are any configurations required? I still get the same error...

**Comment by prj-** [comment]
Could you please send `FreeFem-sources/config.log`?

**Comment by spara7C5** [comment]
it is exactly equal to the one above

**Comment by prj-** [comment]
No, you copy/paste'd `FreeFem-sources/3rdparty/ff-petsc/config.log`...

**Comment by spara7C5** [comment]
sorry for that.
I attach FreeFem-sources/config.log
[config.log](https://github.com/FreeFem/FreeFem-sources/files/5763812/config.log)

**Comment by prj-** [comment]
Where did you install MS-MPI? There is not a single reference in your `config.log`.

**Comment by spara7C5** [comment]
i re-cloned the repo and retried the compile sequence. I still get error in make petsc-slepc.
The config.log file even shows the MS-MPI:
[config.log](https://github.com/FreeFem/FreeFem-sources/files/5789942/config.log)
but i still get:


===============================================================================
             Configuring PETSc to compile on your system
===============================================================================
TESTING: check from config.libraries(config/BuildSystem/config/libraries.py:157)                                                                                                   *******************************************************************************
         UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
-------------------------------------------------------------------------------
--with-mpi-lib=[''] and
--with-mpi-include=[] did not work
*******************************************************************************

make: *** [Makefile:220: petsc-3.14.2/tag-conf-real] Error 1

**Comment by prj-** [comment]
No, the `config.log` does not show a functioning MPI, see at the end: `configure:25676:   --  with MPI:     no`.
Do you have any files in `3rdparty/include/msmpi`? If not, could you try to go into `3rdparty` and type `make reinstall-msmpi` and then reconfigure and make sure you have `--  with MPI:     yes`? You also probably want to add the flag `FCFLAGS=-fallow-invalid-boz` on your configure line.
