### ISSUE TITLE
Matrix-vector product operations with transpose operator give unexpected results

### ISSUE THREAD

**Issue by 1995hnagamin** [FreeFem/FreeFem-sources#164]
I am using FreeFem++ v4.700001 (Sat, Oct 17, 2020 3:31:48 PM - git v4.7-1) for Windows 10.
After executing the following code, `w1` is equal to `[-1i, -2i, -3i]`, as expected, whereas `w2` is equal to `[1i, 2i, 3i]`.
I think they should be the same. Is this behavior expected, or a bug?
Thank you.

```
matrix<complex> A =
    [[0+1i, 0, 0],
     [0, 0+1i, 0],
     [0, 0, 0+1i]];
matrix<complex> B = A';

complex[int] v = [1+0i, 2, 3];
complex[int] w1 = B * v;
complex[int] w2 = A' * v;
```

**Comment by frederichecht** [comment]
You are right, I will correct soon as possible

**Comment by prj-** [comment]
@frederichecht, this should do it.
```
diff --git a/src/femlib/HashMatrix.cpp b/src/femlib/HashMatrix.cpp
index f0c61d79..c7dc1f3c 100644
--- a/src/femlib/HashMatrix.cpp
+++ b/src/femlib/HashMatrix.cpp
@@ -1078,7 +1078,7 @@ typename HashMatrix<I,R>::Pair HashMatrix<I,R>::RoworCol(I ii,bool row)


 template<class I,class R>
-R* HashMatrix<I,R>::addMatMul(R *x,R*Ax,bool Transpose,I sx,I sAx) const {
+R* HashMatrix<I,R>::addMatMul(R *x,R*Ax,const bool Transpose,I sx,I sAx) const {
     I *ii=i,*jj=j;
     R *aa=aij;
     double t0= CPUsecond();
@@ -1091,22 +1091,22 @@ R* HashMatrix<I,R>::addMatMul(R *x,R*Ax,bool Transpose,I sx,I sAx) const {
             for(int k=0; k<nnz;++k)
             {
                 Ax[ii[k]] += aa[k]*x[jj[k]];
-                if( ii[k] != jj[k]) Ax[jj[k]] += (half == 1?conj(aa[k]):aa[k]) *x[ii[k]];
+                if( ii[k] != jj[k]) Ax[jj[k]] += (Transpose?conj(aa[k]):aa[k]) *x[ii[k]];
             }
         else
             for(int k=0; k<nnz;++k)
-                Ax[ii[k]] += aa[k]*x[jj[k]];
+                Ax[ii[k]] += (Transpose?conj(aa[k]):aa[k])*x[jj[k]];
     }
     else
     if( half)
         for(int k=0; k<nnz;++k)
         {
             Ax[ii[k]*sAx] += aa[k]*x[jj[k]*sx];
-            if( ii[k] != jj[k]) Ax[jj[k]*sAx] += (half == 1?conj(aa[k]):aa[k])*x[ii[k]*sx];
+            if( ii[k] != jj[k]) Ax[jj[k]*sAx] += (Transpose?conj(aa[k]):aa[k])*x[ii[k]*sx];
         }
     else
         for(int k=0; k<nnz;++k)
-            Ax[ii[k]*sAx] += aa[k]*x[jj[k]*sx];
+            Ax[ii[k]*sAx] += (Transpose?conj(aa[k]):aa[k])*x[jj[k]*sx];
     matmulcpu+=  CPUsecond()-t0;
     return Ax;}
```
I now correctly get the following.
```
3
	(0,-1)	(0,-2)	(0,-3)
3
	(0,-1)	(0,-2)	(0,-3)
```

**Comment by frederichecht** [comment]
Dear all,

The correction is 



in the commit: 
commit aa2dbe5042e6bef301efcfaebdd7bde2691200bf (HEAD -> develop)




Best Regards, 

Frédéric Hecht.   

-----------------------------------------------------------------------------------------------------------------------------------
Laboratoire  Jacques-Louis Lions,                UPMC Sorbonne Université
BC187,  4 Place  Jussieu,     75252  PARIS cedex 05,               France
Campus Jussieu,       Barre 15-25,           3 etage           Bureau 307 
Projet Alpines ,   Inria de Paris, 2 rue Simone Iff Voie DQ12 75012 Paris
tel:  +33 1 44274411,        mob: +33 6 62198986,     fax: +33 1 44277200
frederic.hecht@sorbonne-universite.fr https://www.ljll.math.upmc.fr/hecht
software:  FreeFem++          web site:       http://www.freefem.org/ff++



> Le 3 janv. 2021 à 09:52, Frédéric Hecht <frederic.hecht@sorbonne-universite.fr> a écrit :
> 
> You are right, I will correct soon as possible 
> 
>> Le 3 janv. 2021 à 07:59, NAGAMINE Hideaki <notifications@github.com <mailto:notifications@github.com>> a écrit :
>> 
>> matrix<complex> A =
>>     [[0+1i, 0, 0],
>>      [0, 0+1i, 0],
>>      [0, 0, 0+1i]];
>> matrix<complex> B = A';
>> 
>> complex[int] v = [1+0i, 2, 3];
>> complex[int] w1 = B * v;
>> complex[int] w2 = A' * v;
>> 
> 


diff --git a/src/femlib/HashMatrix.cpp b/src/femlib/HashMatrix.cpp
index f0c61d79..773e8e44 100644
--- a/src/femlib/HashMatrix.cpp
+++ b/src/femlib/HashMatrix.cpp
@@ -1083,30 +1083,65 @@ R* HashMatrix<I,R>::addMatMul(R *x,R*Ax,bool Transpose,I sx,I sAx) const {
     R *aa=aij;
     double t0= CPUsecond();
     //   if(Transpose != trans) {std::swap(ii,jj);}
+    const bool do_conj  = ((std::is_same<R,complex<double> >::value || std::is_same<R,complex<float> >::value )) && Transpose;
     if(Transpose ) {std::swap(ii,jj);}
     if(fortran) {aa++;}
+    if(do_conj)// complex and transpose => hermitian
+    {
     if(sx==1 && sAx==1)
     {
         if( half)
-            for(int k=0; k<nnz;++k)
+            for(size_t k=0; k<nnz;++k)
             {
+                R aak=aa[k],caak=conj(aa[k]);
+                Ax[ii[k]] += caak*x[jj[k]];
+                if( ii[k] != jj[k])
+                    Ax[jj[k]] += caak*x[ii[k]];
+            }
+        else
+            for(size_t k=0; k<nnz;++k)
+                Ax[ii[k]] += conj(aa[k])*x[jj[k]];
+    }
+    else
+    if( half)
+        for(size_t k=0; k<nnz;++k)
+        {
+            R aak=aa[k],caak=conj(aa[k]);
+            Ax[ii[k]*sAx] += caak*x[jj[k]*sx];
+            if( ii[k] != jj[k])
+                Ax[jj[k]*sAx] += aak*x[ii[k]*sx];
+        }
+    else
+        for(size_t k=0; k<nnz;++k)
+            Ax[ii[k]*sAx] += conj(aa[k])*x[jj[k]*sx];
+    }
+    else // no transp or no complex =>  (no conj)
+    {
+    if(sx==1 && sAx==1)
+    {
+        if( half)
+            for(size_t k=0; k<nnz;++k)
+            {    
                 Ax[ii[k]] += aa[k]*x[jj[k]];
-                if( ii[k] != jj[k]) Ax[jj[k]] += (half == 1?conj(aa[k]):aa[k]) *x[ii[k]];
+                if( ii[k] != jj[k])
+                    Ax[jj[k]] += aa[k] *x[ii[k]];
             }
         else
-            for(int k=0; k<nnz;++k)
+            for(size_t k=0; k<nnz;++k)
                 Ax[ii[k]] += aa[k]*x[jj[k]];
     }
     else
     if( half)
-        for(int k=0; k<nnz;++k)
+        for(size_t k=0; k<nnz;++k)
         {
             Ax[ii[k]*sAx] += aa[k]*x[jj[k]*sx];
-            if( ii[k] != jj[k]) Ax[jj[k]*sAx] += (half == 1?conj(aa[k]):aa[k])*x[ii[k]*sx];
+            if( ii[k] != jj[k])
+                Ax[jj[k]*sAx] += aa[k]*x[ii[k]*sx];
         }
     else
-        for(int k=0; k<nnz;++k)
+        for(size_t k=0; k<nnz;++k)
             Ax[ii[k]*sAx] += aa[k]*x[jj[k]*sx];
+    }
     matmulcpu+=  CPUsecond()-t0;
     return Ax;}

**Comment by 1995hnagamin** [comment]
Thank you!
