### ISSUE TITLE
Sum of three (or more) real[int] vectors

### ISSUE THREAD

**Issue by jaghili** [FreeFem/FreeFem-sources#167]
Dear developpers,

I noticed that summing three (or more) `real[int]` vectors leads to an error. The following piece of code :+1: 

`
real[int] X(10);
real[int] Z = X + X + X;
`
leads to : 
`-- FreeFem++ v4.700001 (mar. 24 nov. 2020 16:39:39 CET - git no git)
 Load: lg_fem lg_mesh lg_mesh3 eigenvalue 
 error operator +  <7Add_KN_IdE>, <P2KNIdE> 
 List of choices 
	 (	  <l> :   <l>, <l> )
	 (	  <8listMesh> :   <8listMesh>, <N5Fem2D4MeshE> )
	 (	  <8listMesh> :   <N5Fem2D4MeshE>, <N5Fem2D4MeshE> )
(...)`

It is also the case with the [FreeFem live ](https://freefem.org/tryit) version (running v3.5). 

Is there any way allow the sum of 3+ such vectors or am I missing something ?

Thank you in advance.

**Comment by prj-** [comment]
No, you are correct. Up to now, you need to do `Z = X + Y; Z += W`.

**Comment by jaghili** [comment]
> No, you are correct. Up to now, you need to do `Z = X + Y; Z += W`. If this is a critical operation for you, it would be quite easy to write a small plugin that would do this efficiently.

Thanks for the return and the confirmation. I spotted this bug few years ago and I always circumvented it easily so far. However this leads to rather unelegant code when one has to repeat this several times. I imagine there are non-trivial copy issues behind this operation but i hope it will be fixed some day.

**Comment by prj-** [comment]
Again, you can just write a small plugin to do this if that operation is critical to you.

**Comment by jaghili** [comment]
> Again, you can just write a small plugin to do this if that operation is critical to you.

I'll keep that in mind. Thanks again.
