### ISSUE TITLE
Eigen value problem with fieldsplit

### ISSUE THREAD

**Issue by Pmollo** [FreeFem/FreeFem-sources#169]
Hi,
I think there is a mistake in the [example to compute Stokes inf-sup constant](https://github.com/FreeFem/FreeFem-sources/blob/develop/examples/hpddm/stokes-2d-SLEPc.edp), because boundary conditions are set on different border in right and left hand side. 
In addition, is it possible to compute inf-sup constant directly with a [P2,P2,P1] FE space with SLEPc ? I try but I can't find the same results, I attach my attempt.
Thanks  

[example for Stokes inf-sup constant]:(https://github.com/FreeFem/FreeFem-sources/blob/develop/examples/hpddm/stokes-2d-SLEPc.edp)

[P2P2P1infsup.edp.txt](https://github.com/FreeFem/FreeFem-sources/files/6265601/P2P2P1infsup.edp.txt)
[Compare.edp.txt](https://github.com/FreeFem/FreeFem-sources/files/6265602/Compare.edp.txt)

**Comment by prj-** [comment]
You are not using a [P2, P2, P1] space in your file `Compare.edp.txt`, are you sure you uploaded the correct file? It is of course possible, and in fact much simpler, since everything is written in a monolithic fashion.

**Comment by Pmollo** [comment]
My attempt is in the file `P2P2P1infsup.edp`, the `compare.edp` file is just for you to see the expected eigen value. Both of them run the same example, but they return different results.

**Comment by prj-** [comment]
My bad, I didn't look at the correct file... I'll have a look, thanks.

**Comment by prj-** [comment]
One problem is that you do not use the proper prefix name in your script. Switch from `0_` and `1_` to `velocity_` and `pressure_` when you set the parameters. Since the ordering of unknowns is not the same when you use a block matrix or a monolithic formulation, I'm not sure we can expect exactly the same results for this problem which is rather ill-posed.

**Comment by Pmollo** [comment]
You're right, but I try to change this and it leads me to PETSc errors that I don't understand. I though that the difference between these two programs was just the ordering, maybe I misunderstood something about fieldsplit. 
Anyway, thanks for your help.

**Comment by prj-** [comment]
Well, it should be just the ordering. But I'm not sure why it's not. Again, probably due to the near indefiniteness, ordering plays an important role?

**Comment by Pmollo** [comment]
I usually save my Stokes problems in FreeFem matrices with [P2,P2,P1] formulation and I can easily manage the ordering using this kind of commands : 
`int[int] I = [ 1,0];`
`int[int] J = [0,1];`
`B = A(I,J);`
If it exists a similar way to manage ordering of PETSc matrices, it can be useful to perform manual reordering before computing the eigen problem ? 
And yes, it blocks me a little bit, because as I said all my problems are formulated in this monolithic formulation.
Thank you for your help.

**Comment by prj-** [comment]
But are you having wrong results in your problems with a monolithic formulation?

**Comment by Pmollo** [comment]
I attach an example where results for these two methods are really different,  I don't know which is wrong ?
And as you said, I define prefix that I don't use, but when I try to use them, the program doesn't run anymore.

[example2_monolithic.edp.txt](https://github.com/FreeFem/FreeFem-sources/files/6277887/example2_monolithic.edp.txt)
[example2_separate.edp.txt](https://github.com/FreeFem/FreeFem-sources/files/6277889/example2_separate.edp.txt)

Thanks for your help

**Comment by prj-** [comment]
But this is not your application, is it? Can you reproduce a similar behavior on your actual code?

**Comment by prj-** [comment]
OK, here are some more details. If in your monolithic solver you switch to `-st_pc_type lu` and in your fieldsplit version, you change:
```
    varf onGamma([u, uB], [v, vB]) = on(1, 2, 3, 4, u=0, uB=0);
```
to
```
    varf onGamma([u, uB], [v, vB]) = on(1, 2, 3, 4, u=1, uB=1);
```
You'll get roughly an equivalent leading eigenvalue.
```
 ---------------------- --------------------
            k             ||Ax-kBx||/||kx||
 ---------------------- --------------------
        0.132597              0.0498349
 ---------------------- --------------------
```
vs.
```
 ---------------------- --------------------
            k             ||Ax-kBx||/||kx||
 ---------------------- --------------------
        0.133182            4.07354e-09
 ---------------------- --------------------
```

**Comment by Pmollo** [comment]
I deal with multiple similar examples and I can never match these two computation methods. 
In what you did, I don't understand why you set 1 on BC ?
And if I set `-st_pc_type lu` instead of `-st_pc_type fieldsplit`, does EPSsolve still use `fields=list` ?

**Comment by prj-** [comment]
The `varf` is not to specify boundary conditions, it is just to define markers for `MatZeroRows` to set the corresponding rows to zero. If you put 0, then no rows are set to zero, and the boundary conditions are not correct.
No, with this `-pc_type`, the `fields` parameter is not needed anymore.

**Comment by Pmollo** [comment]
In addition, when I change `-st_fieldsplit_0_pc_type hypre` in `-st_fieldsplit_0_pc_type lu, I get results even closer and this enhance the fieldsplit convergence.
Again, thanks for your help and explanations.
