### ISSUE TITLE
Bug with the name of a key of string[string] object inside macro

### ISSUE THREAD

**Issue by abaikin** [FreeFem/FreeFem-sources#171]
If I create an array, pass it to macro and try to create an element of string[string] object with the key equal to array var name ( for example, "**array**"), then I get the following error

s1[array] error operator   <5MyMapI6StringS0_E>, <P2KNIdE> 
 List of choices 
         (        <PPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE> :   <5MyMapI6StringS0_E>, <NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE> )

If I pass not array but simple type like real, it works well.

FreeFem++ is version 4.8, gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04).  The code is

`
real[int] array;
macro macr(array){

	string[string] s1;
	s1["array"] = "sds";
}

//EOM
macr(array);

`

**Comment by prj-** [comment]
What are you trying to do? If you change your macro definition to something like
```
macro macr(arrayParameterName){
```
It does work OK.

**Comment by abaikin** [comment]
Yes, it does work. But it is very weird that the naming of the variable (arrays only) influences the keys naming for string[string] map. Is it possible to fix it in FF?

**Comment by frederichecht** [comment]
Dear Abaikin,

I really do not understand what you want exactly. 
Can you explain with example?
Best,
F. Hecht

**Comment by abaikin** [comment]
Dear  Dr. Hecht,

I have an input h5-file. I create the string[string] simInputDatasetsNames to store the names of the datasets paths.

For example,
simInputDatasetsNames["volumeRate"] = "SCHEDULE/VOLUME_RATE_TABLE/VOLUME_RATE";

In my code I create variable real[int] volumeRate

For convenience, the name of the key "volumeRate" is the same as the name of the variable volumeRate.
And I create a macro where I read all the parameters from h5-file to the freefem variables (I write my own h5-reader).

The simplified code is

```
real[int] volumeRate;
macro readSimInputHDF5(volumeRate){
string[string] simInputDatasetsNames;
simInputDatasetsNames["volumeRate"] = "SCHEDULE/VOLUME_RATE_TABLE/VOLUME_RATE";

// My user-defined type and function    
hdf5Reader reader1;
ReadRealArray1DHDF5Dataset(reader1, simInputDatasetsNames["volumeRate"], volumeRate);
} // EOM

// call
readSimInputHDF5(volumeRate)
```
The problem is that volumeRate variable name in ff language is in conflict with the string "volumeRate" unexpectedly. 

It works, if I take not array type. The real, for example,

`real volumeRate;`

Why it does not work for arrays?

**Comment by frederichecht** [comment]
Dear abaikin,

you can use Stringification(a)  to wrap a nam in string. 
I think this you can solve your problem 


Best F. Hecht.

**Comment by abaikin** [comment]
Dear Dr. Hecht,
Thank you, yes it solves my particular problem.

I tried the more general workaround and it works

ReadRealArray1DHDF5Dataset(reader1, simInputDatasetsNames[Stringification("volumeRate")], volumeRate);

**Comment by frederichecht** [comment]
you do not need " in Stringification

ReadRealArray1DHDF5Dataset(reader1, simInputDatasetsNames[Stringification(volumeRate)], volumeRate);
