### ISSUE TITLE
Compilation error on Arch linux

### ISSUE THREAD

**Issue by sgarnotel** [FreeFem/FreeFem-sources#18]
Compilation output:
make[3] : on entre dans le répertoire « /home/simon/Documents/Install/FreeFem/FreeFem-sources/src/nw »
g++  -g  -DNDEBUG -O3 -mmmx -mavx -DBAMG_LONG_LONG  -DNCHECKPTR -fPIC  -rdynamic -o FreeFem++ sansrgraph.o parallelempi-empty.o ffapi.o ../lglib/liblg.a ../fflib/libff.a  -Wl,-rpath,/usr/local/ff-petsc/real/lib -L/usr/local/ff-petsc/real/lib -lumfpack -lklu -lcholmod -lbtf -lccolamd -lcolamd -lcamd -lamd -lsuitesparseconfig -larpack -llapack  -llapack -lblas -ldl -lm -lrt  /usr/lib/gcc/x86_64-pc-linux-gnu/8.1.0/../../../libgfortran.so /usr/lib/gcc/x86_64-pc-linux-gnu/8.1.0/../../../libquadmath.so -L/usr/lib   -lm -ldl -lz -lsz -lhdf5_hl  -lhdf5 -lhdf5_hl
../fflib/libff.a(lgfem.o) : Dans la fonction « TypeSolve<true, Solve>::SolveInit::operator()(void*) const » :
/home/simon/Documents/Install/FreeFem/FreeFem-sources/src/fflib/problem.hpp:493 : référence indéfinie vers « AnyTypeWithOutCheck Problem::eval<double, Fem2D::GFESpace<Fem2D::Mesh3>, v_fes3>(void*, Problem::Data<Fem2D::GFESpace<Fem2D::Mesh3> >*, CountPointer<MatriceCreuse<double> >&, MatriceCreuse<CadnaType<double>::Scalaire>*&) const »
/home/simon/Documents/Install/FreeFem/FreeFem-sources/src/fflib/problem.hpp:491 : référence indéfinie vers « AnyTypeWithOutCheck Problem::eval<std::complex<double>, Fem2D::GFESpace<Fem2D::Mesh3>, v_fes3>(void*, Problem::Data<Fem2D::GFESpace<Fem2D::Mesh3> >*, CountPointer<MatriceCreuse<std::complex<double> > >&, MatriceCreuse<CadnaType<std::complex<double> >::Scalaire>*&) const »
/home/simon/Documents/Install/FreeFem/FreeFem-sources/src/fflib/problem.hpp:484 : référence indéfinie vers « AnyTypeWithOutCheck Problem::eval<double, Fem2D::FESpace, v_fes>(void*, Problem::Data<Fem2D::FESpace>*, CountPointer<MatriceCreuse<double> >&, MatriceCreuse<CadnaType<double>::Scalaire>*&) const »
collect2: error: ld a retourné le statut de sortie 1
make[3]: *** [Makefile:578: FreeFem++] Error 1
make[3] : on quitte le répertoire « /home/simon/Documents/Install/FreeFem/FreeFem-sources/src/nw »

**Comment by sgarnotel** [comment]
This bug is due to gcc version 8.1.0 on Arch, use gcc 7.3.0 instead

**Comment by stefanhusmann** [comment]
The error is also in GCC 8.2.0  on Arch Linux, and prpbably also in Debian when using their flavour of gcc 8.

**Comment by sgarnotel** [comment]
Fixed in ad68038
