### ISSUE TITLE
make petsc-slepc fails when installing the arpack

### ISSUE THREAD

**Issue by Baishi03** [FreeFem/FreeFem-sources#198]
[configure.log](https://github.com/FreeFem/FreeFem-sources/files/7191679/configure.log)
And there is a plain text document called arpack-ng-3.8.0.tar.gz which size is 0 bytes in /home/wby/Software/install-FreeFem/FreeFem-sources-4.9/3rdparty/ff-petsc/petsc-3.15.0/fr/externalpackages/git.slepc/installed-arch-linux2-c-opt/externalpackages/

**Comment by Baishi03** [comment]
I test my proxy, it's ok. So i wonder what should i do next? Looking forward to your reply, thank you!

**Comment by prj-** [comment]
Can you download the following file and do you get an empty tarball https://github.com/prj-/arpack-ng/archive/b64dccb.tar.gz?

**Comment by Baishi03** [comment]
> Can you download the following file and do you get an empty tarball https://github.com/prj-/arpack-ng/archive/b64dccb.tar.gz?

Thans for your relpy!
Yes, i can download the tarball by wget and it's not empty named 
arpack-ng-b64dccb461ffc98257bbb1e537a4fc5e96094018.tar.gz

However, yesterday i tried twice, first i downloaded tarball from the link above, and renamed it to b64dccb.tar.gz then put it to the location where arpack-ng-3.8.0.tar.gz located(i.e. /home/wby/Software/install-FreeFem/FreeFem-sources-4.9/3rdparty/ff-petsc/petsc-3.15.0/fr/externalpackages/git.slepc/installed-arch-linux2-c-opt/externalpackages/), and rerun make petsc-slepc, it still failed with the same log. 

Secondly, i renamed  it to arpack-ng-3.8.0.tar.gz, then do the same things, there was still that same error log.

It does not apear to detect the existence of an existing tarball.

So i wondering how to make it?

**Comment by prj-** [comment]
I don't really know. The simplest advice I can come up with is to simply remove all occurrences of `--download-slepc-configure-arguments="--download-arpack=https://github.com/prj-/arpack-ng/archive/b64dccb.tar.gz"` in `3rdparty/ff-petsc/Makefile` and retry `make petsc-slepc`.

**Comment by Baishi03** [comment]
> I don't really know. The simplest advice I can come up with is to simply remove all occurrences of `--download-slepc-configure-arguments="--download-arpack=https://github.com/prj-/arpack-ng/archive/b64dccb.tar.gz"` in `3rdparty/ff-petsc/Makefile` and retry `make petsc-slepc`.

Thanks for your reply! 
I tried that, but failed with the same error. Then i make clean and remake, it worked!
I'm very appreciated for your help!

**Comment by prj-** [comment]
You are very welcome, don't hesitate if you run into additional issues or need some help.
