### ISSUE TITLE
How to install Pardiso in FreeFem++ v4.9

### ISSUE THREAD

**Issue by Baishi03** [FreeFem/FreeFem-sources#201]
I tried the follow example to use the pardiso, but failed.
_http://jolivet.perso.enseeiht.fr/FreeFem-tutorial/section_4/example2.edp.html_

load "Pardiso", and the error showed that 
/FreeFem/lib/ff++/4.9/lib/PARDISO.so: cannot open shared object file: No such file or directory.

So i wonder how to install Pardiso in FreeFem?

**Comment by prj-** [comment]
Do you have Intel MKL or Intel oneAPI installed on your machine? If so, then you need to enable the MKL via `./configure`, otherwise, you need to install that first.
