### ISSUE TITLE
Request for License file

### ISSUE THREAD

**Issue by ekohlwey** [FreeFem/FreeFem-sources#209]
Can you please add a license file so that it is clear how FreeFEM can be used? Thank you!

**Comment by prj-** [comment]
You can go there: https://freefem.org. It says LGPL 3.0 with a link to https://www.gnu.org/licenses/lgpl-3.0.txt.

**Comment by ekohlwey** [comment]
Thanks so much, that's useful to know, and a great license :) A lot of companies now require a LICENSE.txt file in the actual repo in order to use code, even on an exploratory basis. Do you think you all could add one?

**Comment by prj-** [comment]
Done in https://github.com/FreeFem/FreeFem-sources/commit/b2268bcd74b54cced01d9260011dde82699f0f90. I will close the issue but feel free to re-open it if you have a related question.
