### ISSUE TITLE
Trunc not working anymore

### ISSUE THREAD

**Issue by ffeppon** [FreeFem/FreeFem-sources#221]
Dear developpers,

I encounter again some bug on some meshes when I trunc them with FreeFEM. 

```c++
mesh Th=readmesh("Th_0000.mesh");
mesh Thf=trunc(Th,region==3);
mesh Ths=trunc(Th,region==2);
```
[mesh.zip](https://github.com/FreeFem/FreeFem-sources/files/8251865/mesh.zip)

This results in 
```
Assertion fail : (iseuil)
	line :1819, in file ../femlib/fem.cpp
Assertion fail : (iseuil)
	line :1819, in file ../femlib/fem.cpp
 err code 6 ,  mpirank 0
```

Many thanks if you can fix this bug. 

Florian

**Comment by frederichecht** [comment]
I have correct in last push  on develop 
https://github.com/FreeFem/FreeFem-sources/compare/develop?expand=1

**Comment by frederichecht** [comment]
Thank for find this mistake,
