### ISSUE TITLE
Please add PETSc and SLEPc in distributed packages

### ISSUE THREAD

**Issue by Trophime** [FreeFem/FreeFem-sources#225]
Hi,
it would be great if the debian/ubuntu package you provide contains all freefem plugins
especially PETSc and SLEPc.

Best
C

**Comment by Trophime** [comment]
The package for ubuntu, at 4.11 version, does not containt PETSc.so :((

**Comment by sgarnotel** [comment]
Did you install `FreeFEM-4.11-amd64.deb` or `FreeFEM-4.11-amd64-ubuntu20.04.deb` ?

**Comment by prj-** [comment]
You are looking at the wrong place of the Jenkins log. It says down below:
```
../seq/ff-c++ -auto -mpi PETSc.cpp
eval ../seq/ff-c++ '-mpi' PETSc.cpp -std=c++14 -std=c++14 -DWITH_slepc -Wl,-rpath,/usr/local/ff-petsc/r/lib -L/usr/local/ff-petsc/r/lib -lslepc -I/usr/local/ff-petsc/r/include -DWITH_petsc -Wl,-rpath,/usr/local/ff-petsc/r/lib -L/usr/local/ff-petsc/r/lib -lpetsc -Wl,-rpath,/usr/local/ff-petsc/r/lib -L/usr/local/ff-petsc/r/lib -Wl,-rpath,/usr/lib/x86_64-linux-gnu/openmpi/lib -L/usr/lib/x86_64-linux-gnu/openmpi/lib -Wl,-rpath,/usr/lib/gcc/x86_64-linux-gnu/9 -L/usr/lib/gcc/x86_64-linux-gnu/9 -lHYPRE -lspqr -lumfpack -lklu -lcholmod -lbtf -lccolamd -lcolamd -lcamd -lamd -lsuitesparseconfig -lcmumps -ldmumps -lsmumps -lzmumps -lmumps_common -lpord -lscalapack -lsuperlu -llapack -lblas -lparmmg -lmmg -lmmg3d -lptesmumps -lptscotchparmetis -lptscotch -lptscotcherr -lesmumps -lscotch -lscotcherr -lparmetis -lmetis -ltet -lm -lstdc++ -ldl -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi -lgfortran -lm -lgfortran -lm -lgcc_s -lquadmath -lpthread -lrt -lquadmath -lstdc++ -ldl -I/usr/local/ff-petsc/r/include -DWITH_blas -llapack -lblas -I/usr/local/ff-petsc/r/include -pthread -L/usr/lib/x86_64-linux-gnu/openmpi/lib -lmpi_cxx -lmpi -I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -I/usr/lib/x86_64-linux-gnu/openmpi/include
/usr/bin/mpic++ -c -fPIC -std=c++14 -std=c++14 '-I../seq/include' '-DWITH_slepc' '-I/usr/local/ff-petsc/r/include' '-DWITH_petsc' '-I/usr/local/ff-petsc/r/include' '-DWITH_blas' '-I/usr/local/ff-petsc/r/include' '-I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi' '-I/usr/lib/x86_64-linux-gnu/openmpi/include' -g -O2 -DNDEBUG -O3 -mtune=generic -std=c++14 -DBAMG_LONG_LONG -DNCHECKPTR -fPIC -I/usr/local/ff-petsc/r/include -I/usr/include/hdf5/serial -I/usr/include 'PETSc.cpp'
```

**Comment by Trophime** [comment]
I've installed FreeFEM-4.11-amd64-ubuntu20.04.deb from your gitrepo.
You can easily test this. Just start a docker and run:

-- FreeFem++ v4.11 (Fri 08 Apr 2022 01:02:23 PM CEST - git v4.11)
   file : loadmesh.edp
 Load: lg_fem lg_mesh lg_mesh3 eigenvalue 
    1 : load "PETSc"
Load error: PETSc
	 fail: 
 dlerror : /usr/local/lib/ff++/4.11/lib/PETSc.so: cannot open shared object file: No such file or directory
list prefix: './' '/usr/local/lib/ff++/4.11/lib/' list suffix: '' , '.so' 
  current line = 1
Load error : PETSc
	line number :1, PETSc
error Load error : PETSc
	line number :1, PETSc
 code = 2 mpirank: 0

with loadmesh.edp (just change the msh):

load "PETSc"
DM dm("cylinder_base.msh");
mesh Th = dm;

plot(Th);

**Comment by prj-** [comment]
You are using the `FreeFem++` binary, not `FreeFem++-mpi`. This is not expected to work.

**Comment by prj-** [comment]
No problem, please re-open if this still does not work with `FreeFem++-mpi`.

**Comment by prj-** [comment]
With a `DM`? I think this is a pending issue with DMPlex from PETSc. Could you please share a usable `.msh` and let me know what you'd like to retrieve exactly so that I can give it a go? If some plumbing is missing from within the PETSc plugin, I'll try to add that. If it's a limitation of DMPlex, I'll ask the appropriate people.

**Comment by Trophime** [comment]
Actually, I would like to import a mesh from gmsh and recover volumes/surfaces and BC ids.
I've tried with DM following a discussion on discourse.
I've tried to convert the gmsh mesh to gmsh 2 format, to mesh/meshd with Gmsh
All tests failed somehow.
Next, I've tried meshio to convert msh to mesh, same pb.
I'll send a test mesh by mail.
Thanks
