### ISSUE TITLE
metis.edp runs very slowly

### ISSUE THREAD

**Issue by cdoucet** [FreeFem/FreeFem-sources#24]
Continuous integration on feature-cmake branch has launched metis.edp for several hours without achieving computation:

> https://ci.inria.fr/freefem/job/FreeFem-source-feature-cmake-UbuntuAll/7/console

Here is the output which make me guess that the next test is metis.edp:

> [0;32m OK (Exec) [m /usr/bin/mpiexec -np 4 /builds/workspace/FreeFem-source-feature-cmake-UbuntuAll/build_cmake/src/FreeFem++-mpi -nw lapack.edp ( see lapack.edp-out )
[0;32m OK (Exec) [m /usr/bin/mpiexec -np 4 /builds/workspace/FreeFem-source-feature-cmake-UbuntuAll/build_cmake/src/FreeFem++-mpi -nw layer.edp ( see layer.edp-out )
[0;32m OK (Exec) [m /usr/bin/mpiexec -np 4 /builds/workspace/FreeFem-source-feature-cmake-UbuntuAll/build_cmake/src/FreeFem++-mpi -nw load.edp ( see load.edp-out )
[0;32m OK (Exec) [m /usr/bin/mpiexec -np 4 /builds/workspace/FreeFem-source-feature-cmake-UbuntuAll/build_cmake/src/FreeFem++-mpi -nw meditddm.edp ( see meditddm.edp-out )

I think it is important to understand why (load errror, high complexity, ...) and make it run faster.

**Comment by sgarnotel** [comment]
Do you know where the file meditddm.edp-out is located on the CI-slave ?

**Comment by sgarnotel** [comment]
Really strange behavior, the script directly failed on the CI:
```
ci@ubuntu1604:~/workspace/FreeFem-source-feature-cmake-UbuntuAll/build_cmake$ src/FreeFem++-mpi ../examples++-load/meditddm.edp
-- FreeFem++ v  3.500000 (date ' Tue Jul 17 12:43:47 CEST 2018')
 Load: lg_fem lg_mesh lg_mesh3 eigenvalue parallelempi 
    1 : // meditddm.edp
    2 : load "medit"
load error : medit
 	 fail : 
 dlerror : ./medit.so: cannot open shared object file: No such file or directory
list  prefix: '' './' list  suffix : '' , '.so' 

 Error line number 2, in file ../examples++-load/meditddm.edp, before  token medit
Error load
  current line = 2 mpirank 0 / 1
Compile error : Error load
	line number :2, medit
error Compile error : Error load
	line number :2, medit
 code = 1 mpirank: 0
```

**Comment by sgarnotel** [comment]
Just a remark: this script sould not be launched in parallel

**Comment by cdoucet** [comment]
Ok I will check the main test script and see the difference with the one stored in master branch to understand why it is run in parallel. However, I do not understand why it is slow with Jenkins. Instead of detecting loading failures, it could be a better idea to skip tests when modules to load are not available.

**Comment by sgarnotel** [comment]
Yes, It could be better.
The new launch https://ci.inria.fr/freefem/job/FreeFem-source-feature-cmake-UbuntuAll/8/console freezes on PETSc tests. I think it is not compiled right now, yes?

**Comment by cdoucet** [comment]
Yes, I will manage Petsc (and some other modules) later. For the moment, I just want to test configuration, building, testing and installation to have a complete pipeline with cmake.

**Comment by cdoucet** [comment]
Ok, it seems that metis.cpp was skipped by cmake. This is p.edp which was slow but now it runs fast. I need to make further investigations to understand why. Thank you Simon!

**Comment by cdoucet** [comment]
With CTest, the problem disappears. I close this issue.
