### ISSUE TITLE
atanh does not exist

### ISSUE THREAD

**Issue by cdoucet** [FreeFem/FreeFem-sources#25]
I get the following error message from examples++/ccc-adp.edp

> -- FreeFem++ v  3.500000 (date ' Wed Jul 18 09:02:54 CEST 2018')
 Load: lg_fem lg_mesh lg_mesh3 eigenvalue 
    1 : //  -----  
    2 : real eps =  0.0001;
    3 : real h=1;
    4 : real hmin=0.000005;
    5 : real val=50; 
    6 : real coef=50; // err = 1/100
    7 : int nbiter=10,firstplot=3;
    8 : func f = y*x*x+y*y*y+h*tanh(val*(sin(5.0*y)-2.0*x));
    9 : ofstream fff("err.dat");
   10 : cout << atanh The Identifier atanh does not exist 

> Error line number 10, in file /builds/workspace/FreeFem-source-feature-cmake-UbuntuAll/examples++/ccc-adp.edp, before  token atanh

>  current line = 10
Compile error : 
	line number :10, atanh
error Compile error : 
	line number :10, atanh
 code = 1 mpirank: 0

**Comment by sgarnotel** [comment]
This function id defined in `fflib/AFunction.cpp`.
I suppose it arrives during the cmake test, so does this file is correctly compiled ?

**Comment by cdoucet** [comment]
Yes, I think the problem comes from the fact that HAVE_ATANH is not defined. However, instead of defining it, I would suggest to remove this conditional preprocessor directive because atanh is part of C++99 standard :

> http://www.cplusplus.com/reference/cmath/atanh/

Do you agree? In this case, I can make a PR to remove all other similar definitions in AFunction.cpp.

**Comment by cdoucet** [comment]
Ok. I tested it and I confirm that removing the preprocessor directive solves the problem.

**Comment by sgarnotel** [comment]
So, it have to be tested in the cmake procedure too

**Comment by cdoucet** [comment]
I disagree. Why shall we test the existence of something whose existence is guaranteed by the C++ standard? Why don't we test that printf is available too in this case?

**Comment by sgarnotel** [comment]
Indeed, since cmake is an after 2000 technology, we can suppose that all people that uses cmake has an up-to-date environement.
So we can skip all tests related to functions already in C++99 standard.
But could you defined this macros in the cmake process to ensure compatibility with autoconf and keep the `AFunction.cpp` file unchanged?

**Comment by cdoucet** [comment]
Modifying Afunction.cpp in develop branch will also ensure compatibility between Autoconf and CMake. A compiler which does not support any C++ standard is not a C++ compiler, by definition. Nothing related to CMake here. Removing directives from Afunction.cpp (HAVE_ATANH, HAVE_ASINH, HAVE_ACOSH) is the best solution.

**Comment by sgarnotel** [comment]
So, we have to remove directives from `AFunction.cpp` and equally remove the test in `configure.ac`.
@frederichecht do you agree with that?
PS: `erfc`, `tgamma` are equally in C++99 standard, `getenv` is standard
