### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [FreeFem/FreeFem-sources#251]
Would you like to wrap any pointers with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [ConjugueGradient](https://github.com/FreeFem/FreeFem-sources/blob/1312e9d9c06fec8d3d49f1452df6f951901d85c9/src/femlib/CG.cpp#L195)
- [Transfo_Mesh3](https://github.com/FreeFem/FreeFem-sources/blob/a7d3089c6dd756242fb978bd9a1e0cf290eeb793/plugin/seq/TransfoMesh_v2.cpp#L51)
- [Triangles::gibbs](https://github.com/FreeFem/FreeFem-sources/blob/a7d3089c6dd756242fb978bd9a1e0cf290eeb793/src/bamglib/Meshgibbs.cpp#L959)

**Comment by elfring** [comment]
:thought_balloon: Would you like to take [the C++ guideline “R.11: Avoid calling new and delete explicitly”](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r11-avoid-calling-new-and-delete-explicitly "Recommendations around allocation and deallocation") better into account?

**Comment by prj-** [comment]
No.
