### ISSUE TITLE
fftw custom install autodetection

### ISSUE THREAD

**Issue by simonlegrand** [FreeFem/FreeFem-sources#252]
Hello,

I tried to compile ff (on a HPC cluster) against an existing fftw made visible through environment variables (FFTW_ROOT and FFTW_DIR) but configure doesn't seem to see it. I noticed there are no way to explicitly pass the fftw path to the configure script (--with-fftw). Is there a way to achieve this?

Regards,

Simon

**Comment by prj-** [comment]
There is no way to pass those flags to configure currently, so there it's not possible.

**Comment by simonlegrand** [comment]
Thanks for the answer!
