### ISSUE TITLE
msh3 extract run out of memory

### ISSUE THREAD

**Issue by sgarnotel** [FreeFem/FreeFem-sources#26]
The `extract` function of the `msh3` library run out of memory (128G RAM machine) on this example:
[ExtractExample.txt](https://github.com/FreeFem/FreeFem-sources/files/2206494/ExtractExample.txt)
(the file extension is .txt due to Github limitations, it is an .edp file)

The error occurs in [msh3.cpp - line 5952](https://github.com/FreeFem/FreeFem-sources/blob/4b80c3516bfb205085c1b75e176b6ec2bbc8f5e4/examples%2B%2B-load/msh3.cpp#L5952)

Is it due to a mesh misdefinition or to the `FQuadTree` function ?

**Comment by frederichecht** [comment]
It now working
