### ISSUE TITLE
Win10 compiling error with MS-MPI +Msys2 latest-version +git : error occuring for lacking libarpack.a file 

### ISSUE THREAD

**Issue by Hsiang-Yj** [FreeFem/FreeFem-sources#267]
I follow the installation guide website:[https://doc.freefem.org/introduction/installation.html#compilation-on-windows](url), to compile the FreeFem, however something wrong happened. The screenshot of Msys2_MinGW_64 is like the following picture:
![Inkedbug](https://user-images.githubusercontent.com/61173998/236689903-a7175aa5-8d8e-4637-aa9e-32c76afbdba1.jpg)

Pls tell me how to fix it! Thanks a lot!

**Comment by prj-** [comment]
You should compile PETSc first, see https://github.com/FreeFem/FreeFem-sources/blob/develop/README.md#freefem. Make sure that you have these pacman packages installed `autoconf automake-wrapper bison bsdcpio make git mingw-w64-x86_64-toolchain patch python flex pkg-config pkgfile tar unzip mingw-w64-x86_64-cmake mingw-w64-x86_64-msmpi mingw-w64-x86_64-openblas mingw-w64-x86_64-jq`.

**Comment by Hsiang-Yj** [comment]
Thank you, I try to compile PETS first, but it feedback: no mpicc in （......）as following:
![屏幕截图 2023-05-08 094735](https://user-images.githubusercontent.com/61173998/236716548-85cc47a2-494d-468e-b574-0b1dbc304aa0.png)

**Comment by Hsiang-Yj** [comment]
My 3rdparty isall download from git: 
<img width="266" alt="1" src="https://user-images.githubusercontent.com/61173998/236716835-ee6433a4-6fa9-44f1-9a61-6831017e61ac.png">
My config.log in FreeFem-sources is below:
[config.log](https://github.com/FreeFem/FreeFem-sources/files/11417106/config.log)

**Comment by prj-** [comment]
Please, make sure that:
1. you are on a fresh copy  of FreeFEM `develop` branch;
2. the package `mingw-w64-x86_64-msmpi` is installed;
3. you are using a proper `--prefix`, see again README.md referenced earlier.

You should not use `SUDO` to install PETSc (which will install ARPACK).

**Comment by prj-** [comment]
You are still not using a fresh FreeFEM `develop` branch, see https://github.com/FreeFem/FreeFem-sources/blob/b34f967acc05df3d91f4acf102c750518bb2d7ec/3rdparty/getall#L176 And it looks like you installed the wrong Python, so you may want to type `export PYTHON=/usr/bin/python` in your terminal before `make petsc-slepc`.

**Comment by Hsiang-Yj** [comment]
Thank u, I will use a fresh FreeFEM develop branch to have another try, and my python version is 3.10.11, I didn't do some special operation on Python, which already existed in my computer. Did the python suit for this project?
![3debug](https://user-images.githubusercontent.com/61173998/236779154-16052d1a-aae1-4bbb-9eba-187b3b249f9d.png)

**Comment by prj-** [comment]
No, you must use `/usr/bin/python`, cf. the `export` command from above. Just run it before `make petsc-slepc`.

**Comment by Hsiang-Yj** [comment]
Okay, appreciate for your suggestion. I will try again!

**Comment by Hsiang-Yj** [comment]
Can you provide me some more suggestion! Thank U very much!
![4debug](https://user-images.githubusercontent.com/61173998/236787436-793da41c-36ea-498f-bab0-87da13e68a94.png)

**Comment by prj-** [comment]
You are still not using a fresh `develop` branch...

**Comment by prj-** [comment]
And you still did not install `mingw-w64-x86_64-msmpi`. Why ask for advices, if you don't follow the instructions? Once the package is installed, you'll have
```
$ which mpicc
/mingw64/bin/mpicc
```
You currently have `which: no mpicc`.

**Comment by prj-** [comment]
Can I close the issue or do you still have issues?

**Comment by Hsiang-Yj** [comment]
Of course. Thank you for your time!



from：iPhone


------------------ Original ------------------
From: Pierre Jolivet ***@***.***&gt;
Date: Sat,May 13,2023 10:00 PM
To: FreeFem/FreeFem-sources ***@***.***&gt;
Cc: Hsiang-Yj ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [FreeFem/FreeFem-sources] Win10 compiling error with MS-MPI+Msys2 latest-version +git : error occuring for lacking libarpack.a file (Issue #267)





 
Can I close the issue or do you still have issues?
