### ISSUE TITLE
A higher BDM finite element

### ISSUE THREAD

**Issue by cjj197** [FreeFem/FreeFem-sources#278]
Hello everyone
  I’m trying to solve the Stokes equations with BDM finite element in Freefem. However, there seems to be only BDM1 finite element. It’s so frustrating. Because I want to verify the convergence-order of the error with a higher BDM finite element. Is there any other way to use a higher BDM finite element? Or the next time the software update can add a higher BDM finite element？
Thank you for your help！

**Comment by prj-** [comment]
Please stop spamming the same issue. Closing as this is a duplicate of https://community.freefem.org/t/a-higher-bdm-element-in-freefem/2531.
