### ISSUE TITLE
Failure of include.edp

### ISSUE THREAD

**Issue by cdoucet** [FreeFem/FreeFem-sources#28]
I do not understand why include.edp fails (with CMake). I added to PATH the full path of examples++ (containing funct.edp) but it does not solve the problem (unless I made a mistake somewhere).

> Load: lg_fem lg_mesh lg_mesh3 eigenvalue 
    1 : { include "funct.edp" Error openning file funct.edp in: 
  -- try  :"funct.edp"

>  Error line number 1, in file /home/cdoucet/Depots/github/FreeFem-sources/examples++/include.edp, before  token funct.edp
lex: Error input openning file 
  current line = 1
Compile error : lex: Error input openning file 
	line number :1, funct.edp
error Compile error : lex: Error input openning file 
	line number :1, funct.edp
 code = 1 mpirank: 0

**Comment by sgarnotel** [comment]
The `FF_INCLUDEPATH` variable seems to not be enought:
```
ci@ubuntu1604:~/workspace/FreeFem-source-feature-cmake-UbuntuAll/build_cmake/src$ export FF_INCLUDEPATH=/builds/workspace/FreeFem-source-feature-cmake-UbuntuAll/examples++
ci@ubuntu1604:~/workspace/FreeFem-source-feature-cmake-UbuntuAll/build_cmake/src$ ./FreeFem++ ../../examples++/include.edp 
-- FreeFem++ v  3.500000 (date ' Thu Jul 19 11:33:00 CEST 2018')
 Load: lg_fem lg_mesh lg_mesh3 eigenvalue 
    1 : { include "funct.edp" Error openning file funct.edp in: 
  -- try  :"funct.edp"

 Error line number 1, in file ../../examples++/include.edp, before  token funct.edp
lex: Error input openning file 
  current line = 1
Compile error : lex: Error input openning file 
	line number :1, funct.edp
error Compile error : lex: Error input openning file 
	line number :1, funct.edp
 code = 1 mpirank: 0
```
When the test is launched in the examples++ directory, all works fine.

An other remark, it misses `ref.edp` in the  `examples++` folder, did you remove it @cdoucet ?

**Comment by cdoucet** [comment]
Yes, I removed it by mistake because I thought it has been updated after tests. I don't understand exactly what is happening with this file. I have two different versions of it, one in my local repository and the other in develop branch. Here is the output of diff:

> 1c1
< real REFaadaptation=0.000319245;
---
> real REFaadaptation=0.00031908;
4c4
< real REFaamove=0.0714792;
---
> real REFaamove=0.070846;
9,10c9,10
< real REFdemo1=1.36626;
< real REFdemo=1.31616;
---
> real REFdemo1=1.36948;
> real REFdemo=1.36948;
14,16c14,16
< real REFNSP1P1b=0.0463864;
< real REFNSP1P1=0.0509257;
< real REFNSP1P2=0.0454064;
---
> real REFNSP1P1b=0.0463193;
> real REFNSP1P1=0.0529355;
> real REFNSP1P2=0.0453229;
18c18
< real REFRichard=95.8416;
---
> real REFRichard=95.8882;

**Comment by cdoucet** [comment]
I mean if it stands for reference values for non-regression testing, then it should not be updated but fixed once for all.

**Comment by sgarnotel** [comment]
You will have the same problem with `examples++-3d/Poisson.edp` which require a mesh in the current directory

**Comment by cdoucet** [comment]
Yes, the problem I have with "include" directive is involved in most of failing tests. Solving it would be a great improvement for the cmake version.

**Comment by cdoucet** [comment]
I found the problem. HAVE_GETENV must be defined if one want to use FF_INCLUDEPATH. But, as I said in issue #25, these definitions are useless in C++. Here is the reference for std::getenv:
https://fr.cppreference.com/w/cpp/utility/program/getenv
