### ISSUE TITLE
Meaning of assertion (ii==MotClef.end())

### ISSUE THREAD

**Issue by cdoucet** [FreeFem/FreeFem-sources#29]
What is the meaning of the assertion involved in the error message below?

> Load: lg_fem lg_mesh lg_mesh3 eigenvalue
    1 : load "metis"  current line = 1
Assertion fail : (ii==MotClef.end())
  line :112, in file /home/cdoucet/Depots/github/FreeFem-sources/src/fflib/lex.cpp
error Assertion fail : (ii==MotClef.end())
  line :112, in file /home/cdoucet/Depots/github/FreeFem-sources/src/fflib/lex.cpp
 code = 5 mpirank: 0

**Comment by frederichecht** [comment]
cela arrive si le mot clef était deja un mot clef. 
les mots clefs doivent être unique.
