### ISSUE TITLE
Unable to install FreeFEM++  Error at step: ./3rdparty/getall -a

### ISSUE THREAD

**Issue by Geethesh-Naiyyalga** [FreeFem/FreeFem-sources#306]
`$ ./getall -a
ARPACK arpack96.tar.gz  md5 change => reget 
ARPACK patch.tar.gz  md5 change => reget 
BLAS blas-3.7.1.tgz done
BLAS cblas.tgz done
OpenBLAS OpenBLAS.tar.gz done
FFTW fftw-3.3.8.tar.gz done
freeYams freeyams.2012.02.05.tgz  md5 change => reget 
Gmm++ gmm-4.2.tar.gz  md5 change => reget 
Ipopt Ipopt-3.12.4.tgz done
METIS metis-5.1.0.tar.gz done
ParMETIS ParMetis-4.0.3.tar.gz done
MMG3D mmg3d4.0.tgz done
mshmet mshmet.2012.04.25.tgz  md5 change => reget 
MUMPS MUMPS_5.0.2.tar.gz  md5 change => reget 
NLopt nlopt-2.2.4.tar.gz done
ScaLAPACK scalapack-2.1.0.tgz done
Scotch scotch-v6.1.0.tar.gz done
SuiteSparse SuiteSparse-4.4.4.tar.gz done
SuperLU superlu-5.2.2.zip done
TetGen tetgen1.5.1-beta1.tar.gz done
mmg mmg.zip  md5 change => reget 
parmmg parmmg.zip  md5 change => reget 
PETSc petsc-3.20.2.tar.gz done
htool htool.zip done
hpddm hpddm.zip done
bemtool bemtool.zip done
Boost boost_for_bemtool.tar.gz  md5 change => reget 
libpthread-google libpthread-google.tar.gz  md5 change => reget 
../bin/build/download http://www.caam.rice.edu/software/ARPACK/SRC/arpack96.tar.gz pkg/arpack96.tar.gz 
../bin/build/download http://www.caam.rice.edu/software/ARPACK/SRC/patch.tar.gz pkg/patch.tar.gz 
../bin/build/download https://www.ljll.math.upmc.fr/frey/ftp/archives/freeyams.2012.02.05.tgz pkg/freeyams.2012.02.05.tgz 
--2024-05-27 17:12:48--  http://www.caam.rice.edu/software/ARPACK/SRC/arpack96.tar.gz
Resolving www.caam.rice.edu (www.caam.rice.edu)... ../bin/build/download http://pkgs.freefem.org/gmm-4.2.tar.gz pkg/gmm-4.2.tar.gz 
--2024-05-27 17:12:48--  http://www.caam.rice.edu/software/ARPACK/SRC/patch.tar.gz
Resolving www.caam.rice.edu (www.caam.rice.edu)... ../bin/build/download https://www.ljll.math.upmc.fr/frey/ftp/archives/mshmet.2012.04.25.tgz pkg/mshmet.2012.04.25.tgz 
--2024-05-27 17:12:48--  https://www.ljll.math.upmc.fr/frey/ftp/archives/freeyams.2012.02.05.tgz
../bin/build/download http://mumps.enseeiht.fr/MUMPS_5.0.2.tar.gz pkg/MUMPS_5.0.2.tar.gz 
--2024-05-27 17:12:48--  http://pkgs.freefem.org/gmm-4.2.tar.gz
Resolving pkgs.freefem.org (pkgs.freefem.org)... ../bin/build/download https://github.com/prj-/mmg/archive/1e26c551fdb969b38da46389bb0d95a35eb70d9d.zip pkg/mmg.zip 
134.157.2.44
Connecting to pkgs.freefem.org (pkgs.freefem.org)|134.157.2.44|:80... --2024-05-27 17:12:48--  https://www.ljll.math.upmc.fr/frey/ftp/archives/mshmet.2012.04.25.tgz
connected.
HTTP request sent, awaiting response... ../bin/build/download https://github.com/prj-/ParMmg/archive/9cb2f7a22ef590d196d028970f462889bf610c53.zip pkg/parmmg.zip 
--2024-05-27 17:12:48--  http://mumps.enseeiht.fr/MUMPS_5.0.2.tar.gz
Resolving mumps.enseeiht.fr (mumps.enseeiht.fr)... ../bin/build/download https://www.ljll.math.upmc.fr/~tournier/boost_for_bemtool.tar.gz pkg/boost_for_bemtool.tar.gz 
--2024-05-27 17:12:48--  https://github.com/prj-/mmg/archive/1e26c551fdb969b38da46389bb0d95a35eb70d9d.zip
../bin/build/download http://pkgs.freefem.org/libpthread-google.tar.gz pkg/libpthread-google.tar.gz 
--2024-05-27 17:12:48--  https://github.com/prj-/ParMmg/archive/9cb2f7a22ef590d196d028970f462889bf610c53.zip
Resolving www.ljll.math.upmc.fr (www.ljll.math.upmc.fr)... Resolving www.ljll.math.upmc.fr (www.ljll.math.upmc.fr)... --2024-05-27 17:12:48--  https://www.ljll.math.upmc.fr/~tournier/boost_for_bemtool.tar.gz
--2024-05-27 17:12:48--  http://pkgs.freefem.org/libpthread-google.tar.gz
Resolving pkgs.freefem.org (pkgs.freefem.org)... Resolving github.com (github.com)... Resolving github.com (github.com)... 20.207.73.82
20.207.73.82Connecting to github.com (github.com)|20.207.73.82|:443... 
Connecting to github.com (github.com)|20.207.73.82|:443... connected.
connected.
Resolving www.ljll.math.upmc.fr (www.ljll.math.upmc.fr)... HTTP request sent, awaiting response... HTTP request sent, awaiting response... 134.157.2.44
Connecting to pkgs.freefem.org (pkgs.freefem.org)|134.157.2.44|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-05-27 17:12:48 ERROR 404: Not Found.

404 Not Found
2024-05-27 17:12:48 ERROR 404: Not Found.

Error download pkg/mmg.zip
Download failed from https://github.com/prj-/mmg/archive/1e26c551fdb969b38da46389bb0d95a35eb70d9d.zip of mmg.zip
Try other site: http://pkgs.freefem.org/mmg.zip
Error download pkg/parmmg.zip
Download failed from https://github.com/prj-/ParMmg/archive/9cb2f7a22ef590d196d028970f462889bf610c53.zip of parmmg.zip
Try other site: http://pkgs.freefem.org/parmmg.zip
134.157.2.3134.157.2.3

134.157.2.3
Connecting to www.ljll.math.upmc.fr (www.ljll.math.upmc.fr)|134.157.2.3|:443... Connecting to www.ljll.math.upmc.fr (www.ljll.math.upmc.fr)|134.157.2.3|:443... Connecting to www.ljll.math.upmc.fr (www.ljll.math.upmc.fr)|134.157.2.3|:443... connected.
connected.
connected.
--2024-05-27 17:12:48--  http://pkgs.freefem.org/mmg.zip
Resolving pkgs.freefem.org (pkgs.freefem.org)... --2024-05-27 17:12:48--  http://pkgs.freefem.org/parmmg.zip
Resolving pkgs.freefem.org (pkgs.freefem.org)... 134.157.2.44
Connecting to pkgs.freefem.org (pkgs.freefem.org)|134.157.2.44|:80... connected.
HTTP request sent, awaiting response... 134.157.2.44
Connecting to pkgs.freefem.org (pkgs.freefem.org)|134.157.2.44|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-05-27 17:12:48 ERROR 404: Not Found.

Error download pkg/gmm-4.2.tar.gz
Download failed from http://pkgs.freefem.org/gmm-4.2.tar.gz of gmm-4.2.tar.gz
Try other site: http://pkgs.freefem.org/gmm-4.2.tar.gz
--2024-05-27 17:12:48--  http://pkgs.freefem.org/gmm-4.2.tar.gz
Resolving pkgs.freefem.org (pkgs.freefem.org)... 134.157.2.44
Connecting to pkgs.freefem.org (pkgs.freefem.org)|134.157.2.44|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-05-27 17:12:48 ERROR 404: Not Found.

Error download pkg/libpthread-google.tar.gz
Download failed from http://pkgs.freefem.org/libpthread-google.tar.gz of libpthread-google.tar.gz
Try other site: http://pkgs.freefem.org/libpthread-google.tar.gz
--2024-05-27 17:12:48--  http://pkgs.freefem.org/libpthread-google.tar.gz
Resolving pkgs.freefem.org (pkgs.freefem.org)... 134.157.2.44
Connecting to pkgs.freefem.org (pkgs.freefem.org)|134.157.2.44|:80... connected.
HTTP request sent, awaiting response... 147.127.176.144
Connecting to mumps.enseeiht.fr (mumps.enseeiht.fr)|147.127.176.144|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-05-27 17:12:49 ERROR 404: Not Found.

404 Not Found
2024-05-27 17:12:49 ERROR 404: Not Found.

Error download pkg/parmmg.zip
Download 2 times failed from http://pkgs.freefem.org/parmmg.zip of parmmg.zip
Try (2 times)  other site: http://104.46.50.187/pkg/parmmg.zip
Error download pkg/mmg.zip
Download 2 times failed from http://pkgs.freefem.org/mmg.zip of mmg.zip
Try (2 times)  other site: http://104.46.50.187/pkg/mmg.zip
--2024-05-27 17:12:49--  http://104.46.50.187/pkg/parmmg.zip
Connecting to 104.46.50.187:80... connected.
HTTP request sent, awaiting response... --2024-05-27 17:12:49--  http://104.46.50.187/pkg/mmg.zip
Connecting to 104.46.50.187:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-05-27 17:12:49 ERROR 404: Not Found.

Error download pkg/gmm-4.2.tar.gz
Download 2 times failed from http://pkgs.freefem.org/gmm-4.2.tar.gz of gmm-4.2.tar.gz
Try (2 times)  other site: http://104.46.50.187/pkg/gmm-4.2.tar.gz
--2024-05-27 17:12:49--  http://104.46.50.187/pkg/gmm-4.2.tar.gz
Connecting to 104.46.50.187:80... connected.
HTTP request sent, awaiting response... ERROR: cannot verify www.ljll.math.upmc.fr's certificate, issued by ‘/C=NL/O=GEANT Vereniging/CN=GEANT OV RSA CA 4’:
  Unable to locally verify the issuer's authority.
To connect to www.ljll.math.upmc.fr insecurely, use `--no-check-certificate'.
Error download pkg/mshmet.2012.04.25.tgz
Download failed from https://www.ljll.math.upmc.fr/frey/ftp/archives/mshmet.2012.04.25.tgz of mshmet.2012.04.25.tgz
Try other site: http://pkgs.freefem.org/mshmet.2012.04.25.tgz
ERROR: cannot verify www.ljll.math.upmc.fr's certificate, issued by ‘/C=NL/O=GEANT Vereniging/CN=GEANT OV RSA CA 4’:
  Unable to locally verify the issuer's authority.
To connect to www.ljll.math.upmc.fr insecurely, use `--no-check-certificate'.
Error download pkg/freeyams.2012.02.05.tgz
Download failed from https://www.ljll.math.upmc.fr/frey/ftp/archives/freeyams.2012.02.05.tgz of freeyams.2012.02.05.tgz
Try other site: http://pkgs.freefem.org/freeyams.2012.02.05.tgz
ERROR: cannot verify www.ljll.math.upmc.fr's certificate, issued by ‘/C=NL/O=GEANT Vereniging/CN=GEANT OV RSA CA 4’:
  Unable to locally verify the issuer's authority.
To connect to www.ljll.math.upmc.fr insecurely, use `--no-check-certificate'.
Error download pkg/boost_for_bemtool.tar.gz
Download failed from https://www.ljll.math.upmc.fr/~tournier/boost_for_bemtool.tar.gz of boost_for_bemtool.tar.gz
Try other site: http://pkgs.freefem.org/boost_for_bemtool.tar.gz
--2024-05-27 17:12:49--  http://pkgs.freefem.org/mshmet.2012.04.25.tgz
Resolving pkgs.freefem.org (pkgs.freefem.org)... 134.157.2.44
Connecting to pkgs.freefem.org (pkgs.freefem.org)|134.157.2.44|:80... connected.
HTTP request sent, awaiting response... --2024-05-27 17:12:49--  http://pkgs.freefem.org/freeyams.2012.02.05.tgz
Resolving pkgs.freefem.org (pkgs.freefem.org)... --2024-05-27 17:12:49--  http://pkgs.freefem.org/boost_for_bemtool.tar.gz
Resolving pkgs.freefem.org (pkgs.freefem.org)... 134.157.2.44
Connecting to pkgs.freefem.org (pkgs.freefem.org)|134.157.2.44|:80... connected.
HTTP request sent, awaiting response... 134.157.2.44
Connecting to pkgs.freefem.org (pkgs.freefem.org)|134.157.2.44|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-05-27 17:12:49 ERROR 404: Not Found.

Error download pkg/libpthread-google.tar.gz
Download 2 times failed from http://pkgs.freefem.org/libpthread-google.tar.gz of libpthread-google.tar.gz
Try (2 times)  other site: http://104.46.50.187/pkg/libpthread-google.tar.gz
--2024-05-27 17:12:49--  http://104.46.50.187/pkg/libpthread-google.tar.gz
Connecting to 104.46.50.187:80... connected.
HTTP request sent, awaiting response... 404 Not Found
404 Not Found
2024-05-27 17:12:49 ERROR 404: Not Found.
2024-05-27 17:12:49 ERROR 404: Not Found.

Error download pkg/mshmet.2012.04.25.tgz
Error download pkg/freeyams.2012.02.05.tgz
404 Not Found
2024-05-27 17:12:49 ERROR 404: Not Found.

Download 2 times failed from http://pkgs.freefem.org/mshmet.2012.04.25.tgz of mshmet.2012.04.25.tgz
Download 2 times failed from http://pkgs.freefem.org/freeyams.2012.02.05.tgz of freeyams.2012.02.05.tgz
Try (2 times)  other site: http://104.46.50.187/pkg/mshmet.2012.04.25.tgz
Try (2 times)  other site: http://104.46.50.187/pkg/freeyams.2012.02.05.tgz
Error download pkg/boost_for_bemtool.tar.gz
Download 2 times failed from http://pkgs.freefem.org/boost_for_bemtool.tar.gz of boost_for_bemtool.tar.gz
Try (2 times)  other site: http://104.46.50.187/pkg/boost_for_bemtool.tar.gz
--2024-05-27 17:12:49--  http://104.46.50.187/pkg/freeyams.2012.02.05.tgz
Connecting to 104.46.50.187:80... --2024-05-27 17:12:49--  http://104.46.50.187/pkg/mshmet.2012.04.25.tgz
Connecting to 104.46.50.187:80... connected.
HTTP request sent, awaiting response... connected.
HTTP request sent, awaiting response... --2024-05-27 17:12:49--  http://104.46.50.187/pkg/boost_for_bemtool.tar.gz
Connecting to 104.46.50.187:80... connected.
HTTP request sent, awaiting response... 128.42.33.23128.42.33.23

Connecting to www.caam.rice.edu (www.caam.rice.edu)|128.42.33.23|:80... Connecting to www.caam.rice.edu (www.caam.rice.edu)|128.42.33.23|:80... connected.
HTTP request sent, awaiting response... connected.
HTTP request sent, awaiting response... 302 Found
302 Found
Location: https://www.caam.rice.edu/software/ARPACK/SRC/arpack96.tar.gz [following]
Location: https://www.caam.rice.edu/software/ARPACK/SRC/patch.tar.gz [following]
--2024-05-27 17:12:55--  https://www.caam.rice.edu/software/ARPACK/SRC/patch.tar.gz
--2024-05-27 17:12:55--  https://www.caam.rice.edu/software/ARPACK/SRC/arpack96.tar.gz
Connecting to www.caam.rice.edu (www.caam.rice.edu)|128.42.33.23|:443... Connecting to www.caam.rice.edu (www.caam.rice.edu)|128.42.33.23|:443... connected.
connected.
503 Service Unavailable
503 Service Unavailable
503 Service Unavailable
2024-05-27 17:12:56 ERROR 503: Service Unavailable.

2024-05-27 17:12:56 ERROR 503: Service Unavailable.

2024-05-27 17:12:56 ERROR 503: Service Unavailable.

Error download pkg/gmm-4.2.tar.gz
Error download pkg/parmmg.zip
Error download pkg/mmg.zip
Download failed (MD5 check) from http://pkgs.freefem.org/gmm-4.2.tar.gz of gmm-4.2.tar.gz
Try other site: http://pkgs.freefem.org/gmm-4.2.tar.gz
Download failed (MD5 check) from https://github.com/prj-/ParMmg/archive/9cb2f7a22ef590d196d028970f462889bf610c53.zip of parmmg.zip
Try other site: http://pkgs.freefem.org/parmmg.zip
Download failed (MD5 check) from https://github.com/prj-/mmg/archive/1e26c551fdb969b38da46389bb0d95a35eb70d9d.zip of mmg.zip
Try other site: http://pkgs.freefem.org/mmg.zip
--2024-05-27 17:12:56--  http://pkgs.freefem.org/gmm-4.2.tar.gz
Resolving pkgs.freefem.org (pkgs.freefem.org)... --2024-05-27 17:12:56--  http://pkgs.freefem.org/parmmg.zip
Resolving pkgs.freefem.org (pkgs.freefem.org)... --2024-05-27 17:12:56--  http://pkgs.freefem.org/mmg.zip
Resolving pkgs.freefem.org (pkgs.freefem.org)... 134.157.2.44
134.157.2.44
Connecting to pkgs.freefem.org (pkgs.freefem.org)|134.157.2.44|:80... Connecting to pkgs.freefem.org (pkgs.freefem.org)|134.157.2.44|:80... connected.
connected.
HTTP request sent, awaiting response... HTTP request sent, awaiting response... 134.157.2.44
Connecting to pkgs.freefem.org (pkgs.freefem.org)|134.157.2.44|:80... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2024-05-27 17:12:56 ERROR 503: Service Unavailable.

Error download pkg/libpthread-google.tar.gz
Download failed (MD5 check) from http://pkgs.freefem.org/libpthread-google.tar.gz of libpthread-google.tar.gz
Try other site: http://pkgs.freefem.org/libpthread-google.tar.gz
--2024-05-27 17:12:56--  http://pkgs.freefem.org/libpthread-google.tar.gz
Resolving pkgs.freefem.org (pkgs.freefem.org)... 134.157.2.44
Connecting to pkgs.freefem.org (pkgs.freefem.org)|134.157.2.44|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-05-27 17:12:56 ERROR 404: Not Found.

404 Not Found
404 Not Found
2024-05-27 17:12:56 ERROR 404: Not Found.

2024-05-27 17:12:56 ERROR 404: Not Found.

Error download pkg/gmm-4.2.tar.gz
Error download pkg/parmmg.zip
Error download pkg/mmg.zip
503 Service Unavailable
503 Service Unavailable
503 Service Unavailable
2024-05-27 17:12:56 ERROR 503: Service Unavailable.

2024-05-27 17:12:56 ERROR 503: Service Unavailable.

2024-05-27 17:12:56 ERROR 503: Service Unavailable.

Error download pkg/freeyams.2012.02.05.tgz
Error download pkg/boost_for_bemtool.tar.gz
Error download pkg/mshmet.2012.04.25.tgz
Download failed (MD5 check) from https://www.ljll.math.upmc.fr/frey/ftp/archives/freeyams.2012.02.05.tgz of freeyams.2012.02.05.tgz
Try other site: http://pkgs.freefem.org/freeyams.2012.02.05.tgz
Download failed (MD5 check) from https://www.ljll.math.upmc.fr/frey/ftp/archives/mshmet.2012.04.25.tgz of mshmet.2012.04.25.tgz
Try other site: http://pkgs.freefem.org/mshmet.2012.04.25.tgz
Download failed (MD5 check) from https://www.ljll.math.upmc.fr/~tournier/boost_for_bemtool.tar.gz of boost_for_bemtool.tar.gz
Try other site: http://pkgs.freefem.org/boost_for_bemtool.tar.gz
--2024-05-27 17:12:56--  http://pkgs.freefem.org/freeyams.2012.02.05.tgz
Resolving pkgs.freefem.org (pkgs.freefem.org)... --2024-05-27 17:12:56--  http://pkgs.freefem.org/mshmet.2012.04.25.tgz
Resolving pkgs.freefem.org (pkgs.freefem.org)... --2024-05-27 17:12:56--  http://pkgs.freefem.org/boost_for_bemtool.tar.gz
Resolving pkgs.freefem.org (pkgs.freefem.org)... 134.157.2.44
134.157.2.44Connecting to pkgs.freefem.org (pkgs.freefem.org)|134.157.2.44|:80... 
Connecting to pkgs.freefem.org (pkgs.freefem.org)|134.157.2.44|:80... connected.
HTTP request sent, awaiting response... connected.
HTTP request sent, awaiting response... 134.157.2.44
Connecting to pkgs.freefem.org (pkgs.freefem.org)|134.157.2.44|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-05-27 17:12:56 ERROR 404: Not Found.

Error download pkg/libpthread-google.tar.gz
HTTP request sent, awaiting response... HTTP request sent, awaiting response... 404 Not Found
404 Not Found
2024-05-27 17:12:56 ERROR 404: Not Found.

2024-05-27 17:12:56 ERROR 404: Not Found.

404 Not Found
Error download pkg/freeyams.2012.02.05.tgz
2024-05-27 17:12:56 ERROR 404: Not Found.
Error download pkg/mshmet.2012.04.25.tgz

Error download pkg/boost_for_bemtool.tar.gz
301 Moved Permanently
Location: https://cmor.rice.edu/software/ARPACK/SRC/arpack96.tar.gz [following]
--2024-05-27 17:12:56--  https://cmor.rice.edu/software/ARPACK/SRC/arpack96.tar.gz
Resolving cmor.rice.edu (cmor.rice.edu)... 301 Moved Permanently
Location: https://cmor.rice.edu/software/ARPACK/SRC/patch.tar.gz [following]
--2024-05-27 17:12:56--  https://cmor.rice.edu/software/ARPACK/SRC/patch.tar.gz
Resolving cmor.rice.edu (cmor.rice.edu)... 151.101.155.52
151.101.155.52
Connecting to cmor.rice.edu (cmor.rice.edu)|151.101.155.52|:443... Connecting to cmor.rice.edu (cmor.rice.edu)|151.101.155.52|:443... connected.
connected.
HTTP request sent, awaiting response... HTTP request sent, awaiting response... 404 Not Found
2024-05-27 17:12:57 ERROR 404: Not Found.

Error download pkg/arpack96.tar.gz
Download failed from http://www.caam.rice.edu/software/ARPACK/SRC/arpack96.tar.gz of arpack96.tar.gz
Try other site: http://pkgs.freefem.org/arpack96.tar.gz
404 Not Found
2024-05-27 17:12:57 ERROR 404: Not Found.

Error download pkg/patch.tar.gz
Download failed from http://www.caam.rice.edu/software/ARPACK/SRC/patch.tar.gz of patch.tar.gz
Try other site: http://pkgs.freefem.org/patch.tar.gz
--2024-05-27 17:12:57--  http://pkgs.freefem.org/arpack96.tar.gz
Resolving pkgs.freefem.org (pkgs.freefem.org)... --2024-05-27 17:12:57--  http://pkgs.freefem.org/patch.tar.gz
Resolving pkgs.freefem.org (pkgs.freefem.org)... 134.157.2.44
Connecting to pkgs.freefem.org (pkgs.freefem.org)|134.157.2.44|:80... connected.
HTTP request sent, awaiting response... 134.157.2.44
Connecting to pkgs.freefem.org (pkgs.freefem.org)|134.157.2.44|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-05-27 17:12:58 ERROR 404: Not Found.

Error download pkg/arpack96.tar.gz
Download 2 times failed from http://pkgs.freefem.org/arpack96.tar.gz of arpack96.tar.gz
Try (2 times)  other site: http://104.46.50.187/pkg/arpack96.tar.gz
404 Not Found
2024-05-27 17:12:58 ERROR 404: Not Found.

Error download pkg/patch.tar.gz
Download 2 times failed from http://pkgs.freefem.org/patch.tar.gz of patch.tar.gz
Try (2 times)  other site: http://104.46.50.187/pkg/patch.tar.gz
--2024-05-27 17:12:58--  http://104.46.50.187/pkg/arpack96.tar.gz
Connecting to 104.46.50.187:80... connected.
HTTP request sent, awaiting response... --2024-05-27 17:12:58--  http://104.46.50.187/pkg/patch.tar.gz
Connecting to 104.46.50.187:80... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
503 Service Unavailable
2024-05-27 17:13:05 ERROR 503: Service Unavailable.

2024-05-27 17:13:05 ERROR 503: Service Unavailable.

Error download pkg/arpack96.tar.gz
Error download pkg/patch.tar.gz
Download failed (MD5 check) from http://www.caam.rice.edu/software/ARPACK/SRC/patch.tar.gz of patch.tar.gz
Try other site: http://pkgs.freefem.org/patch.tar.gz
Download failed (MD5 check) from http://www.caam.rice.edu/software/ARPACK/SRC/arpack96.tar.gz of arpack96.tar.gz
Try other site: http://pkgs.freefem.org/arpack96.tar.gz
--2024-05-27 17:13:05--  http://pkgs.freefem.org/patch.tar.gz
Resolving pkgs.freefem.org (pkgs.freefem.org)... --2024-05-27 17:13:05--  http://pkgs.freefem.org/arpack96.tar.gz
Resolving pkgs.freefem.org (pkgs.freefem.org)... 134.157.2.44134.157.2.44

Connecting to pkgs.freefem.org (pkgs.freefem.org)|134.157.2.44|:80... Connecting to pkgs.freefem.org (pkgs.freefem.org)|134.157.2.44|:80... connected.
connected.
HTTP request sent, awaiting response... HTTP request sent, awaiting response... 404 Not Found
404 Not Found
2024-05-27 17:13:05 ERROR 404: Not Found.
2024-05-27 17:13:05 ERROR 404: Not Found.

Error download pkg/arpack96.tar.gz
Error download pkg/patch.tar.gz
Read error (Connection timed out) in headers.
Retrying.

--2024-05-27 17:13:20--  (try: 2)  http://mumps.enseeiht.fr/MUMPS_5.0.2.tar.gz
Connecting to mumps.enseeiht.fr (mumps.enseeiht.fr)|147.127.176.144|:80... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2024-05-27 17:13:27 ERROR 503: Service Unavailable.

Error download pkg/MUMPS_5.0.2.tar.gz
Download failed from http://mumps.enseeiht.fr/MUMPS_5.0.2.tar.gz of MUMPS_5.0.2.tar.gz
Try other site: http://pkgs.freefem.org/MUMPS_5.0.2.tar.gz
--2024-05-27 17:13:27--  http://pkgs.freefem.org/MUMPS_5.0.2.tar.gz
Resolving pkgs.freefem.org (pkgs.freefem.org)... 134.157.2.44
Connecting to pkgs.freefem.org (pkgs.freefem.org)|134.157.2.44|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-05-27 17:13:27 ERROR 404: Not Found.

Error download pkg/MUMPS_5.0.2.tar.gz
Download 2 times failed from http://pkgs.freefem.org/MUMPS_5.0.2.tar.gz of MUMPS_5.0.2.tar.gz
Try (2 times)  other site: http://104.46.50.187/pkg/MUMPS_5.0.2.tar.gz
--2024-05-27 17:13:27--  http://104.46.50.187/pkg/MUMPS_5.0.2.tar.gz
Connecting to 104.46.50.187:80... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2024-05-27 17:13:35 ERROR 503: Service Unavailable.

Error download pkg/MUMPS_5.0.2.tar.gz
Download failed (MD5 check) from http://mumps.enseeiht.fr/MUMPS_5.0.2.tar.gz of MUMPS_5.0.2.tar.gz
Try other site: http://pkgs.freefem.org/MUMPS_5.0.2.tar.gz
--2024-05-27 17:13:35--  http://pkgs.freefem.org/MUMPS_5.0.2.tar.gz
Resolving pkgs.freefem.org (pkgs.freefem.org)... 134.157.2.44
Connecting to pkgs.freefem.org (pkgs.freefem.org)|134.157.2.44|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-05-27 17:13:35 ERROR 404: Not Found.

Error download pkg/MUMPS_5.0.2.tar.gz

ERROR: ../bin/build/download http://104.46.50.187/pkg/parmmg.zip pkg/parmmg.zip  FAILED
ERROR: ../bin/build/download http://104.46.50.187/pkg/mmg.zip pkg/mmg.zip  FAILED
ERROR: ../bin/build/download http://104.46.50.187/pkg/libpthread-google.tar.gz pkg/libpthread-google.tar.gz  FAILED
ERROR 2: ../bin/build/download http://pkgs.freefem.org/gmm-4.2.tar.gz pkg/gmm-4.2.tar.gz  FAILED
ERROR2: INVALID MD5 for gmm-4.2.tar.gz  d41d8cd98f00b204e9800998ecf8427e
ERROR 2: ../bin/build/download http://pkgs.freefem.org/parmmg.zip pkg/parmmg.zip  FAILED
ERROR 2: ../bin/build/download http://pkgs.freefem.org/mmg.zip pkg/mmg.zip  FAILED
ERROR2: INVALID MD5 for parmmg.zip  d41d8cd98f00b204e9800998ecf8427e
ERROR2: INVALID MD5 for mmg.zip  d41d8cd98f00b204e9800998ecf8427e
ERROR: ../bin/build/download http://104.46.50.187/pkg/freeyams.2012.02.05.tgz pkg/freeyams.2012.02.05.tgz  FAILED
ERROR: ../bin/build/download http://104.46.50.187/pkg/boost_for_bemtool.tar.gz pkg/boost_for_bemtool.tar.gz  FAILED
ERROR 2: ../bin/build/download http://pkgs.freefem.org/libpthread-google.tar.gz pkg/libpthread-google.tar.gz  FAILED
ERROR2: INVALID MD5 for libpthread-google.tar.gz  d41d8cd98f00b204e9800998ecf8427e
ERROR 2: ../bin/build/download http://pkgs.freefem.org/freeyams.2012.02.05.tgz pkg/freeyams.2012.02.05.tgz  FAILED
ERROR 2: ../bin/build/download http://pkgs.freefem.org/mshmet.2012.04.25.tgz pkg/mshmet.2012.04.25.tgz  FAILED
ERROR2: INVALID MD5 for freeyams.2012.02.05.tgz  d41d8cd98f00b204e9800998ecf8427e
ERROR2: INVALID MD5 for mshmet.2012.04.25.tgz  d41d8cd98f00b204e9800998ecf8427e
ERROR 2: ../bin/build/download http://pkgs.freefem.org/boost_for_bemtool.tar.gz pkg/boost_for_bemtool.tar.gz  FAILED
ERROR2: INVALID MD5 for boost_for_bemtool.tar.gz  d41d8cd98f00b204e9800998ecf8427e
ERROR: ../bin/build/download http://104.46.50.187/pkg/patch.tar.gz pkg/patch.tar.gz  FAILED
ERROR: ../bin/build/download http://104.46.50.187/pkg/arpack96.tar.gz pkg/arpack96.tar.gz  FAILED
ERROR 2: ../bin/build/download http://pkgs.freefem.org/patch.tar.gz pkg/patch.tar.gz  FAILED
ERROR2: INVALID MD5 for patch.tar.gz  d41d8cd98f00b204e9800998ecf8427e
ERROR2: INVALID MD5 for arpack96.tar.gz  d41d8cd98f00b204e9800998ecf8427e
ERROR: ../bin/build/download http://104.46.50.187/pkg/MUMPS_5.0.2.tar.gz pkg/MUMPS_5.0.2.tar.gz  FAILED
ERROR 2: ../bin/build/download http://pkgs.freefem.org/MUMPS_5.0.2.tar.gz pkg/MUMPS_5.0.2.tar.gz  FAILED
ERROR2: INVALID MD5 for MUMPS_5.0.2.tar.gz  d41d8cd98f00b204e9800998ecf8427e`

It seems like some of the links for packages are not working or obsolete.

**Comment by frederichecht** [comment]
Dear user,

Theoricaly this use is corrected in develop distribution. 

this file is ok for me. 

￼
Bien cordialement, 
Frédéric Hecht.   

-----------------------------------------------------------------------------------------------------------------------------------
Laboratoire  Jacques-Louis Lions,                UPMC Sorbonne Université
BC187,  4 Place  Jussieu,     75252  PARIS cedex 05,               France
Campus Jussieu,       Barre 15-25,           3 etage           Bureau 307 
Projet Alpines ,   Inria de Paris, 2 rue Simone Iff Voie DQ12 75012 Paris
tel:  +33 1 44274411,        mob: +33 6 62198986,     fax: +33 1 44277200
***@***.*** https://www.ljll.math.upmc.fr/hecht
software:  FreeFem++          web site:       http://www.freefem.org/ff++

**Comment by Geethesh-Naiyyalga** [comment]
Hello Frédéric Hecht,

We were trying to install FreeFEM on one of our servers and also on Ubuntu
22.04.

We were able to complete " ./configure --enable-download --enable-optim
--prefix=${HOME}/FreeFem-install " in both of them.
But soon we faced the above mentioned issue.

Kindly, brief us about "develop distribution".

Regards,
Geethesh

**Comment by cmd8** [comment]
Just use 
`git checkout develop`
