### ISSUE TITLE
Build breaks with clang-19: no member named 'stack' in 'pb2mat<K>'

### ISSUE THREAD

**Issue by yurivict** [FreeFem/FreeFem-sources#323]
```
lgfem.cpp:3135:56: error: no member named 'stack' in 'pb2mat<K>'
 3135 |     Problem::Data< FESpace > *data = pb->dataptr(this->stack);
      |                                                  ~~~~  ^
depbase=`echo string_def.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
c++ -DHAVE_CONFIG_H -I. -I../..  -I./../lglib -I./../bamglib -I./../Graphics -I./../femlib -I/usr/local/include -I/usr/include/suitesparse -I./../Eigen -I/usr/local/include/superlu -isystem /usr/local/include  -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -isystem /usr/local/include -DNDEBUG -O3 -std=gnu++14 -DBAMG_LONG_LONG  -DNCHECKPTR -fPIC -MT string_def.o -MD -MP -MF $depbase.Tpo -c -o string_def.o string_def.cpp &&\
mv -f $depbase.Tpo $depbase.Po
1 error generated.
```

[log](https://pkg-status.freebsd.org/beefy18/data/main-amd64-default/p380be9c7980a_s5036d9652a5/logs/freefem++-4.14_8.log)

Version: 4.14
clang-19
FreeBSD 14.1

**Comment by frederichecht** [comment]
Effectively, this code is wrong, I will correct soon as possible 
Best Regards, 

Frédéric Hecht.   

-----------------------------------------------------------------------------------------------------------------------------------
Laboratoire  Jacques-Louis Lions,                UPMC Sorbonne Université
BC187,  4 Place  Jussieu,     75252  PARIS cedex 05,               France
Campus Jussieu,       Barre 15-25,           3 etage           Bureau 307 
Projet Alpines ,   Inria de Paris, 2 rue Simone Iff Voie DQ12 75012 Paris
tel:  +33 1 44274411,        mob: +33 6 62198986,     fax: +33 1 44277200
***@***.*** https://www.ljll.fr/hecht
software:  FreeFem++          web site:       http://www.freefem.org/ff++

**Comment by frederichecht** [comment]
the correction 

diff --git a/src/fflib/lgfem.cpp b/src/fflib/lgfem.cpp
index 909f97421..e94ddec64 100644
--- a/src/fflib/lgfem.cpp
+++ b/src/fflib/lgfem.cpp
@@ -3319,7 +3319,7 @@ class pb2mat : public E_F0 {
   static E_F0 *f(const basicAC_F0 &args) { return new Plot(args); }
 
   AnyType operator( )(Stack s) const {
-    Problem::Data< FESpace > *data = pb->dataptr(this->stack);
+    Problem::Data< FESpace > *data = pb->dataptr(s);// coorect 9/11/24  Build breaks with clang-19
     if (SameType< K, double >::OK) {
       ffassert(!!data->AR);
       return SetAny< Matrice_Creuse< K > * >(&data->AR);
