### ISSUE TITLE
ARPACK not longer at https://www.caam.rice.edu/software/ARPACK/SRC/arpack96.tar.gz

### ISSUE THREAD

**Issue by loopless** [FreeFem/FreeFem-sources#327]
ARPACK is no longer available for download at that location. This breaks the build

**Comment by loopless** [comment]
> Use `make petsc-slepc` to switch to a proper URL. This is probably fixed in the `develop` branch as well.

Not sure what is meant here.

**Comment by prj-** [comment]
Just follow the instructions from https://github.com/FreeFem/FreeFem-sources?tab=readme-ov-file#freefem but first be sure to checkout the `develop` branch of the repository.
