### ISSUE TITLE
FF_INCLUDEPATH is not split when it contains several paths

### ISSUE THREAD

**Issue by cdoucet** [FreeFem/FreeFem-sources#36]
Environment variable FF_INCLUDEPATH is not split when it contains several paths separated by ":" on Unix systems. Here is the error message coming from examples++/include.edp (take a look at the last try):

>  --lex open :funct.edp
  --lex open :/home/cdoucet/Depots/github/FreeFem-sources/examples++:/home/cdoucet/Depots/github/FreeFem-sources/examples++-3d:/home/cdoucet/Depots/github/FreeFem-sources/examples++-load/funct.edp
 Error openning file funct.edp in: 
  -- try  :"funct.edp"
  -- try  :"/home/cdoucet/Depots/github/FreeFem-sources/examples++:/home/cdoucet/Depots/github/FreeFem-sources/examples++-3d:/home/cdoucet/Depots/github/FreeFem-sources/examples++-load/funct.edp"

when FF_INCLUDEPATH is defined by

`export FF_INCLUDEPATH=$FF_INCLUDEPATH:/home/cdoucet/Depots/github/FreeFem-sources/examples++:/home/cdoucet/Depots/github/FreeFem-sources/examples++-3d:/home/cdoucet/Depots/github/FreeFem-sources/examples++-load`

**Comment by frederichecht** [comment]
Il faut faire attention, j'ai mis un ";" pour windows 
car il y a des :  dans path window C:\Users\.... 

et je veux  un truc assez universel

**Comment by cdoucet** [comment]
Ok I see. Maybe it could be an improvement of user experience to display an explanatory error message in some unambiguous situations, e.g. when FF_INCLUDEPATH contains at least two ":" but no ";". But it is not mandatory as it appears in the documentation. Thanks.
