### ISSUE TITLE
Using a path when loading a mesh file (DSL)?

### ISSUE THREAD

**Issue by cdoucet** [FreeFem/FreeFem-sources#38]
When one loads a mesh in an edp file, e.g. `mesh3 Th("foo.mesh")`, no path seems to be used (see Mesh::read in femlib/fem.cpp). 

Unless there already exists some mechanism to use a path, I would like to modify Mesh::read so that it looks for mesh files in some path variable such as PATH, or FF_DATAPATH, or something like that.

Another strategy would be to look for mesh files in the same directory as the edp file which needs it, i.e. implementing the same behavior as the one submitted for include directive in issue #37.

What do you think of it?

**Comment by frederichecht** [comment]
yes
