### ISSUE TITLE
Which eigenv.h should be used?

### ISSUE THREAD

**Issue by cdoucet** [FreeFem/FreeFem-sources#39]
There are to header files named eigenv.h, one in src/medit and the other in src/libMesh. 
Their contents are different (diff output below):

> 1,4d0
< #ifdef __cplusplus
< extern "C" {
< #endif
< 
7,10d2
< 
< #ifdef __cplusplus
< }
< #endif

In examples++-load/Curvature.cpp, one finds `#include "eigenv.h"`. 

Which file does it refer to?
Can we delete the other one? 

(The "extern C" version seems to be the correct one, even though it may not be the original version.)

**Comment by frederichecht** [comment]
This file is in lib mesh directory

**Comment by cdoucet** [comment]
Thank you
