### ISSUE TITLE
Problem compiling on Debian 9.5 

### ISSUE THREAD

**Issue by MPenaR** [FreeFem/FreeFem-sources#48]
I was compiling the last version and everything went fine, until I made "make -j4". 
I get the error that there is no rule for "eigenvalue.o" needed for "libff.a"

I don't know if this is a known bug.

**Comment by sgarnotel** [comment]
I do not ever seen this bug. Do you use the master or develop branch?

Could you provide the `configure` step output please ?

**Comment by MPenaR** [comment]
Sorry it was my fault. I have had the great idea of adding AM_INIT_AUTOMAKE([subdir-objects]) to the configure.ac in order to get rid of the warnings of the type " X is in subdirectory but subdir is disabled".
Using the code as expected works fine

**Comment by sgarnotel** [comment]
Ok, we will fix this behavior in the future
