### ISSUE TITLE
P1nc in 3D

### ISSUE THREAD

**Issue by sophiechervet** [FreeFem/FreeFem-sources#49]
I need to use P1nc elements in 3d to validate an algorithm.
When I try, I get this error message : `sorry no cast to this 3d finite element`
Would it be possible to create this finite element space?

**Comment by frederichecht** [comment]
See examples++-loadtestp1dcnc.edp form the source 
https://github.com/FreeFem/FreeFem-sources/blob/master/examples%2B%2B-load/testp1dcnc.edp
