### ISSUE TITLE
MUMPS error

### ISSUE THREAD

**Issue by sgarnotel** [FreeFem/FreeFem-sources#51]
OS: ArchLinux
FreeFem++ version: develop

The MUMPS/MUMPS_seq plugin does not work anymore.
The compilation process complete correctly, but during the check, `LapMUMPS_seq.edp` fails

For example with this file [mumps.edp.txt](https://github.com/FreeFem/FreeFem-sources/files/2479006/mumps.edp.txt), the result is:
```
FreeFem++ mumps.edp
```
```
 Matrix morse type:6
 BuildSolverMUMPSseq<double>
[---:09016] *** An error occurred in MPI_Comm_rank
[---:09016] *** reported by process [3860070401,0]
[---:09016] *** on communicator MPI_COMM_WORLD
[---:09016] *** MPI_ERR_COMM: invalid communicator
[---:09016] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[---:09016] ***    and potentially your MPI job)
```

Any idea about this bug ?

**Comment by prj-** [comment]
Do you still have this error if you comment out this [line](https://github.com/FreeFem/FreeFem-sources/blob/develop/plugin/seq/MUMPS_seq.cpp#L188)?

**Comment by sgarnotel** [comment]
Yes I still have this error.

By commenting the line, that works well

**Comment by prj-** [comment]
Would that be an appropriate fix for you? There is really no need to call `MPI_Comm_rank` and I'm guessing there is something wrong in the `mpiseq` library. I'll make the commit once you give me the green light.

**Comment by sgarnotel** [comment]
That fix the problem when I use `load "MUMPS_seq"`
But when I use `load "MUMPS"` in a sequential script, `MUMPS_seq` is not loaded by defaut and the error is still here

**Comment by prj-** [comment]
Have you made the same fix in [MUMPS.cpp](https://github.com/FreeFem/FreeFem-sources/blob/develop/plugin/seq/MUMPS.cpp#L188)?

**Comment by sgarnotel** [comment]
Ok, that fix all. I have not realized that `SolveMUMPS_seq` is equally defined in `MUMPS.cpp`.

Thanks a lot, all work fine now

**Comment by frederichecht** [comment]
remark  in plugin/seq dir MUMPS.cpp and MUMPS_seq.cpp is the same code
Best Regards, 

Frédéric Hecht.   

-----------------------------------------------------------------------------------------------------------------------------------
Laboratoire  Jacques-Louis Lions,                UPMC Sorbonne Université
BC187,  4 Place  Jussieu,     75252  PARIS cedex 05,               France
Campus Jussieu,       Barre 15-25,           3 etage           Bureau 307 
Projet Alpines ,   Inria de Paris, 2 rue Simone Iff Voie DQ12 75012 Paris
tel:  +33 1 44274411,        mob: +33 6 62198986,     fax: +33 1 44277200
frederic.hecht@sorbonne-universite.fr https://www.ljll.math.upmc.fr/hecht
software:  FreeFem++          web site:       http://www.freefem.org/ff++

**Comment by maximefiore1** [comment]
Hello, I apologize for sending this message but I also used the command  load "MUMPS_seq" in Freefem++ and when I defined a sparsematrix (NSMAT=LNS(Uvvp,Uvvp,solver=sparsesolver);) (I think the error comes at this line), I get the same type of error as the one described previously:

[visu01:44612] *** An error occurred in MPI_Bcast
[visu01:44612] *** reported by process [3541041153,0]
[visu01:44612] *** on communicator MPI_COMM_WORLD
[visu01:44612] *** MPI_ERR_COMM: invalid communicator
[visu01:44612] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[visu01:44612] ***    and potentially your MPI job)

I am using a 4.5 version of Freefem++, would you know if I make something wrong with the code.


I thank you,

Maxime Fiore

**Comment by frederichecht** [comment]
REmark,

MUMPS is a parallel solver work with MPII; if you are on sequential code (no mpi)
You say Freefem++ but I think you use FreeFem++-mpi and the plugging "MUMPS_seq"  

1) try with FreeFem++  
and please send all the output.

**Comment by maximefiore1** [comment]
Hello,

I thank you for your answer, I have tried with the different executable available, this is the output obtained: 

with FreeFem++ executable:

 [pando01:81420] 1 more process has sent help message help-mpi-btl-openib.txt / no device params found
[pando01:81420] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
[pando01:81419] *** An error occurred in MPI_Bcast
[pando01:81419] *** reported by process [2850029569,0]
[pando01:81419] *** on communicator MPI_COMM_WORLD
[pando01:81419] *** MPI_ERR_COMM: invalid communicator
[pando01:81419] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[pando01:81419] ***    and potentially your MPI job)

with FreeFem++-nw executable:

[pando01:82088] 1 more process has sent help message help-mpi-btl-openib.txt / no device params found
[pando01:82088] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
[pando01:82087] *** An error occurred in MPI_Bcast
[pando01:82087] *** reported by process [3611557889,0]
[pando01:82087] *** on communicator MPI_COMM_WORLD
[pando01:82087] *** MPI_ERR_COMM: invalid communicator
[pando01:82087] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[pando01:82087] ***    and potentially your MPI job)

with Freefem++-mpi executable:

[pando01:82516] *** An error occurred in MPI_Init
[pando01:82516] *** reported by process [3585671169,0]
[pando01:82516] *** on a NULL communicator
[pando01:82516] *** Unknown error
[pando01:82516] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[pando01:82516] ***    and potentially your MPI job)
[pando01:82517] 1 more process has sent help message help-mpi-btl-openib.txt / no device params found
[pando01:82517] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages


I can share also the code if needed.

I thank you for your help.

Maxime Fiore
