### ISSUE TITLE
Execution problem in Ubuntu 18.04

### ISSUE THREAD

**Issue by paolopiers** [FreeFem/FreeFem-sources#52]
Hi. I have downloaded the ubuntu-source-master zip file but I cannot run FreeFem++.
I cd into the binaries folder by typing
`cd/freefem++-source-master/bin`
and then I run 
`./FreeFem++`
However, I am returned a message saying that the library `libhdf5_serial.so.10` is missing. Could you please help me out?

**Comment by frederichecht** [comment]
Yes,

I sorry, I do not where is this library.

Best Regards, 

Frédéric Hecht.   

----------------------------------------------------------------------------------------------
Laboratoire  Jacques-Louis Lions,             UPMC Sorbonne Universités
BC187,  4 Place  Jussieu,     75252  PARIS cedex 05,                France
Campus Jussieu,          Barre 15-25,           3 etage              Bureau 307 
Projet Alpines ,  Inria de Paris, 2 rue Simone Iff Voie DQ12 75012 Paris
tel:  +33 1 44274411,      mob: +33 6 62198986,    fax: +33 1 44277200
mail & web: frederic.hecht@sorbonne-universite.fr     https://www.ljll.math.upmc.fr/hecht/
software:  FreeFem++          web site:           http://www.freefem.org/ff++

**Comment by sgarnotel** [comment]
Hi,

Sorry for that. This is an Ubuntu 16.04 release, I don't know if it works
with Ubuntu 18.04.

You could try to install libhdf5-serial (I do not know the exact package
name) or link /usr/lib/libhdf5_serial.so.XX to usr/lib/libhdf5_serial.so.10.
If that leads to a bug, you have to compile source.

Best,
Simon Garnotel

**Comment by paolopiers** [comment]
Hi and thanks a lot to everyone for answering. 
I tried to link to link the library as Simon suggested and I also tried to install the library that Trophime suggested.
However, I keep up receiving the same error message about that missing library.

Best regards,

Paolo

**Comment by sgarnotel** [comment]
I try to build a .deb package as soon as possible

**Comment by Trophime** [comment]
@paolopiers could you send the output of ldd command?
By the way, I'm pretty sure that there is an up to date freefem++ package on Ubuntu 18.04.
Why not using it?

**Comment by Trophime** [comment]
May be this would do the trick (if your "still" want to use freefem++ latest version):
`sudo ln -sf /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so usr/lib/libhdf5_serial.so.10`

**Comment by sgarnotel** [comment]
I just add a [deb package](https://github.com/FreeFem/FreeFem-sources/releases/download/3.61/freefem_3.61.1-1_amd64.deb)

**Comment by paolopiers** [comment]
I have tried as @Trophime and @frederichecht  suggested.
Linking the library DOES the trick and the program is successfully executed. 
To recapitulate, this is how the problem related to the `.zip` bundle was solved:

1) Run `sudo ln -sf /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so usr/lib/libhdf5_serial.so.10`

2) This is the output of `./FreeFem++` 

`paolo@MADept:~/Downloads/freefem-ubuntu-3.61/freefem-source-master/bin$ ./FreeFem++
 Error parameter: ./FreeFem++ , version :   3.610000 (date Wed Jun 20 19:07:59 CEST 2018) 64bits 
 Syntaxe = ./FreeFem++   [ -v verbosity ] [ -fglut filepath ] [ -glut command ] [ -nw] [ -f] filename  [SCRIPT-arguments]
        -v      verbosity : 0 -- 1000000 level of freefem output 
        -fglut  filepath  : the file name of save all plots (replot with ffglut command ) 
        -glut    command  : change  command  compatible with ffglut  
        -gff     command  : change  command  compatible with ffglut (with space quoting)
        -nowait           : nowait at the end on window   
        -wait             : wait at the end on window   
        -nw  or -ng       : no ffglut, ffmedit  (=> no graphics windows) 
        -wg               : with graphic   (=>  graphics windows) 
        -ne               : no edp script output
        -cd               : Change dir to script dir
        -jc               : just compile
        -cdtmp            : Change dir to tmp dir (for test)

 without     default ffglut : ffglut
`

I also tried to compile an example and everything works perfectly.
Thanks a lot everyone for your help.

@sgarnotel I have tried your `.deb` package (version 3.610002) and it works perfectly. I tried to compile a basic example (the same as above) and I got the desired output. Thank you very much for your help!

**Comment by sgarnotel** [comment]
Thank you for your feedback. I close this issue as it's solved
