### ISSUE TITLE
j'essaye

### ISSUE THREAD

**Issue by penarhoat** [FreeFem/FreeFem-sources#6]
je tente le coup

**Comment by sgarnotel** [comment]
Do you have a question, comment or remark?

**Comment by frederichecht** [comment]
Hello,

I have a question 
How a none developer  can send modification on the source. 

I want to put  that in README-git

Amicalement,

Frédéric Hecht.   

----------------------------------------------------------------------------------------------
Laboratoire  Jacques-Louis Lions,             UPMC Sorbonne Universités
BC187,  4 Place  Jussieu,     75252  PARIS cedex 05,                France
Campus Jussieu,          Barre 15-25,           3 etage              Bureau 307 
Projet Alpines ,  Inria de Paris, 2 rue Simone Iff Voie DQ12 75012 Paris
tel:  +33 1 44274411,      mob: +33 6 62198986,    fax: +33 1 44277200
mail & web: frederic.hecht@sorbonne-universite.fr   https://www.ljll.math.upmc.fr/hecht/
software:  FreeFem++          web site:           http://www.freefem.org/ff++

**Comment by sgarnotel** [comment]
Yes, it is possible.
Developers that are not part of the official FreeFem team can fork the FreeFem-sources repository on their GitHub account, make modifications locally and submit a pull request to the FreeFem-sources repository

**Comment by penarhoat** [comment]
Fork it is then. Thank you.

**Comment by sgarnotel** [comment]
I append that to the [Wiki](https://github.com/FreeFem/FreeFem-sources.wiki.git)
