### ISSUE TITLE
v4 missing include

### ISSUE THREAD

**Issue by sgarnotel** [FreeFem/FreeFem-sources#60]
For MacOS, Linux and Windows:
`fatal error: umfpack.h: No such file or directory`

Under Ubuntu 16.04:
-  `umfpack.h`: The include directory `/usr/include/suitesparse` is missing in such Makefiles (`src/fflib/Makefile` and `src/mpi/Makefile`, possibly other), and using `ff-c++`

**Comment by frederichecht** [comment]
Je pense avoir corrigé
pas sur!!!

**Comment by prj-** [comment]
Still not compiling.
