### ISSUE TITLE
how to collect mesh infor from FreeFEM

### ISSUE THREAD

**Issue by ztdepztdep** [FreeFem/FreeFem-sources#62]
Dear sir:
    I want to use FreeFem as my adaptive mesh generator, how to output the mesh informs (cell neighbor, cell central, etc.)from FreeFem.

**Comment by sgarnotel** [comment]
You can find some useful information [here](https://doc.freefem.org/documentation/MeshGeneration/#mesh-connectivity-and-data)

In particular, have a look on the `adj` keyword

**Comment by frederichecht** [comment]
see section  https://doc.freefem.org/documentation/MeshGeneration/#mesh-connectivity-and-data
of the doc.
