### ISSUE TITLE
3d savemesh

### ISSUE THREAD

**Issue by ksugahar** [FreeFem/FreeFem-sources#63]
Attached is the edp file  when executed on windows 7 64bit.
It seems that ".mesh" works but ".msh" does not.

load "msh3"

int In = 1;
int Out = 0;
real dl = 0.01;

border O1(t=-pi,pi) {x=3.*cos(t);y=3.*sin(t); label=Out; }
border I1(t=pi,-pi) {x=1.*cos(t);y=1.*sin(t);label=In;}

mesh Th2 = buildmesh(O1(6.*pi/dl)+I1(2.*pi/dl));

int[int] rup=[0,5], rdown=[0,6], rmid=[1,1,2,2,3,3,4,4];
mesh3 Th3=buildlayers(Th2,10,zbound=[-2,2],labelmid=rmid,labelup=rup,labeldown=rdown);
savemesh(Th3,"test.mesh");
savemesh(Th3,"test.msh");

**Comment by sgarnotel** [comment]
Following the discussion in the mailing-list.

Look at this [file](https://github.com/FreeFem/FreeFem-sources/blob/master/examples%2B%2B-load/ttestio.edp) to save in gmsh format
