### ISSUE TITLE
Strange Results from 2D Rectangular EM Waveguide (compare with FEniCS + Pozar)

### ISSUE THREAD

**Issue by bryanbosworth** [FreeFem/FreeFem-sources#64]
I have replicated the approach described in section 34.1.1 of the FEniCS manual (edge elements in X,Y and Lagrangian in Z) separating transverse and longitudinal E field components to find rectangular waveguide mode cutoff frequencies. https://launchpadlibrarian.net/83776282/fenics-book-2011-10-27-final.pdf

The problem replicates Example 3.1 in Pozar "Microwave Engineering."  

If I run the attached file with "FreeFEM++ EFieldEigenCutoff.edp -s 40000" (-s sets the shift in meter^-2 for the eigenvalue problem) I can get the first few TM modes (a few spurious solutions pop up near 0 eigenvalue). Or if the boundary condition is modified to "+ on(horiz,vert,Ex=0,Ey=0);" I can get the first few TE modes. However, in both cases the solver works by treating only the Z field and forcing the transverse components to zero (not invalid in this case, but not the 3 component vector field solution it was supposed to find). My real interest is in more general non-TE/TM mode problems so this is rather discouraging. 

Side note: I implemented other modesolvers in FreeFEM++ in 2D before using only the H field and found that with P2 elements the penalty on the divergence caused the eigenvalues to be very unreliable, so I was very hopeful the formulation attached with edge elements would work. The element issue is summarized nicely here: https://fenicsproject.org/docs/dolfin/2018.1.0/python/demos/maxwell-eigenvalues/demo_maxwell-eigenvalues.py.html

(The reduction matrix routine in the middle of the script was tested to help the eigenvalue solver, but it wasn't necessary.)

Thank you!
[EFieldEigenCutoff2.txt](https://github.com/FreeFem/FreeFem-sources/files/2804784/EFieldEigenCutoff2.txt)

**Comment by frederichecht** [comment]
Sorry the Nedelec finite element 1 and 2 are wrong in 2d 
but First please read this boffi1.pdf <https://www.ljll.math.upmc.fr/hecht/ftp/Ecole-Cirm-EFEF5/boffi/boffi1.pdf>  you see you bug

a first correction..

**Comment by frederichecht** [comment]
I put the correction in  version  in develop branch.
