### ISSUE TITLE
MPIGMRES2D.edp does not converge when using FreeFem++-mpi compiled using Intel Libraries

### ISSUE THREAD

**Issue by aantao** [FreeFem/FreeFem-sources#70]
Hi,
When I run make check on FreeFem++ compiled using the the Intel Libraries, it does not converge. MPIGMRES3D.edp convegres using the same FreeFem++ binary.

When I check with FreeFem++ compiled using GCC, MPIGMRES2D.edp converges.
I am not sure what is happening.

**Comment by aantao** [comment]
Is there any further information I can provide to help with this issue?

**Comment by sgarnotel** [comment]
Hi,

There is a lot of changes right now in the FreeFem++ sources architecture and the core, we are quite overbooked, sorry for that.

Do you compile the version 4 ?
Could you try using GCC or clang if you have the same behavior ?

There is some breaking change and we introduce ffddm (@phtournier), this is probably the reason of your problem if you use the v4.

**Comment by aantao** [comment]
Hello, Thank you for your response! 

I am using 3.62. When I compile with gcc, I do not see the same behaviour, which is why I was trying to figure out what went wrong. I followed the intel compilation guide as posted in the documentation.

Only other notable thing I noticed when compiling was that the hips installation (in the intel compile) failed but other than everything else looked good.

**Comment by sgarnotel** [comment]
I don't use ICC personally, perhaps @prj- could answer that

**Comment by prj-** [comment]
I don't use `develop`, but `develop-v3`. Everything is fine there with Intel compilers and Intel MPI.

**Comment by aantao** [comment]
Thank you for your response. Would it be possible to share your compile steps, if different from the documentation. I will try to recompile and test.

On a side note, what is the difference between develop and develop-v3?

**Comment by sgarnotel** [comment]
@aantao `develop-v3` is the latest v3 developments
`develop` is the new v4, not as stable as v3 yet

**Comment by aantao** [comment]
I pulled the sources from master and used that to compile my two versions of FreeFem++. I will try to pull the version from devel-v3 and see if it helps.

**Comment by prj-** [comment]
[Here](http://jolivet.perso.enseeiht.fr/FreeFem-tutorial/index.html#pf1a) are my compile steps.

**Comment by aantao** [comment]
Thanks @prj- , I am unable to find the steps to compile with Intel. After compiling with GCC, I run make check, and am able to pass the tests.
If I compile with intel and run make check, I get stuck at mpigmres2D.edp as it does not converge. I checked the same FreeFem with Intel binary against mpigmres3D.edp and it converges.

These are the steps, I follow to compile with intel:
```
###FreeFem compile with intel

$source ffintel.sh  ###export OPTF=-axCOMMON-AVX512 and corresponding C,CXX,FC,F flags
$source psxevars.sh intel64
$git clone https://github.com/FreeFem/FreeFem-sources.git
$cd FreeFem-sources
$autoreconf -i
$./configure --enable-download --prefix=/software/freefem++/3.62-intel --with-hdf5=/software/hdf5/1.10.1/lib --with-mpiinc=-I${I_MPI_ROOT}/intel64/include --with-mpilibs="-L${I_MPI_ROOT}/intel64/lib/release_mt -L${I_MPI_ROOT}/intel64/lib -lmpicxx -lmpifort -lmpi -lmpigi -ldl -lrt -lpthread" --with-mpilibsc="-L${I_MPI_ROOT}/intel64/lib/release_mt -L${I_MPI_ROOT}/intel64/lib -lmpicxx -lmpifort -lmpi -lmpigi -ldl -lrt -lpthread" --with-mpi=/software/intel/compilers_and_libraries_2018.3.222/linux/mpi --disable-pastix
$./downlaod/getall -a
$./reconfigure --enable-download --prefix=/software/freefem++/3.62-intel --with-hdf5=/software/hdf5/1.10.1/lib --with-mpiinc=-I${I_MPI_ROOT}/intel64/include --with-mpilibs="-L${I_MPI_ROOT}/intel64/lib/release_mt -L${I_MPI_ROOT}/intel64/lib -lmpicxx -lmpifort -lmpi -lmpigi -ldl -lrt -lpthread" --with-mpilibsc="-L${I_MPI_ROOT}/intel64/lib/release_mt -L${I_MPI_ROOT}/intel64/lib -lmpicxx -lmpifort -lmpi -lmpigi -ldl -lrt -lpthread" --with-mpi=/software/intel/compilers_and_libraries_2018.3.222/linux/mpi --disable-pastix
$make
$make check   ###gets stuck because mpigmres2D.edp does not converge
$make install
```
