### ISSUE TITLE
Problem on GMRES solver in v4.0

### ISSUE THREAD

**Issue by zhaog6** [FreeFem/FreeFem-sources#74]
Professor,

I expect know the difference between GMRES in old version(v3.62) and in v4.0, thanks, because I find, in my code (that is right), the effect of using GMRES in v3.62  is different from the effect of using GMRES in v4.0. More specifically, the former can get convergent solution(I'm sure that's right), whereas the later is not convergent. I don't understand reasons. I would email my code to your mailbox. Thanks.

**Comment by frederichecht** [comment]
The code in version 4 is completely rewrite, 
now it is base of work of F. Nataf and P. Jolivet, P-H Tournier. 

the old code was take form IML (very old version, before 2000)  https://en.wikipedia.org/wiki/IML%2B%2B  software.
