### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by ztdepztdep** [FreeFem/FreeFem-sources#76]
I met the following error, when I make it. could you please give me some suggstions

g++ -shared -fPIC -g -DNDEBUG -O3 -mmmx -mavx -std=c++11 -DBAMG_LONG_LONG -DNCHECKPTR -fPIC -I/home/ztdep/Downloads/freefem++-4.0/download/include 'ff-Ipopt.o' -o ff-Ipopt.so '-L/home/ztdep/Downloads/freefem++-4.0/download/lib' '-lipopt' '-L/home/ztdep/Downloads/freefem++-4.0/download/lib' '-ldmumpsFREEFEM-SEQ' '-lzmumpsFREEFEM-SEQ' '-lmumps_commonFREEFEM-SEQ' '-lpordFREEFEM-SEQ' '-lpthread' '-lblas' '-L/home/ztdep/Downloads/freefem++-4.0/download/lib' '-lmpiseqFREEFEM-SEQ' /usr/lib64/gcc/x86_64-suse-linux/7/libgfortran.so /usr/lib64/gcc/x86_64-suse-linux/7/libquadmath.so
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lipopt
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:2020: ff-Ipopt.so] Error 1
make[3]: *** Waiting for unfinished jobs....

g++ -shared -fPIC -g -DNDEBUG -O3 -mmmx -mavx -std=c++11 -DBAMG_LONG_LONG -DNCHECKPTR -fPIC -I/home/ztdep/Downloads/freefem++-4.0/download/include 'ff-NLopt.o' -o ff-NLopt.so '-L/home/ztdep/Downloads/freefem++-4.0/download/lib' '-lnlopt_cxx'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lnlopt_cxx

**Comment by sgarnotel** [comment]
Could you provide more informations about your OS, configuration options, ...

**Comment by frederichecht** [comment]
just install the nlopt c++ package not only the c version.
