### ISSUE TITLE
gradient-singular finit elements

### ISSUE THREAD

**Issue by BHT-plas** [FreeFem/FreeFem-sources#78]
Hello,

I saw that it was possible to add new types of finite elements to freefem ++.
Do you think that the freefem ++ structure is compatible with the finite element family described in this paper (doi: 10.1109 / TAP.2012.2194660).
This kind of finit element should enable to treat the singularity of electric or magnetic field occuring at the junction of several dielectrics/ or sharp metal edges.

Best regards,

Bonjour,

J ai vu qu il etait possible d adjoindre de nouveaux types d elements finis a freefem++.
Pensez vous que la structure de freefem++ soit compatibles avec la famille d elements finis decrits dans ce papier de Webb (doi: 10.1109/TAP.2012.2194660)
Ce type d elements doit permettre de traiter les singularites de champ electrique ou magnetique advenant aux points de contacts de plusieurs dielectriques ou encore a proximite de pointes metalliques..

Bien cordialement,

**Comment by sgarnotel** [comment]
Hi,

Sorry this is not possible for now in FreeFEM. It's really difficult to make an approximation of different kind of finite elements on the same mesh
