### ISSUE TITLE
Heat exchanger example seems odd

### ISSUE THREAD

**Issue by flothesof** [FreeFem/FreeFem-sources#79]
Hi there,

thank you for putting together the nice new looking documentation.
I'm trying to get started with FreeFem and read through the [heat exchanger example](https://doc.freefem.org/tutorials/HeatExchanger/).
I just wanted to say two things about this example:
- I first got confused about the modelling of this situation: one conductor is modelled as a boundary condition (C1 at 60°C) while the other is as a volume.
- the text says that kappa in conductor C2 is 5 times larger than in C0 but the code says 3 times larger `Vh kappa=1 + 2*(x<-1)*(x>-2)*(y<3)*(y>-3);`

I think that this example could be made more beginner friendly by clearly putting an illustration of the situation with C0, C1 and C2 at the beginning of the problem description. Otherwise, adjusting the description to the code would reduce confusion (`Vh kappa=1 + 4*(x<-1)*(x>-2)*(y<3)*(y>-3);`).

Best regards,
Florian

**Comment by sgarnotel** [comment]
Hi,

Tanks a lot for your feedback!

This is designed as is because we have a transmitter (C1) and a receiver (C2), the first one volume (surface in 2D) is not important, so not meshed.

I will fix the value of kappa and add an illustration of the problem.

**Comment by sgarnotel** [comment]
Fixed

If you have any remark, don't hesitate

**Comment by flothesof** [comment]
Thanks for your quick action. I just checked the illustration you added, it looks great in the tutorial! Great work :)
