### ISSUE TITLE
Version 4.0 - things shown when verbosity=0

### ISSUE THREAD

**Issue by bbogo** [FreeFem/FreeFem-sources#80]
Hello,

In version 4.0 when using solver=Crout the following is shown even when verbosity = 0

SumpT=59287
  -- forward substitution L
  -- diagonal substitution D
  -- backward substitution  U

I guess this is not a critical issue, but it shows unnecessary information

Best regards,
  Beniamin

**Comment by bbogo** [comment]
Here is an example:

`verbosity = 0;

mesh Th = square(20,20);

/* Parameters */
real T0 = 20.0;
real T1 = 100.0;

/* Finite element spaces: P1 elements for the resolution of the linearized elasticity system */
fespace Vh(Th,P1);
/* Functions */
Vh   T,v;

macro grad(u) [dx(u),dy(u)]//

// Define the heat system //
problem heat(T,v,solver=Crout) =
    int2d(Th)(grad(T)'*grad(v))
   -int2d(Th)(T*grad(v)'*[0,1])
    +on(1,T=T1)
    +on(2,T=0);

heat;`

**Comment by frederichecht** [comment]
Ok, I will correct soon as possible. 
Best Regards, 

Frédéric Hecht.   

-----------------------------------------------------------------------------------------------------------------------------------
Laboratoire  Jacques-Louis Lions,                UPMC Sorbonne Université
BC187,  4 Place  Jussieu,     75252  PARIS cedex 05,               France
Campus Jussieu,       Barre 15-25,           3 etage           Bureau 307 
Projet Alpines ,   Inria de Paris, 2 rue Simone Iff Voie DQ12 75012 Paris
tel:  +33 1 44274411,        mob: +33 6 62198986,     fax: +33 1 44277200
frederic.hecht@sorbonne-universite.fr https://www.ljll.math.upmc.fr/hecht
software:  FreeFem++          web site:       http://www.freefem.org/ff++

**Comment by bbogo** [comment]
There's no rush, but I just wanted to point it out. 

Best regards,
  Beniamin Bogosel

**Comment by frederichecht** [comment]
Yes , this is simple so I do
