### ISSUE TITLE
An error in examples++-tutorial/cavity.edp

### ISSUE THREAD

**Issue by zhaog6** [FreeFem/FreeFem-sources#81]
Dear Professor,
There is an error in examples++-tutorial/cavity.edp. I find the value in effect figure is wrong (**Remark:** The value of stream function at the center of large vortex should be smallest, rather than largest) when running it to implement driven cavity flow.

Specifically，In line 41th
(example++-tutorial/cavity.edp) the code is as follows
```
35: solve streamlines(psi, phi)
36:      = int2d(Th) (
37:            dx(psi) * dx(phi)
38:          + dy(psi) * dy(phi)
39:      )
40:      + int2d(Th) (
41:            - phi * (dy(u1) - dx(u2))
42:      )
```

**It should be changed to**
```
41:           - phi * (dx(u2) - dy(u1))
```

**Comment by frederichecht** [comment]
OK, but at graphic level, no change.

**Comment by frederichecht** [comment]
I did  the computation and the sign is correct 
because curl curl = -Delta
so to find curl phi = u => - Delta u = curl u  
so the correct si OK. 
solve streamlines(psi,phi) =
int2d(Th)( dx(psi)*dx(phi) + dy(psi)*dy(phi))
+ int2d(Th)( -phi*(dy(u1)-dx(u2))) + on(1,2,3,4,psi=0);
