### ISSUE TITLE
Underscore support in variable, macro, function definitions

### ISSUE THREAD

**Issue by ffeppon** [FreeFem/FreeFem-sources#83]
Dear developpers,

Is there any reason why the underscore is not allowed in variable definitions? 

real var_1=0;

results in 
 
syntax error
  current line = 1
Compile error : syntax error
	line number :1, _
error Compile error : syntax error
	line number :1, _

Sometime it is nice to have underscores in variables name for readability. 

Thanks

**Comment by sgarnotel** [comment]
The underscore character is not allowed in the EDP scripts (see the [doc](https://doc.freefem.org/reference/))

It will be used in the future as an operator for time derivatives, for example

**Comment by frederichecht** [comment]
yes, but I reserved _ for other thing, 

Best Regards, 

Frédéric Hecht.   

-----------------------------------------------------------------------------------------------------------------------------------
Laboratoire  Jacques-Louis Lions,                UPMC Sorbonne Université
BC187,  4 Place  Jussieu,     75252  PARIS cedex 05,               France
Campus Jussieu,       Barre 15-25,           3 etage           Bureau 307 
Projet Alpines ,   Inria de Paris, 2 rue Simone Iff Voie DQ12 75012 Paris
tel:  +33 1 44274411,        mob: +33 6 62198986,     fax: +33 1 44277200
frederic.hecht@sorbonne-universite.fr https://www.ljll.math.upmc.fr/hecht
software:  FreeFem++          web site:       http://www.freefem.org/ff++
