### ISSUE TITLE
How to query values at each vertices?

### ISSUE THREAD

**Issue by RiverIntheSky** [FreeFem/FreeFem-sources#84]
Suppose phi is my variable on Vh. I've only seen examples with P1 functions, where phi[][i] works good. But I need P2 function and this won't give the correct result. Query by triangles like phi[][Vh(i,j)] works, but there are repetitions, and I also don't understand the correspondences between these triangles and the vertices.

**Comment by frederichecht** [comment]
Dear user,

In P2 the dofs are  on vertices and on edges so the numbering scramble edge and vertice

If you want only dof on vertices 

you can get the numbering of vertices

int[int] I(Th.nv);

for(int k=0; k<Th.nt; ++k)
for(int i=0; i<3; ++i)
  I[Th(k,i)] = Vh(k,i); 


phi[][I[i]) given the correct result ... 

or
fespace Wh(Th,P1);

Wh phi1=phi; 
and use phi1 not phi ... 


Best Regards, 

Frédéric Hecht.   

-----------------------------------------------------------------------------------------------------------------------------------
Laboratoire  Jacques-Louis Lions,                UPMC Sorbonne Université
BC187,  4 Place  Jussieu,     75252  PARIS cedex 05,               France
Campus Jussieu,       Barre 15-25,           3 etage           Bureau 307 
Projet Alpines ,   Inria de Paris, 2 rue Simone Iff Voie DQ12 75012 Paris
tel:  +33 1 44274411,        mob: +33 6 62198986,     fax: +33 1 44277200
frederic.hecht@sorbonne-universite.fr https://www.ljll.math.upmc.fr/hecht
software:  FreeFem++          web site:       http://www.freefem.org/ff++

**Comment by RiverIntheSky** [comment]
Thank you! This solved my problem. I need P2 for computation, but for plotting the mesh I guess I can only make use of the value on the vertices.
