### ISSUE TITLE
Simulation doesn't run when I don't look at it

### ISSUE THREAD

**Issue by RiverIntheSky** [FreeFem/FreeFem-sources#86]
I'm on an Arch Linux machine (Manjaro 18.0.4), and I'm having this problem with both version 3.62 and 4.00
That is if I let the simulation run in the background and do something else on my computer in the meanwhile, after a while I come back to check the state of the simulation, it sometimes happens that the simulation stops where I left or has only past very few steps. Only after a few seconds, it resumes again.
The most recent thing that happened today is that the simulation was outputting some results every ten minutes, then it didn't output anything during the whole three hours while I was at a meeting.
I never encountered similar problems with other software so I have no idea, is there any additional information I should provide?

**Comment by RiverIntheSky** [comment]
I think this problem is caused by plotting. I tried both on my Linux and Mac, if I don't keep the window active, sometimes the simulation just stops there and won't continue. FreeFem++-nw does not have this problem.

**Comment by RiverIntheSky** [comment]
But I didn't expect this behavior, what if I just want to let it plot and check the progress now and then, not to look at it all the time?

**Comment by prj-** [comment]
Are you using `wait = true` in your plot command? If no, I guess you'll have to switch to something else than `plot`, like ParaView.

**Comment by RiverIntheSky** [comment]
No, I'm not using `wait = true`. Now that you mention that, I think `wait = true` and `wait = false` don't differ essentially.
Of course, I could use external software, I also have other choices than ParaView. But I don't think this is the ideal solution, I use plot now and then because it's simple and built-in, I don't need to save it elsewhere and open it elsewhere. I don't know who is expecting this behavior, at least not me, I was expecting similar behavior as in MATLAB. Also nowhere in your documentation mentioned this behavior. Or if you did but I didn't find it then it's my fault.

**Comment by frederichecht** [comment]
Use the option -nw 
so FreeFem++ -nw .....

Best Regards, 

Frédéric Hecht.   

-----------------------------------------------------------------------------------------------------------------------------------
Laboratoire  Jacques-Louis Lions,                UPMC Sorbonne Université
BC187,  4 Place  Jussieu,     75252  PARIS cedex 05,               France
Campus Jussieu,       Barre 15-25,           3 etage           Bureau 307 
Projet Alpines ,   Inria de Paris, 2 rue Simone Iff Voie DQ12 75012 Paris
tel:  +33 1 44274411,        mob: +33 6 62198986,     fax: +33 1 44277200
frederic.hecht@sorbonne-universite.fr https://www.ljll.math.upmc.fr/hecht
software:  FreeFem++          web site:       http://www.freefem.org/ff++
