### ISSUE TITLE
load error: gsl

### ISSUE THREAD

**Issue by ouening** [FreeFem/FreeFem-sources#92]
FreeFEM version:4.1
OS: WIN10 64
Hi, When I run example **"bottle.edp"** in directory **FreeFem++\examples++-3d**, I get the error like below:
`-- FreeFem++ v  4.100000 (date mar.  9 avr. 2019 13:55:28)
 Load: lg_fem lg_mesh lg_mesh3 eigenvalue
    1 : load "msh3"(load: loadLibary D:\Applications\FreeFem++\\.\msh3 = 0)
    2 : load "medit"(load: loadLibary D:\Applications\FreeFem++\\.\medit = 0)
    3 : load "gsl"
**load error : gsl
         fail :**
list  prefix: 'D:\Applications\FreeFem++\\.\' list  suffix : '' , '.dll'
  current line = 3
Load error : gsl
        line number :3, gsl
error Load error : gsl
        line number :3, gsl
 code = 2 mpirank: 0
 try getConsole D:\Applications\FreeFem++\examples++-3d\bottle.edp
 save log in :  'D:\Applications\FreeFem++\examples++-3d\bottle.log'
wait enter ?`

Is it a bug in FreeFEM? Can someone help? Thanks!

**Comment by frederichecht** [comment]
you do not have libgsl so I miss this lib in the install under window. 

It is not a Bug!

**Comment by ouening** [comment]
So how can I fix it?

**Comment by frederichecht** [comment]
Dear user,

I am miss 2 library in the distribution

$ ldd gsl.dll  |grep min
        libgsl-23.dll => /mingw64/bin/libgsl-23.dll (0x66780000)
        libgslcblas-0.dll => /mingw64/bin/libgslcblas-0.dll (0x6be00000)



Best Regards, 

Frédéric Hecht.   

-----------------------------------------------------------------------------------------------------------------------------------
Laboratoire  Jacques-Louis Lions,                UPMC Sorbonne Université
BC187,  4 Place  Jussieu,     75252  PARIS cedex 05,               France
Campus Jussieu,       Barre 15-25,           3 etage           Bureau 307 
Projet Alpines ,   Inria de Paris, 2 rue Simone Iff Voie DQ12 75012 Paris
tel:  +33 1 44274411,        mob: +33 6 62198986,     fax: +33 1 44277200
frederic.hecht@sorbonne-universite.fr https://www.ljll.math.upmc.fr/hecht
software:  FreeFem++          web site:       http://www.freefem.org/ff++



I will rebuild a new version with this 2 library .

**Comment by frederichecht** [comment]
Dear user,

The new version is at 

http://www3.freefem.org/ff++/ftp/FreeFem++-4.1-win64-corei7-v2.exe

Best Regards, 

Frédéric Hecht.   

-----------------------------------------------------------------------------------------------------------------------------------
Laboratoire  Jacques-Louis Lions,                UPMC Sorbonne Université
BC187,  4 Place  Jussieu,     75252  PARIS cedex 05,               France
Campus Jussieu,       Barre 15-25,           3 etage           Bureau 307 
Projet Alpines ,   Inria de Paris, 2 rue Simone Iff Voie DQ12 75012 Paris
tel:  +33 1 44274411,        mob: +33 6 62198986,     fax: +33 1 44277200
frederic.hecht@sorbonne-universite.fr https://www.ljll.math.upmc.fr/hecht
software:  FreeFem++          web site:       http://www.freefem.org/ff++



with the miss library  libels

**Comment by ouening** [comment]
@frederichecht Thanks！

**Comment by lprc** [comment]
Did this error come back in version 4.2.1?

Putting the line `load "gsl"` in a file `test.edp` and executing it yields

```
-- FreeFem++ v  4.200001 (date Sat, Jun 08, 2019  6:08:22 PM git v4.2.1)
 Load: lg_fem lg_mesh lg_mesh3 eigenvalue
    1 : load "gsl"
load error : gsl
         fail :
list  prefix: 'C:\Program Files (x86)\FreeFem++\\.\' list  suffix : '' , '.dll'
  current line = 1
Load error : gsl
        line number :1, gsl
error Load error : gsl
        line number :1, gsl
 code = 2 mpirank: 0
 try getConsole C:\Users\simon\Desktop\test.edp
 save log in :  'C:\Users\simon\Desktop\test.log'
wait enter ?
```

I saw that the file `gsl.dll` indeed exists in the installation directory, but apparently it isn't found by FreeFem anyways. Is there some workaround? I tried using the absolute path to `gsl.dll` in the load command but that didn't work either.
