### ISSUE TITLE
Questions in "ExtractDofsonBorder.idp"

### ISSUE THREAD

**Issue by zhaog6** [FreeFem/FreeFem-sources#94]
Hello,
Recently, I have a question using function `ExtractDofsonBorder()`. I'd like to ask if it is necessary to solve Pbabciss(abslabs, atest) in the file "ExtractDofsonBorder.idp"? I try to remove or comment line 15-24 in this idp file and made the following test
```
macro ExtractDofsonBorder(labs,Wh,doflabs,orient)
{
	varf vlabsneg(u,v) = on(labs,u=-1);
	real[int] absc=vlabsneg(0,Wh);
	doflabs.resize(Wh.ndof);
	doflabs=0:Wh.ndof-1;
	sort(absc,doflabs);
	absc= absc? 1:0;
	doflabs.resize(absc.sum+0.5);
}
//
```
but it's still right, I don't understand why "Pbabciss(abslabs, atest)" need to be solved.
Thanks for your time

**Comment by sgarnotel** [comment]
The `Pbabciss` problem is just a way to sort the border points along the boundary (`orient=+-1`).
You can skip it using `orient=0`

**Comment by zhaog6** [comment]
Thanks for your answer. Previously, I did the following test
```
include "ExtractDofsonBorder.idp"
int nn = 2;
int[int] labs = [1, 2, 3, 4];
mesh Th = square(nn, nn);
fespace Vh(Th, P2);
Vh xx = x, yy = y;
int[int] doflabs;
ExtractDofsonBorder(labs, Vh, doflabs, 1);
for (int j = 0; j < doflabs.n; ++j)
{
    cout << doflabs[j] << ", (" << xx[][doflabs[j]] << ", " << yy[][doflabs[j]] << ")" << endl;
}
```
I has realized I use the "closed" border points before, that is `labs=[1,2,3,4] `, rather than `labs=[1, 2]` or `labs=[1, 2, 3]`or labels like that. When I take `labs=[1, 2]`, I see `ExtractDofsonBorder()` did sort the border points along the boundary by `Pbabciss` problem as your answer. But taking `labs` as a closed label `[1, 2, 3, 4]`, it seem to be disorder, of course, not to be complete disorder.

Thanks again

**Comment by sgarnotel** [comment]
Exactly, the sort is only possible with a non closed border
