### ISSUE TITLE
Build on Fedora with PETSc

### ISSUE THREAD

**Issue by pnavaro** [FreeFem/FreeFem-sources#97]
I am trying to build FreeFem from sources with PETSc on Fedora. I need to link with atlas library because some errors about cblas occurs. I tried several options
```
--with-lapack-ldflags="-L/usr/lib64/atlas -ltatlas"
--with-blas="-L/usr/lib64/atlas -ltatlas"
```
But it does not change the generated Makefiles in src/nw and src/mpi

If i add these flags by editing the Makefile in these directories it works. But i have another error with parmetis. I probably need to include the parallel version of scotch include with 
--with-scotch-include=/usr/include/openmpi-x86_64/
but it seems that options passed to configure tool has no effect.

**Comment by prj-** [comment]
Could you please send us your `config.log`?

**Comment by pnavaro** [comment]
Thanks to help me.
[config.log](https://github.com/FreeFem/FreeFem-sources/files/3147395/config.log)

**Comment by prj-** [comment]
1) Could you use `--with-lapack` instead of `--with-lapack-ldflags`?
2) FreeFEM will use the BLAS/LAPACK of PETSc since you use `--enable-download`. You need to make sure that the flags for the first time you do the `./configure` are correctly used by PETSc. If you are `./reconfigure`ing without nuking your `/usr/local/ff-petsc/` install, the same (wrong) BLAS/LAPACK from the very first time you built PETSc will be used over and over again.

**Comment by pnavaro** [comment]
Thanks it works until the compilation of the file parmetis.cpp
The macro SCOTCH_Num is not defined but we can find it in
/usr/local/ff-petsc/real/include/scotch.h
or
/usr/include/openmpi-x86_64/scotch.h
Both directories are included in the command line. Do you have an idea ?
Thanks you very much for your help.

```
../seq/ff-c++ -auto -mpi parmetis.cpp
eval ../seq/ff-c++ '-mpi' parmetis.cpp -pthread -Wl,-rpath -Wl,/usr/lib64/openmpi/lib -Wl,--enable-new-dtags -L/usr/lib64/openmpi/lib -lmpi_cxx -lmpi -I/usr/include/openmpi-x86_64 -Wl,-rpath,/usr/local/ff-petsc/real/lib -L/usr/local/ff-petsc/real/lib -lparmetis -I/usr/local/ff-petsc/real/include
/usr/lib64/openmpi/bin/mpic++ -c -fPIC -g -DNDEBUG -O3 -mmmx -mavx -std=c++11 -DBAMG_LONG_LONG -DNCHECKPTR -fPIC -I/usr/local/ff-petsc/real/include -I/usr/include -I../seq/include '-I/usr/include/openmpi-x86_64' '-I/usr/local/ff-petsc/real/include' 'parmetis.cpp'
In file included from parmetis.cpp:31:0:
/usr/include/openmpi-x86_64/parmetis.h:98:67: error: ‘SCOTCH_Num’ does not name a type
 void                        METISNAMEU(ParMETIS_V3_NodeND) (const SCOTCH_Num * const, SCOTCH_Num * const, SCOTCH_Num * const, const SCOTCH_Num * const, const SCOTCH_Num * const, SCOTCH_Num * const, SCOTCH_Num * const, MPI_Comm * const);
```

**Comment by pnavaro** [comment]
/usr/include/openmpi-x86_64/parmetis.h is the wrong header and it should be 
/usr/local/ff-petsc/real/include/parmetis.h
I removed the package ptscotch-openmpi-devel-parmetis and the compilation passed this step.

**Comment by prj-** [comment]
Right, your system ParMETIS seems outdated, best to use the one from PETSc. If you have other issue, please post your new `config.log` and compilation errors. Otherwise, could you close the issue? Thanks.

**Comment by pnavaro** [comment]
Thanks you very much for your help. It works.
