### ISSUE TITLE
Function ambiguity

### ISSUE THREAD

**Issue by FlorianeProg** [FreeFem/FreeFem-sources#98]
**Describe the bug**
Function ambiguity

**Expected behavior**
Should not compile

**Code**
```
func real[int] test (real[int] &u) {
	return u;
}

func real[int] test (real[int] &u) {
	return u;
}

real[int] u = [1, 2, 3];
//real[int] v = test(u);

LinearCG(test, u);
```

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - Version: v4.1 develop

**Comment by frederichecht** [comment]
Never compile the 2 fonctions test have the same prototype => bug 
no way to choose.

**Comment by sgarnotel** [comment]
This code really compiles, and leads to a seg fault

**Comment by prj-** [comment]
The segfault is trivial to fix. Getting a `function ambiguity` message is tougher.

**Comment by sgarnotel** [comment]
When we use the commented line, we correctly have a `function ambiguity` message, but when used in `LinearCG` (probably with other functions), this leads to a silent segfault.

Did users really have the right to write two functions with the same prototype ? (in edp file)

**Comment by prj-** [comment]
You have the message because, as Frédéric said, the function is being evaluated in the `.edp`. In the `.cpp`, there is a missing `ffassert` there https://github.com/FreeFem/FreeFem-sources/blob/master/src/fflib/lgfem.cpp#L585 (and probably in many other places).

**Comment by frederichecht** [comment]
a put a correction
  10 : //real[int] v = test(u);
   11 : 
   12 : LinearCG(test, u)
 Warning ambiguity Polymorphic Find 2
	 (	  <3KN_IdE> :   <P2KNIdE> )
	 (	  <3KN_IdE> :   <P2KNIdE> )
 We have ambiguity 2
  current line = 12
Assertion fail : (A)
