### ISSUE TITLE
An issue about PETSc in FreeFem++-4.0-MacOS_10.11.pkg

### ISSUE THREAD

**Issue by zhaog6** [FreeFem/FreeFem-sources#99]
Hi, 

1. It seems that FreeFem++-4.0-MacOS_10.11.pkg in "FreeFEM v4.0" is Beta-version (387MB), Might you update it?
2. I download the latest FreeFem++-4.0-MacOS_10.11.pkg from old website afterward（358MB）, but I have a problem using package FreeFem++-4.0-MacOS_10.11.pkg:
There is always show "load error: PETSc" when I run my programs which use `load "PETSc"` on Mac, but same one works well using other packages, I don't know if there is something wrong with this binary package used in Mac.

**Comment by frederichecht** [comment]
Hi, 

I have put a version on the web FreeFem++-4.1-MacOS_10.11.pkg <http://www3.freefem.org/ff++/ftp/FreeFem++-4.1-MacOS_10.11.pkg>  but not tested 
so I can have missing file

**Comment by frederichecht** [comment]
the version http://www3.freefem.org/ff++/ftp/FreeFem++-4.1-MacOS_10.11-corei5.pkg
work (tested)  on intel core I5/i7/I9 but not in intel core2 duo

**Comment by zhaog6** [comment]
Thank you very much，I uninstalled XQuartz(X11) that had ever been installed before, so it causes PETSc don't run on my Mac . Now the problem has been solved and the new package works well in all respects.

**Comment by zhaog6** [comment]
Thank you very much，I uninstalled XQuartz(X11) that had ever been installed before, so it causes PETSc don't run on my Mac . Now the problem has been solved and the new package works well in all respects.
